### PR TITLE
better EMT belt sprite

### PR DESCRIPTION
**Pull request by JoeHammad1844**
## About the PR

i made this a while ago but it wasnt used for some reason

## Media
image

- [x] have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

<!--
Make sure to take this Changelog template out of the comment block in order for it to show up.
:cl: JoeHammad
- tweak: Improved EMT belt sprite

### CODE REVIEW

**Comment by Verbalase** [comment]
yeah ngl this does look actually better

**Review by jorgun — APPROVED** [review]
looks good.

**Review by Piras314 — APPROVED** [review]

**Comment by Aidenkrz** [comment]
Okay not sure why @Piras314 merged this, the copyright in the meta needs to be updated.

**Comment by Piras314** [comment]
inhand and wearing sprites need to be changed along with copyright, reverting this

**Comment by JoeHammad1844** [comment]
my bad ill be on it

**Comment by JoeHammad1844** [comment]
#358

**Pull request merged**
