### PR TITLE
H.E.V suit

### PR DESCRIPTION
**Pull request by BombasterDS**
## About the PR
Great protect from radiation and caustic, small protection against blunt and shock
Can spawn with 5% chance in radiation suit locker

## Why / Balance
Gordon freeman saved my life

## Media
image

**Changelog**

:cl:
- add: H.E.V suit with a small chance can be found in radiation suit locker

## Release Notes

- **New Features**
  - Added the H.E.V helmet and H.E.V suit, enhancing protective gear options in the game.
  - Introduced a new clothing item, the ClothingOuterSuitHEV, with specific probability settings for resource management.
  - Implemented specialized storage units for H.E.V suits, improving inventory management.

- **Improvements**
  - Enhanced metadata for helmet and suit textures, improving visual representation and functionality in gameplay.
  - Added a new tag for HEVSuit to facilitate categorization.

These additions enrich the game's inventory and provide players with new strategies for survival in hazardous environments.

### CODE REVIEW

**Review by Piras314 — APPROVED** [review]

**Comment by BombasterDS** [comment]
> should probably specify the commit where you took the sprite from and the repository where it's from specifically though

done

**Comment by jorgun** [comment]
Needs a built in flashlight and geiger counter.
And shud have a battery slot for the flashlight but I can understand not adding that.
This looks to be space proof. Whit h is a good thing. For refueling collectors 
You shud add a hev locker for mappers

**Review by whateverusername0 — APPROVED** [review]
nice

**Comment by BombasterDS** [comment]
> Needs a built in flashlight and geiger counter. And shud have a battery slot for the flashlight but I can understand not adding that. This looks to be space proof. Whit h is a good thing. For refueling collectors You shud add a hev locker for mappers

Added HEV locker, but don't really want to add flashlight to it. It's already have geiger counter.

**Pull request merged**
