### PR TITLE
Goob Coin (Server Currency)

### PR DESCRIPTION
**Pull request by Aidenkrz**
Adds server currency to Goob.

## TODO:
- [x] Database
- [x]  Systems
  - [x] Currency
    - [x] Modify Classes (Add, Remove, Set, Get)
    - [x] Helper Classes (CanAfford, Stringify)
    - [x] Caching (We should cache the player's balance and update the database regularly instead of read/writing to the database constantly)
      - [x] Auto-Saving (Save at the end of each round, and we should save at a set interval.)
    - [x] Client System (Only pass thru GetBalance,) 
    - [x] Events
  - [x] Visuals
    - [x] Show balance in lobby
    - [x] Currency Popups 
- [ ] Payouts
  - [x] Surving Rounds
  - [x] Greentexting
  - [x] Admin Events (commands for admins to add currency, ingame event rewards, and contests like "make lobby art, top 3 get currency")
  - [x] Player Gifting (Send other players currency, also allows more complex things like github bounty issues.)
  - [ ] Challenges (equip a trait that has negative effects for the player, if they survive the round with it, give them extra currency)

**Changelog**
:cl:
- add: Goob coin! Super simple setup right now, you can't buy anything with goob coin yet, but you can earn it :-)

## Release Notes

- **New Features**
	- Introduced a new in-game currency system called "Goob Coin," allowing players to manage and view their currency balance in real-time.
	- Added console commands for players and administrators to check, gift, add, remove, and set currency balances.
	- Enhanced lobby UI to display player currency balance.
	- Integrated a reward system that grants currency for completing objectives.
	- Implemented asynchronous methods for retrieving and updating player currency in the database.

- **Bug Fixes**
	- Resolved issues related to memory leaks by properly unsubscribing from events.

- **Documentation**
	- Added localization strings for currency commands to improve user experience.

- **Chores**
	- Updated internal systems to support the new currency management features.

### CODE REVIEW

**Comment by GitHubUser53123** [comment]
what's that currency supposed to do

**Comment by DEATHB4DEFEAT** [comment]
> what's that currency supposed to do

funny things

**Comment by GitHubUser53123** [comment]
based

**Comment by gluesniffler** [comment]
> what's that currency supposed to do

Well, going off the source, which is monkestation from 13:
- Can be used for purchasing things from loadouts, such as cosmetic items (would be more effective with EE loadouts though)
- Can also be used for buying other misc cosmetics that you would want to lock behind playtime, like say, a toy Blood Red Hardsuit costume.
- Can be traded across players as a form of payment for things... which ends up driving a non insignificant amount of contributions over at MonkeStation.

Theres other things you can do or get with it, such as round start gimmicks like joining by being dropped in a washing machine, or starting with X amounts of maints pills. But thats more WYCI stuff.

**Comment by Aidenkrz** [comment]
> what's that currency supposed to do

I've clarified it further in the PR.

**Comment by toasterpm87** [comment]
Please add gambling

**Comment by Aidenkrz** [comment]
> Please add gambling

I'll think about it

**Comment by whateverusername0** [comment]
now make it a real cryptocurrency :godmode:

**Comment by deltanedas** [comment]
gobux

**Comment by Aidenkrz** [comment]
Got a good bit in and realized "huh, saving and writing to the database constantly probably isn't good, and forces me to use async shit, which I hate, so I'll add caches"

6 hours later we have virtually the same exact functionality but now its not Shitcode :tm: !

**Comment by Aidenkrz** [comment]
Condensed scope of this PR so i can get it added it and get an idea of how fast people earn coins before I add the shop

**Review by whateverusername0 — APPROVED** [review]
if it works it works

also would be funny to buy antag tokens with them :trollface:

**Comment by Aidenkrz** [comment]
> if it works it works
> 
> also would be funny to buy antag tokens with them :trollface:

no

**Comment by whateverusername0** [comment]
epic test fail

**Comment by JustSome1Nearby** [comment]
Soooo
Will there be any form of a shop... Some day?
Or is this never comming

**Comment by Piras314** [comment]
@JustSome1Nearby when you code it

**Pull request merged**
