### PR TITLE
Make cryo syringes usable in syringe guns.

### PR DESCRIPTION
**Pull request by a-person5660**
## About the PR
cryo syringe in syringe gun

## Why / Balance
funni

**Changelog**
:cl:
- tweak: Cryo syringes are usable in syringe guns now.

### CODE REVIEW

**Comment by a-person5660** [comment]
Also found out you can use bluespace beakers in modular grenades :trollface:

**Comment by Aidenkrz** [comment]
brother
https://github.com/Goob-Station/Goob-Station/pull/1017

**Comment by a-person5660** [comment]
That was also bluespace syringes, cryo syringes don't have 100u capacity like bluespace ones, surely this is fine.

**Comment by Piras314** [comment]
My complaint was cryo + bluespace. Just add darts

**Comment by a-person5660** [comment]
> My complaint was cryo + bluespace. Just add darts

what do you mean by add darts? the hypodarts?

**Pull request closed without merging**
