### PR TITLE
Holy damage

### PR DESCRIPTION
**Pull request by RealFakeSoof**
## About the PR

Added paranormal damage which consists of holy, unholy, spectral, and psychological damage. Also gave chaplain a gun that does holy damage.
## Why / Balance

Chap needs more feature
## Technical details

Sooooooooo much shitcode
## Media

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

https://discord.com/channels/1202734573247795300/1236697829171527841/1307186963996086402

**Changelog**

:cl:
- Made chaplain great again

## Release Notes

- **New Features**
  - Introduced new damage types: Holy, Unholy, Spectral, and Psychological.
  - Added a new damage group: Paranormal, enhancing damage categorization.
  - New weapon: WeaponGodGun, a battery-powered firearm with unique attributes.
  - New projectile: HolyLaser, featuring distinct visual effects and damage properties.
  - Chaplain role updated with a new healing component and enhanced starting gear.

- **Bug Fixes**
  - Corrected gear references for the Emergency Response Team roles.

- **Documentation**
  - Updated metadata for health analyzer and new weapon/projectile assets.

### CODE REVIEW

**Comment by BombasterDS** [comment]
Hi, i think you add too much damage types. There shouldn't be psychological damage, because game logic don't count mentality as real damage. Also about spectral and unholy damage - there is no real difference between them, so you have leave just one. (Spectral sounds more cooler).

**Comment by whateverusername0** [comment]
uhh how do you heal holy damage?

**Comment by whateverusername0** [comment]
> Hi, i think you add too much damage types. There shouldn't be psychological damage, because game logic don't count mentality as real damage. Also about spectral and unholy damage - there is no real difference between them, so you have leave just one. (Spectral sounds more cooler).

🤓 bro is striving to become wizden pm

**Comment by whateverusername0** [comment]
@RealFakeSoof i bet we'll have mood soon enough and psychological damage shouldn't really make you die
also yeah how do you heal holy damage and other? idk looks like you could permakill someone using it which is bad

**Comment by RealFakeSoof** [comment]
I was going to make some different stuff heal holy, but I forgot to and remembered after I made the pr lol

**Comment by Aidenkrz** [comment]
> @RealFakeSoof i bet we'll have mood soon enough and psychological damage shouldn't really make you die also yeah how do you heal holy damage and other? idk looks like you could permakill someone using it which is bad

we are not porting mood to LRP

**Comment by GroggleG** [comment]
> > @RealFakeSoof i bet we'll have mood soon enough and psychological damage shouldn't really make you die also yeah how do you heal holy damage and other? idk looks like you could permakill someone using it which is bad
> 
> we are not porting mood to LRP

dont port mood PERIOD I swear to fucking god.

**Comment by RealFakeSoof** [comment]
i suck at using git, so im just going to close this pr, and make a new one with the fixed stuff

**Pull request closed without merging**
