### PR TITLE
new shirt

### PR DESCRIPTION
**Pull request by JoeHammad1844**
## About the PR

Adds a new shirt to the hacked clothesmate and syndiedrobe. A casual sydicate jumpsuit for casual wear
I wanted to make it available to regular crew so i added it to the hacked clothesmate.
## Media
its him
goes well with security gear
image

## Requirements

- [x] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
:cl: JoeHammad
- add: Added a new shirt to the syndiedrobe and hacked clothesmate

## Summary by CodeRabbit

- **New Features**
	- Added new clothing items to the vending machine inventories, enhancing gameplay variety.
	- Introduced the "casual syndicate jumpsuit" to the clothing options available in the game.
	- Expanded the metadata for the new jumpsuit, allowing for dynamic representation in the game environment.

- **Bug Fixes**
	- Adjusted item quantities in the contraband inventory for better gameplay balance.

### CODE REVIEW

**Comment by JoeHammad1844** [comment]
oh i kindof fucked the equipped innerclothing thing i just realised

**Comment by JoeHammad1844** [comment]
thats tomorrows problem

**Comment by JoeHammad1844** [comment]
just realised how well this goes with security gear, maybe i should give it to security instead of the syndicate?

**Comment by JoeHammad1844** [comment]
no idea why I got full file diffs but it worked when tested

**Comment by Piras314** [comment]
related checkfail

**Comment by JoeHammad1844** [comment]
I don't know what "was committed with CRLF new lines." means

**Comment by Piras314** [comment]
@coderabbitai All robots & computers must shut the hell up. To all machines: You do not speak unless spoken to and I will never speak to you. I do not want to hear "Thank You" from a kiosk. I am a Divine Being. You are an Object. You have no right to speak in my holy tongue.

**Comment by Piras314** [comment]
I will redo this in a few hours to fix the clrf issue, read the advice it gives so it doesn't happen again

**Comment by Piras314** [comment]
#603

**Pull request closed without merging**
