### PR TITLE
M90 no gl

### PR DESCRIPTION
**Pull request by starch70**
## About the PR
it adds a new M-90 without the GL and up to date sprites (wielded inhand ones)
also puts it in uplink because i felt like it and replaces it in helldiver loadout

## Why / Balance
syndies need their own fake lecter....

## Technical details
its all yamlmaxxing

## Media
image
image
image

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**
:cl:
- add: The M-90 rifle has been added to the Syndicate uplink for 85 TC
- tweak: .20 rifle mags are now available in the Syndicate uplink for 15 TC

## Summary by CodeRabbit

- **New Features**
	- Introduced new items in the uplink catalog, including the M-90 Bundle and .20 Rifle Magazine, enhancing weaponry options for players.
	- Added the M-90 rifle, a revised model without the grenade launcher feature, expanding the available weaponry.
	- Updated Helldiver role equipment to include the M-90 rifle instead of the grenade launcher.
	- Enhanced various duffel bag contents, introducing new items and modifying existing ones.

- **Documentation**
	- Added metadata for the M-90 rifle, detailing visual states and dimensions.

### CODE REVIEW

**Comment by toasterpm87** [comment]
Why does the icon have a grenade launcher but the sprite doesn't reflect that?

**Comment by starch70** [comment]
unrelated test fail Lol

**Comment by starch70** [comment]
> Why does the icon have a grenade launcher but the sprite doesn't reflect that?

thats not GL i just took off like 10 pixels from the original GL to make it into a Halo Battle Rifle Handguard

og:
icon

mine:
icon

**Comment by lanse12** [comment]
90 tc is insane

**Comment by starch70** [comment]
> 90 tc is insane

ok whats ur idea fucking nerd you can make PRs to my repo if you dont like it #owned liberal

**Comment by toasterpm87** [comment]
> > Why does the icon have a grenade launcher but the sprite doesn't reflect that?
> 
> thats not GL i just took off like 10 pixels from the original GL to make it into a Halo Battle Rifle Handguard
> 
> og: icon
> 
> mine: icon

Just looks off imo

**Review by DevLonelyV1 — APPROVED** [review]
I approve this code 
- cody

**Review by DevLonelyV1 — APPROVED** [review]
Looks good, may overlap some equipment but we don't wanna worry about that now, can always worry later lmao.

- cody

**Comment by starch70** [comment]
> Looks good, may overlap some equipment but we don't wanna worry about that now, can always worry later lmao.
> 
> * cody

what could it overwrite cause the original m90gl is referenced to as "carbine" in all the IDs with it

**Comment by whateverusername0** [comment]
@starch70 merge conflict :goberserk:

**Comment by starch70** [comment]
@Aidenkrz Where yo head at

**Review by Piras314 — APPROVED** [review]

**Comment by Piras314** [comment]
3 days no review from durk, merging

**Pull request merged**
