### PR TITLE
The Pull Request to Rule Them All

### PR DESCRIPTION
**Pull request by Aidenkrz**
## About the PR
Title

**Changelog**

:cl:
- remove: Vulps and Harpies are no longer colorblind.
- tweak: Syndicate microwave has a smaller chance to explode when microwaving IDs.
- tweak: Normal microwave has chance to explode when microwaving IDs.
- tweak: You can now put any items on a burger.
- fix: Tranquility now affects all species.
- tweak: Tranquility now affects mobs, not just players.

### CODE REVIEW

**Comment by a-person5660** [comment]
vulp and harpie vision should be a trait imo

**Comment by Aidenkrz** [comment]
> vulp and harpie vision should be a trait imo

they have been a trait since day 1 bro

**Comment by a-person5660** [comment]
how did i miss that bruh

**Comment by Aidenkrz** [comment]
I was going to add more to this, but i wanna see anything burgers in game rn.

**Comment by Aidenkrz** [comment]
@coderabbitai review this pull request

**Pull request merged**
