### PR TITLE
Fix Pvs Serialization bug caused by amputations.

### PR DESCRIPTION
**Pull request by Procdox**
## About the PR
Add tracking of "original body" assignment to bodypart, organ, and bodypartappearance components. Clearing the fields on the limbs when the body assigned is deleted.

## Why / Balance
This was one of the sources of  ```Can't resolve "Robust.Shared.GameObjects.MetaDataComponent"```
errors in the logs that I was given.

## Technical details

The error was caused by references to bodyparts orginal bodies becoming stale when the og body was deleted.
I added component hashsets for each of the components on bodies that tracks parts that are claiming it as their og.
The issue can be reproduced by amputating a limb then gibbing the body. (Note that debug deleting the body does not provoke the error, you have to use "IC " methods to delete it.)

## Requirements

- [X ] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [ X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl:
- fix: server side serialization bug caused by amputations

### CODE REVIEW

**Comment by Procdox** [comment]
Still need to add Goobstation comments I suppose. But I wanted this to be reviewable since its touching Pvs structures.

**Comment by gluesniffler** [comment]
Merge conflict heads up, I'll be nuking `OriginalBody` from Body Parts since its fairly easy to spare ourselves from dealing with this lifecycle shitshow. Do keep it for organs though since thats gonna be my stopgap until organ health is real :tm:

**Comment by Piras314** [comment]
@gluesniffler

**Comment by Procdox** [comment]
No longer relevant after changes to remove OriginalBody tracking. 
https://github.com/Goob-Station/Goob-Station/pull/1003/commits/e145f42b88688fc4f16e6a590f4cb63ff07e690b

**Comment by gluesniffler** [comment]
I'll put a pin on it regardless since I dont know if organs might cause these same issues on entity deletion. As we are *still* tracking OriginalBody on those after all.

**Comment by Procdox** [comment]
If Organs are still tracking it, I will try to reproduce the same issue. If I can, I will fix it and reopen.

**Pull request closed without merging**
