### PR TITLE
Mimic but maybe it works now

### PR DESCRIPTION
**Pull request by Hmeister-real**
## About the PR
Should work, updated according to comment on #167 

## Media

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

### CODE REVIEW

**Comment by Aidenkrz** [comment]
SYNC AND REBASE AGAIN!!!!!!!!! GRAHH!!!

**Comment by Hmeister-real** [comment]
> SYNC AND REBASE AGAIN!!!!!!!!! GRAHH!!!

I HATE REBASING, I DON't WANNA

**Comment by Aidenkrz** [comment]
anyways change the weight to 10, and the chance to 0.01. 20 and 0.08 is a bit too high

**Comment by Verbalase** [comment]
failed checks ratio

**Comment by Hmeister-real** [comment]
> SYNC AND REBASE AGAIN!!!!!!!!! GRAHH!!!

ok tell me how to sync and rebase and il do it

**Pull request merged**
