### PR TITLE
new nukie shuttle

### PR DESCRIPTION
**Pull request by starch70**
## About the PR
replaces john station's infiltrator with one i made from a divine vison
has the same amount of equipment and shit

## Why / Balance
john station's nukie shuttle flies like a brick and is very ugly imo
also salv keeps breaking in from the front and stealing it (stalls the rounds where nukeops are cursed to use their nuke alot)
also also this one has liquid oxy and liquid nitrogen can instead of just 2 liquid oxy cans
also also also this one has a sustenance vendor and generators instead of AME because newkies cannot be trusted to not blow up their own shuttle

also (4x) this one has linked airlocks and directional fans so nukies dont space the entire ship lmao

Follows proper FAA navigational light standards.

## Media
image
image
image

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**
:cl:
- add: NEW NUKIE SHUTTLE!!! NEW NUKIE SHUTTLE!!!! ITS OVER FOR YOU SALVBROS!!! NO LONGER WILL YOU STEAL THE SHUTTLE WITH A SINGLE SEISMIC CHARGE!!

### CODE REVIEW

**Comment by JoeHammad1844** [comment]
WTF, NCWL HIND?? 
image
by the way the turrets at the docks are totally gonna hit the tank dispensers. move the turrets up one tile.

**Comment by TurboTrackerss14** [comment]
Where da reverse thrusters

**Comment by JoeHammad1844** [comment]
infront of the cockpit

**Comment by TurboTrackerss14** [comment]
I am infact fucking blind. :trollface:

**Comment by JustSome1Nearby** [comment]
We need a Syndicate Killdozer shuttle i think , yes yes... 
Buy lobbying bundle, get PA and Singu gen, set it up in front part of the shuttle (on this one there is perfect 3 tile opening), place 2 rows of Containment fields to not get eaten due to some physics oopsies. Anchor the   Singu magnet inside. 
Nothing can stop this
Singu insta kills all crew nearby, turrets defend the killdozer, there are 6 nukies inside armed to the teeth, Plast. Walls do not allow it to be broken...

**Comment by whateverusername0** [comment]
nice

**Pull request merged**
