### PR TITLE
Adds EE Run/Build Scripts.

### PR DESCRIPTION
**Pull request by gluesniffler**
## About the PR
Added the scripts folder from EE to the game files. In practice this means that instead of having to make commands to run both the client and server at once without building, you can just comfortably run your choice of ./buildall[debug/tools/release] and ./runquick[client/server/all].

## Why / Balance
QOL

## Requirements
- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

**Changelog**
:cl: Mocho
- add: Added EE build/run scripts

## Summary by CodeRabbit

- **New Features**
	- Introduced multiple batch and shell scripts for building projects in different configurations (Debug, Release, Tools).
	- Added scripts for running client and server applications without recompilation.
	- Implemented testing scripts for unit tests, integration tests, and YAML linting.

- **Documentation**
	- Updated `!README.txt` files to include new commands and clarify build configurations.

### CODE REVIEW

**Comment by gluesniffler** [comment]
lol heisentest

**Comment by yglop** [comment]
Is copy-pasting 2 commands into terminal is so hard for windows users?

**Comment by gluesniffler** [comment]
> Is copy-pasting 2 commands into terminal is so hard for windows users?

i am hardworking enough to code surgery

i am lazy enough to not want to do anything but press up and down on my terminal :trollface:

**Comment by Aidenkrz** [comment]
>  In practice this means that instead of having to make commands to run both the client and server at once without building,

this mf doesn't know how to edit launch files

**Pull request merged**
