### PR TITLE
Remove Train from the Map Pool

### PR DESCRIPTION
**Pull request by Piras314**
## About the PR

Removed Train Station from the map pool.

## Why / Balance

People really really really hate Train Station, more than Detroit (Barratry) back in my day. I thought it was for Halloween only but apparently not. This just removes it from master though, so it will stay with the Halloween update.

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl:
- remove: Removed Train Station from the map pool.

## Summary by CodeRabbit

- **New Features**
	- Updated game map pool by removing the broken map `Cog`.
	- Commented out the map `Train` with a new note reflecting user feedback.
  
- **Bug Fixes**
	- Removed a problematic map from the configuration to enhance gameplay experience.

### CODE REVIEW

**Comment by a-person5660** [comment]
also make train not a low pop map on halloween branch.

**Comment by Piras314** [comment]
Halloween is tomorrow it doesn't matter so much.

**Comment by a-person5660** [comment]
fair enough

**Comment by HenhenIII** [comment]
This must be merged **NOW!!!!**

**Comment by starch70** [comment]
if this gets merged unban me for helping saw it in half

SyzE3dEFRnCHcEyPeWoLoA

**Comment by Piras314** [comment]
also I'm going to make a PR to re-add detroit/barratry to compensate :)

**Pull request merged**
