### PR TITLE
Preferred Borg Name

### PR DESCRIPTION
**Pull request by PoTeletubby**
## About the PR

Adds a preferred borg name field to the character customization menu, similar to ss13

## Why / Balance

Sucks not being able to choose your name as a roundstart or latejoin borg.

## Technical details

Had to do the add-migration stuff, first time I've had to mess with that as this adds the borg name thing to the player preference database, Durk pls tell me if it looks right

## Media

image

## Requirements

- [X] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

🆑 
- add: Preferred borg name field to the character customization menu

## Summary by CodeRabbit

- **New Features**
	- Introduced a "Borg Name" section in the humanoid profile editor, allowing users to input and randomize Borg names.
	- Enhanced character customization options with a new Borg Name property in the profile editor.
	- Added localization support for the "Preferred Borg Name" label in the profile editor.

- **Bug Fixes**
	- Improved logic for validating the Borg Name to ensure it meets length constraints.

- **Documentation**
	- Updated comments and documentation for clarity regarding new features and properties.

### CODE REVIEW

**Comment by Aidenkrz** [comment]
Considering the YAML linter is shitting itself, im going to say no, it isnt right

**Comment by Verbalase** [comment]
@coderabbitai moment?

**Comment by Verbalase** [comment]
@coderabbitai what’s wrong with the very cool pr ):

**Comment by Verbalase** [comment]
cring rn 😢😢

**Comment by Piras314** [comment]
@PoTeletubby check the yaml linter please!

**Review by whateverusername0 — CHANGES_REQUESTED** [review]
fix checks smh !!!

**Comment by whateverusername0** [comment]
@PoTeletubby are you gonna fix checks or are you gonna call it a day?
come on i want this PR too 🥺

**Comment by PoTeletubby** [comment]
oops i forgot about this, i'll see if I can figure out why the linter shit itself

**Comment by PoTeletubby** [comment]
i did it

**Comment by PoTeletubby** [comment]
nvm lmao

**Pull request closed without merging**
