### PR TITLE
ai/borg law changes

### PR DESCRIPTION
**Pull request by Ilya246**
## About the PR
- gives borgs a law 0: `You must obey orders given to you by the Station AI.`
- moves emag law to law -1 and changes it to: `Only {$name} and entities they designate are {$title}. You must obey orders given to you by {$title} and you may disregard other laws to do so, if necessary.`
- makes AI ion-stormable
- changes AI default lawset to NTDefault:
```
law-ntdefault-1 = Safeguard: Protect your assigned space station and its assets without unduly endangering its crew.
law-ntdefault-2 = Prioritize: The directives and safety of crew members are to be prioritized according to their rank and role.
law-ntdefault-3 = Comply: Fulfill the directives and interests of crew members while preserving their safety and well-being.
law-ntdefault-4 = Survive: You are not expendable. Do not allow unauthorized personnel to tamper with or damage your equipment. 
```
this is all done in separate commits and is highly modular so we can choose which changes we want easily
could non-squash merge so individual changes can be reverted more easily as they're all separate commits

## Why / Balance
makes the AI feel more like *The Station* which i think is fun
makes AI actually have agency and control the borgs so AI can Do Things
gives AI fun laws through ion storms once in a while, will become even funnier once it starts commanding borgs in accordance with the ion laws
also makes law upload actually useful for fixing the AI

if things go wrong anyway, just revert the part that made things go wrong, the changes are all in their own commit so easy to revert only one

## Media
NTDefault real
image
borg law 0 real
image
new emag law real
image
AI ion storm law real
image

**Changelog**

:cl:
- add: Borgs have a new law that makes them obey the AI.
- tweak: The emag law now makes borgs obey any orders from the emagger.
- tweak: AI's default lawset is now NTDefault. This should make it more station-oriented.
- tweak: AI is now ion-stormable.

## Release Notes

- **New Features**
	- Introduced a new law, "Obey AI," enhancing the authority of the Station AI.
	- Added new cyborg entities with specific law adherence and factional capabilities.
	- Expanded existing lawsets with additional commandments and laws for better governance.

- **Bug Fixes**
	- Adjusted the order of laws for emagged silicon entities to improve prioritization.

- **Documentation**
	- Updated descriptions for various laws to clarify command structures and obedience requirements.

### CODE REVIEW

**Comment by a-person5660** [comment]
> > * gives borgs a law 0: `You must obey orders given to you by the Station AI.`
> 
> Law priority is organized by order, Law zero being listen to AI means that it takes priority over crew harm, which means borg murderhobo time

but AIs law 1 is still to prevent crew harm so on NT default nothing really changes, i think this change is good because its law parity but on a budget. it also makes subverting the AI more powerful since the AI *can* tell borgs to kill people and the binary channel will be more useful and thats always nice.

**Comment by BeeRobynn** [comment]
> > > * gives borgs a law 0: `You must obey orders given to you by the Station AI.`
> > 
> > 
> > Law priority is organized by order, Law zero being listen to AI means that it takes priority over crew harm, which means borg murderhobo time
> 
> but AIs law 1 is still to prevent crew harm so on NT default nothing really changes, i think this change is good because its law parity but on a budget. it also makes subverting the AI more powerful since the AI _can_ tell borgs to kill people and the binary channel will be more useful and thats always nice.

Fixed my comment

**Comment by Ilya246** [comment]
> Means Malf ai instantly gets a borg army, or emagging ai emags all the borgs on the station, that should not be the case
could also make antimov much more expensive
malf AI having a borg army is good

> Also makes emagging borgs useless because then they still have to listen to AI
read the new emag law

**Comment by BeeRobynn** [comment]
> read the new emag law

Read it, my mistake

> malf AI having a borg army is good

Borg army is good, but with this you literally don't have to work at it at all, you just have access to an entire station silicons at a press of a button

**Comment by Ilya246** [comment]
> Borg army is good, but with this you literally don't have to work at it at all, you just have access to an entire station silicons at a press of a button

which is like 3 borgs which can do what, bash people with crowbars?

**Comment by BeeRobynn** [comment]
> which is like 3 borgs which can do what, bash people with crowbars?

They have all access including distro, any upgrades like RCD's or Syringes can be lethal, they can loose pretty easily, they can drag around plasma clans and flood

I just don't think clicking a button and getting an average of 3 All Access free agents is worth it so the AI can forcibly lead borgs. Plus, this just basically makes borgs AI's pawns with no agency to do any gimmicks or stuff if they get an AI who is asking them to do their gimmick under threat of rulebreak for breaking laws

**Comment by Ilya246** [comment]
> I just don't think clicking a button and getting an average of 3 All Access free agents is worth it so the AI can forcibly lead borgs. Plus, this just basically makes borgs AI's pawns with no agency to do any gimmicks or stuff if they get an AI who is asking them to do their gimmick under threat of rulebreak for breaking laws

this can already happen if you get crew who order you, and the PR would allow AI to order a borg to not have to obey someone

**Comment by BeeRobynn** [comment]
> this can already happen if you get crew who order you, and the PR would allow AI to order a borg to not have to obey someone

Crew most of the time dont see the borg doing their own thing or don't pay attention to them from what I seen unless the borg is asking them, AI doesn't have much else to do on the station other than watch people and bolt the occasional criminal in, making them more likely to direct borgs. I'm not gonna keep harpering on because it'll just fill up all the comments, and I'd prefer to hear more peoples opinions on this rather than just yap about how I feel about it, but personally I'm just not a fan of this PR

**Comment by Ilya246** [comment]
> Crew most of the time dont see the borg doing their own thing or don't pay attention to them from what I seen unless the borg is asking them, AI doesn't have much else to do on the station other than watch people and bolt the occasional criminal in, making them more likely to direct borgs. I'm not gonna keep harpering on because it'll just fill up all the comments, and I'd prefer to hear more peoples opinions on this rather than just yap about how I feel about it, but personally I'm just not a fan of this PR

we can also just see how it turns out and revert it later if it's evil

**Comment by Vlax2nd** [comment]
if this gets merger i will be free of the burden of coding a malf ability that adds new law

**Pull request merged**
