### PR TITLE
bagel update

### PR DESCRIPTION
**Pull request by Icepicked**
## About the PR

added BSO and NTR rooms to Bagel
- Added new Airlocks and Door Electronics, "CentCommCap" using Central Command and Captain Access.
- Added BSO and NTR rooms to Bagel, below Security.

## Media

Screenshot 2024-09-29 225235
image

## Requirements

- [ ] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [ ] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl:
- add: Added BSO and NTR rooms to Bagel.
- add: Added a Mail area to Bagel.
- add: Added Airlock using Central Command and Captain access.

## Summary by CodeRabbit

- **New Features**
	- Introduced new entities to enhance gameplay, including various furniture and command systems such as `AirlockCommandCommandLocked`, `MailingUnit`, and `VendingMachineMailDrobe`.
	- Enhanced atmospheric management with new components for detailed control.
	- Updated visual representations of tiles in the game environment.

- **Bug Fixes**
	- Adjusted positional values for several entities to improve layout and interaction.

- **Documentation**
	- Updated entity definitions and properties for clarity and better user understanding.

### CODE REVIEW

**Comment by Icepicked** [comment]
Kk, dont merge this untill I commit that, it will br in like 6 hours.

**Review by BombasterDS — COMMENTED** [review]
Better to move oasis to different PR imo.

**Comment by Icepicked** [comment]
Yeah, didnt mean to PR it here. Ill fix it when I get home.

**Comment by Icepicked** [comment]
@Piras314 chat this PR is ready to merge I believe.

**Pull request merged**
