### PR TITLE
Elite nukie suit resprite

### PR DESCRIPTION
**Pull request by InfinityPandaRed**
## About the PR

Resprites the Elite nukie hardsuit to have the classic 4 red eyes
## Why / Balance

Sometimes players confuse nukies with elite hardsuits for sec officers hardsuits
## Media

nukie resprite 2
nukie resprite

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl:
- tweak: The Nukie Elite Hardsuit has been resprited to have the classic "four-eyes".

## Summary by CodeRabbit

- **Chores**
	- Updated copyright statements in the `meta.json` files for the `syndieelite.rsi` textures to include attribution to "InfinityRedPanda" as an editor.

### CODE REVIEW

**Comment by InfinityPandaRed** [comment]
btw dont mind github saying i deleted the files, i dont know why it says that

**Review by Piras314 — APPROVED** [review]
github doesn't say you deleted stuff, it's just saying the file size is smaller, it just displays that in probably one of the stupidest ways I've ever seen.

you didn't do the CL quite right but I'll edit it for you

**Comment by Icepicked** [comment]
oh but I get executed for it 😔

**Comment by cheki-ss14** [comment]
This is fucking sick, I like it a lot. Resembles the old elite suit sprite with a fresh updated look

**Comment by whateverusername0** [comment]
@InfinityPandaRed can you instead pr the sprite from gaming rework (#659)?
image

**Comment by BombasterDS** [comment]
> @InfinityPandaRed can you instead pr the sprite from gaming rework (#659)? image whatever fits i just think that elite should have a somewhat different look from the bloodred, not just the color change

imo elite suit from this pr looks cooler

**Comment by InfinityPandaRed** [comment]
which you mean my pr?

**Comment by Piras314** [comment]
resolve the conflicts @InfinityPandaRed

**Pull request closed without merging**
