### PR TITLE
Port Mail from DeltaV/Frontier

### PR DESCRIPTION
**Pull request by BombasterDS**
## About the PR
Ported Mail system, Maildrobe and MailMetrics from DeltaV with Frontier updates.

Didn't add courier job because cargo tech ofter have nothing to do, so they can work as couriers.
Added mailman drip to cargo tech loadout.
Cleaned up DeltaV/Frontier exclusive prototypes from mails.

## Why / Balance
Mail is super funny.

## Media
image

**Changelog**

:cl:
- add: Mail added to the game.

## Summary by CodeRabbit

- **New Features**
  - Introduced a comprehensive mail metrics system, including a user interface for displaying mail statistics.
  - Added a mail teleportation system for improved mail delivery efficiency.
  - Implemented visual representation of mail parcels based on recipient jobs.
  - New components for tracking mail delivery statistics and managing logistics.

- **Bug Fixes**
  - Resolved issues with mail handling and delivery processes to ensure smoother gameplay.

- **Documentation**
  - Updated localization files for improved user experience.

- **Style**
  - Enhanced UI design for mail metrics display.

- **Tests**
  - Added tests for new mail systems and components to ensure functionality and reliability.

### CODE REVIEW

**Comment by Piras314** [comment]
Is the rate at which mail is sent lower than on delta-v/frontier?

**Comment by BombasterDS** [comment]
> Is the rate at which mail is sent lower than on delta-v/frontier? It probably should be half or a quarter of what it is there.

I didn't change the rate, but i decrease the cash amount every mail add to cargo

**Comment by whateverusername0** [comment]
can you mail a PDA forkbomb that causes the PDA to explode?

**Comment by BombasterDS** [comment]
> can you mail a PDA forkbomb that causes the PDA to explode?

uuuhh, no?

**Comment by Piras314** [comment]
change the rate at which mail is sent down

**Comment by BombasterDS** [comment]
> change the rate at which mail is sent down

Increased interval from 5 mins to 7.5 mins

**Pull request merged**
