### PR TITLE
Adding Phobos station

### PR DESCRIPTION
**Pull request by Starbuckss14**
## About the PR

Small medium pop map with a asteroid theme. Probably not that good but its funny like train! 

Screenshot (26)
Screenshot (27)
Screenshot (43)
Screenshot (45)
Screenshot (47)
mapren

If you're unsure whether your PR will require media, ask a maintainer.

Check the box below to confirm that you have in fact seen this (put an X in the brackets, like [X]):
-->

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

### CODE REVIEW

**Comment by CatMagic1** [comment]
Address the comments from your upstream pr.

**Comment by Starbuckss14** [comment]
> Address the comments from your upstream pr.
Dog I did. This is for goob not wizden

**Comment by Aidenkrz** [comment]
> > Address the comments from your upstream pr.
> Dog I did. This is for goob not wizden
The screenshots show you havent changed anything, and as far as i can tell this doesn't include job spawns for NTR or Blueshield. It also merges with upstream, which is a no no.

**Comment by CatMagic1** [comment]
Nice map tho
Add the changes from the upstream comments, add job spawns for NTR and Blueshield & probably switch your repo so you don't merge upstream changes

**Pull request closed without merging**
