### PR TITLE
Skeletons are fragile now

### PR DESCRIPTION
**Pull request by Aineias1**
## About the PR

Nerfed skeletons, bones shouldnt be stronger than lots of meat

OLD STATS 
immune to everything except physical and heat damage
type: damageModifierSet
id: Skeleton
coefficients:
  Blunt: 1.1
  Slash: 0.8
  Piercing: 0.6
  Cold: 0.0
  Poison: 0.0
  Radiation: 0.0
  Asphyxiation: 0.0
  Bloodloss: 0.0
  Cellular: 0.0
flatReductions:
  Blunt: 5
## Why / Balance

Skeleton nukies are too OP, + skeleton antags are OP
## Technical details

changed code in Resources/Prototypes/Damage/modifier_sets.yml
## Media

image

## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

Skeletons are Nerfed
**Changelog**

## Summary by CodeRabbit

- **New Features**
	- Introduced multiple new damage modifier sets, enhancing gameplay interactions with various materials, including `StructuralMetallicStrong`, `Rock`, `Electronic`, and more.
- **Modifications**
	- Updated coefficients for the existing `Skeleton` damage modifier set, improving balance in damage types.
	- Specified flat reductions for several damage modifier sets, impacting damage mitigation strategies across various materials.
- **Copyright Updates**
	- Simplified copyright information for the tourniquet sprite and brown briefcase texture, removing previous credits.
	- Updated copyright for the wood door resource by removing the redesign credit.

### CODE REVIEW

**Comment by Piras314** [comment]
push this into the halloween branch

**Comment by Aineias1** [comment]
> push this into the halloween branch

i suppose skeletons should be weak not only on halloween
but yeah sure

**Comment by Aineias1** [comment]
missclick

**Review by Piras314 — CHANGES_REQUESTED** [review]
blunt 1.2 slash 1.1 might be better

**Comment by Aineias1** [comment]
@Piras314  Changed sprites back to normal and fixed checks
 (I STILL DONT KNOW HOW THEY GOT CHANGED, ONLY THING I HAVE COMMITED IS THE DAMAGE MODIFICATORS)

**Comment by Scruq445** [comment]
If they were skeletons, then they are hollow and you might shoot past them, so give them a small inmate dodge chance :trol:

**Comment by Aineias1** [comment]
k

**Pull request closed without merging**
