### PR TITLE
Revert shit

### PR DESCRIPTION
**Pull request by Aidenkrz**
## About the PR
Reverts #852, malders in chat
Reverts #611, adds to much stupid shit
Reverts #808, sprites are way to large

**Changelog**
:cl:
- remove: Removed skibidi toilet from station events, and other related items (sigma juice, skibidi antag item).
- tweak: Mothroaches are back, freaks.

## Release Notes

- **New Features**
  - Introduced new audio files and updated sound effects for revolutionary events.
  - Added multiple new meal recipes, including various burgers and desserts.
  - New entities such as `MobDionaNymph` and `SyndicateSponge` added to enhance gameplay.

- **Changes**
  - Renamed and updated descriptions for various entities, including "SyndiMaggot" to "SyndiRoach."
  - Removed outdated audio and entities related to "Skibidi Toilet" and "SigmaJuice."

- **Bug Fixes**
  - Adjusted interaction strings and movement parameters for improved gameplay experience.

- **Documentation**
  - Updated licensing information for audio files and textures.

### CODE REVIEW

**Comment by Piras314** [comment]
If you revert #930 heretics will be broken

**Comment by Aidenkrz** [comment]
> If you revert #930 heretics will be broken

:trollface:

**Comment by Aidenkrz** [comment]
yknow what actually, i dont fucking care, john station can merge upstream from now on and handle every bug fix

**Comment by whateverusername0** [comment]
keep #930

**Comment by whateverusername0** [comment]
or make heretic work with newstore noob :goberserk:

**Comment by whateverusername0** [comment]
ong newstore is overall worse than old one i tell you
it's not about the visuals it's about the shitcode :goberserk: 
they shitcoded discounts into listings

**Comment by whateverusername0** [comment]
you also deleted goob flavor text which i restored in #930 
\+ there's more than just that there
you're just gonna kill all and then expect me to fix that shit? nah :goberserk:

**Comment by whateverusername0** [comment]
image
finally

**Comment by JoeHammad1844** [comment]
I support reverting the first one but the other two are too far

**Comment by JoeHammad1844** [comment]
durk be like
instantly self merges pr
instantly closes revert prs for no given reason multiple times
reverts it himself
Dante

**Comment by Aidenkrz** [comment]
> durk be like instantly self merges pr instantly closes revert prs for no given reason multiple times reverts it himself

You are stupid and have a feeble mind.

**Comment by Aidenkrz** [comment]
@Piras314 is the ` Failed to load map /Maps/Shuttles/emergency_raven.yml` related to something you did in the skibidi pr?

**Comment by Piras314** [comment]
half/quarter the res of sportacus if you don't like it being so big
also skibidi rizz ohio update adds a lot of actually useful stuff, manually delete skibidi juice or whatever if you REALLY want, but don't revert it. Also there are no issues with 611, it just adds silly shit I don't know why
emergency_raven fail I think I might have mapped sigma juice on that

**Comment by Piras314** [comment]
there's a staaaaaarmaaaaaaan

**Pull request closed without merging**
