### PR TITLE
Steal the material silo, my beloved

### PR DESCRIPTION
**Pull request by jorgun**
## About the PR

Made the material Silo a steal target for thiefs

## Why / Balance

Material silo is so good. whud be a shame if anything happened to it
Structure steal are already a rare. so this will not come up ofte.

## Technical details

added the ensure so that it will not trigger on maps where it is not present. 

## Media

image

## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl:
- add: Thiefs have set there eyes on the Material Silo

### CODE REVIEW

**Comment by Aviu00** [comment]
I don't really like this. It will cause too much grief and silo isn't really that hard to steal on most stations.

**Comment by jorgun** [comment]
> I don't really like this. It will cause too much grief and silo isn't really that hard to steal on most stations.

i think it will be the other way around. 
i think this will be a difecult steal objective, becuse if it gets taken then all conected lathes will notice it. and starting a hunt for it.
ther eis alts that it is a steal structure target. it is not verry common as how often do somone get the steal captains toilet or fax. 
im not ageinst lowering the weigth to 0.5 becuse of the pain it will bring losing it.
but i do think this shud be stealtarget becuse of its value.

**Comment by Aviu00** [comment]
> i think it will be the other way around. i think this will be a difecult steal objective, becuse if it gets taken then all conected lathes will notice it. and starting a hunt for it. there is altso that it is a steal structure target. it is not verry common as how often do somone get the steal captains toilet or fax. im not ageinst lowering the weigth to 0.5 becuse of the pain it will be losing it. but i do think this shud be stealtarget becuse of its value.

You can just break into comms, disassemble silo and then reconstruct it somewhere behind the walls in maints. And nobody will ever find it.

**Comment by Piras314** [comment]
structure steal is really awful, I don't think we need more of them

**Pull request closed without merging**
