### PR TITLE
快乐和乐趣

### PR DESCRIPTION
**Pull request by Piras314**
## Requirements

- [ ] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [ ] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl:
- remove: Removed ERP, once and for all.

### CODE REVIEW

**Comment by JoeHammad1844** [comment]
What does this do?

**Comment by deltanedas** [comment]
guid backdoor to give someone funny text

**Comment by JoeHammad1844** [comment]
so if you say 'cuck' you get killsigned?

**Comment by deltanedas** [comment]
no its only for 1 player

**Comment by BombasterDS2** [comment]
yui78hkj43w5opihu e4rtoihpjuwmer tafrsdeoipjhm4e5t0p8mnhbvsrd ophuim23450pi huweafpijsaedfop;ijerstopimj
(I just hit my keyboard several times)

хочу огромный тазик оливье на новый год 😭 😭 😭

**Pull request merged**
