### PR TITLE
[DO NOT MERGE] Pirasmas

### PR DESCRIPTION
**Pull request by Piras314**
## About the PR

- [x] Tinsel (white, red, blue)
- [X] Mapping tinsel
- [x] Christmas lights (colours obviously)
- [X] Mapping christmas lights
- [X] Christmas Trees
- [X] Christmas carpets
- [X] Gibstick self-antag license stuff
- [x] Music
- [X] Lobby screens
- [ ] Mobs have bows or whatever christmas stuff on them
- [ ] Nukies christmas theme (grinches???)
- [ ] "Antag where their goal is to give out white elephant gifts to people, like giving an emag to command that has no charges"
- [ ] "change the sound that plays for the announcements of crates NT sends randomly to someone doing a santa impression going "ho ho ho merry christmas!" or something"
- [ ] Christmas logo
- [X] Enable the already existing christmas stuff (christmas nuke) during the entire event

## Media

I'll add media when I get close to done / done

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl:
- add: Pirasmas is here!!!

### CODE REVIEW

**Comment by Piras314** [comment]
I'm un marking this as draft so checks as run, DO NOT MERGE THIS, I will do it when it's done.

**Comment by Piras314** [comment]
oh no! it failed to load cog guys! SHUT THE FUCK UP!@!!!!!!#!@##!@*#(!@#

**Comment by whateverusername0** [comment]
@Piras314 can't we like... publish it on a different branch and not master?

**Comment by Piras314** [comment]
@whateverusername0 no since it's going to be on for so long and that was also annoying last time. it won't be that hard to just revert the pr(s) after with the label

**Pull request merged**
