### PR TITLE
Inconsistency v4

### PR DESCRIPTION
**Pull request by InfinityPandaRed**
## About the PR

resprited most lockers to fit rest of goob sprites. sprites are based off of tg station. Also respites some other stuff such as grinders pill canisters and fax machines
## Media

Incos v5

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

-resprited stuff

## Summary by CodeRabbit

- **Bug Fixes**
	- Updated copyright attribution for the `pills_canister.rsi` resource to reflect the correct source.

### CODE REVIEW

**Comment by JoeHammad1844** [comment]
Please no, I hate these sprites, ESPECIALLY the lockers

**Comment by JoeHammad1844** [comment]
Also the pill bottles sprites are going to clip because they're larger than the 1x1 space they take up

**Comment by Piras314** [comment]
testing these ingame rn

**Comment by Piras314** [comment]
@JoeHammad1844 works fine
image

**Comment by Piras314** [comment]
image

**Comment by JoeHammad1844** [comment]
> image
> 
> 

Everything here except the lockers are fine I think

**Comment by InfinityPandaRed** [comment]
> Please no, I hate these sprites, ESPECIALLY the lockers

why do you not like lockers

**Comment by JoeHammad1844** [comment]
> why do you not like lockers

they just look worse than the current ones. the current ones have bold outlines, and have more colour and don't look as flat
image

**Comment by InfinityPandaRed** [comment]
> > why do you not like lockers
> 
> they just look worse than the current ones. the current ones have bold outlines, and have more colour and don't look as flat image

image

**Comment by BombasterDS** [comment]
New lockers sprites looks cool

**Review by BombasterDS — APPROVED** [review]

**Pull request merged**
