### PR TITLE
modsuits (fake) (not moddable)

### PR DESCRIPTION
**Pull request by starch70**
## About the PR
hardsuits have built in features now (eg borg health hud, sechud, INSULS)

also two new hardsuits for T3 arsenal and T3 engi

## Why / Balance
make sci have a reason to do their fuckning job

## Media
(https://cdn.discordapp.com/attachments/1202734573247795303/1303855174275563571/2024-11-06_17-53-36.mp4?ex=672d4542&is=672bf3c2&hm=f14671d2cde84518337cca826c2fbb1b2d15eae5d2bd995167a7ff70db63a724&)
https://cdn.discordapp.com/attachments/1202734573247795303/1303854448979873843/2024-11-06_17-51-00.mp4?ex=672d4495&is=672bf315&hm=a80d634ec9baa9346d8e6a8a6dfb280efc422a78a38909f8e488439950cb53e7&

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**
:cl:
- add: Added researchable and printable hardsuits.
- add: Advanced combat and engineering hardsuit (T3 arsenal and T3 industrial).
- add: Hardsuits now have job specific features (medhud, sechud, insuls, eye protection, etc).
- tweak: Nukie agent hardsuit is now actually slightly better than normal blood-red.

## Summary by CodeRabbit

- **New Features**
	- Introduced new hardsuit helmets with enhanced features, including eye protection and advanced functionalities.
	- Added multiple new hardsuit recipes for crafting, expanding options for players.
	- New technologies related to hardsuits have been added, enhancing gameplay progression.

- **Bug Fixes**
	- Updated descriptions and attributes for various hardsuits and helmets to improve clarity and functionality.

- **Documentation**
	- New metadata files for advanced hardsuits added, detailing graphical representations and states.

### CODE REVIEW

**Comment by Piras314** [comment]
check the checks @starch70

**Comment by starch70** [comment]
> check the checks @starch70

the checks have been checked

**Comment by JoeHammad1844** [comment]
I feel like all my closed PRs on wizden are coming back

**Comment by whateverusername0** [comment]
i don't like hardsuits being printable
better take a real modsuit pr from some shithole fork and adapt it to goob man

**Comment by starch70** [comment]
> i don't like hardsuits being printable better take a real modsuit pr from some shithole fork and adapt it to goob man

uuhhhhhh wyci

**Comment by starch70** [comment]
> just make actual mod suits

why :dontdo:

**Comment by BombasterDS** [comment]
i'll continue to work on modsuits after i finish what i'm doing now

**Pull request closed without merging**
