### PR TITLE
removes salvage, a cargo tech can do the same job

### PR DESCRIPTION
**Pull request by GitHubUser53123**
## About the PR
fuck salvage fucking powergaming motherfuckerskdfm making shittles not interacting with the station

## Breaking changes
**Changelog**

- removed fun

## Summary by CodeRabbit

- **New Features**
	- Removal of the `SalvageSpecialist` job from multiple game maps, streamlining job availability for players.
	- Increased maximum availability for the `CargoTechnician` job on the "Reach" map.

- **Bug Fixes**
	- Adjusted job availability for `CargoTechnician` and `Passenger` roles in the "Fland Installation" high population map.

### CODE REVIEW

**Comment by GitHubUser53123** [comment]
what the fuck do you mean this PR has conflicts

**Comment by a-person5660** [comment]
harriet you forgot to give cargo access to salvage, and you should add salvage clothes to cargo loadouts.

**Comment by GitHubUser53123** [comment]
no, salvage must kil

**Comment by gluesniffler** [comment]
image

**Comment by HenhenIII** [comment]
This is such a bad PR that I can't even tell if it's satire or not.

Salv about to be rushed by every cargo tech round start, what does it change when random cargo techs don't interact with the station all shift and when salvage doesn't interact with the station.
Just an unnecessary removal of content. Like that one PR removing paramedic because med could do his job.

**Comment by whateverusername0** [comment]
⭐ 🎆

**Comment by JoeHammad1844** [comment]
>removes salvage
>doesn't increase cargo tech jobs to compensate
>doesn't give cargotechs salvage access
>barely elaborates
chad tider

**Pull request closed without merging**
