### PR TITLE
R U READY 4 ZE NEW TIDE ORDER

### PR DESCRIPTION
**Pull request by starch70**
## About the PR
tiders now have a hivemind radio
this can be used without a headset

## Why / Balance
image

## Media
image
image

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**
:cl: Yakub, Starch
- add: Tiders now have a intrinsic hivemind radio channel. Access it with ":i"

### CODE REVIEW

**Comment by a-person5660** [comment]
actually peak

**Review by Piras314 — APPROVED** [review]
I AM READY 4 ZE NEW TIDE ORDER

**Comment by Verbalase** [comment]
I like fun, but this is actually stupid imo!!!

**Comment by Piras314** [comment]
kira what happened to you this is literally the absolute peak of PRs

**Comment by Agustron24** [comment]
All tiders share a single braincell

**Comment by kurokoTurbo** [comment]
this is hell. if players on goob become a little more robust this pr will destroy sec/shitter balance if it didnt destroy it already

**Comment by kurokoTurbo** [comment]
its like no one experienced metagangs here

**Pull request merged**
