### PR TITLE
Ported Onis from DeltaV

### PR DESCRIPTION
**Pull request by ScyronX**
## About the PR

Ported Oni species from DeltaV
## Why / Balance

Oni species have higher health and melee damage, but they shoot very inaccurately basically they cant shoot.
## Technical details

only previously existing code changed was gun component and tool component to give oni system writing acces to modify stats

**Changelog**

:cl:
- add: Added oni species.

### CODE REVIEW

**Comment by Plyushsune** [comment]
Mhm oni woman

**Comment by JoeHammad1844** [comment]
Yowie exists and we have so many species already

**Comment by Plyushsune** [comment]
> Yowie exists and we have so many species already

Shut up

**Comment by Aidenkrz** [comment]
> Yowie exists and we have so many species already

ok and

**Review by gluesniffler — APPROVED** [review]

**Comment by Piras314** [comment]
Your changelog won't work, you need the :cl: emoji above it, e.g.

```
:cl:
- add: Added fun
```

**Comment by ScyronX** [comment]
Moved the file to DeltaV

**Pull request merged**
