### PR TITLE
Shitmed Update 2 - bottom text

### PR DESCRIPTION
**Pull request by gluesniffler**
resentment technical debt

## About the PR
image

Honey wake up, another shitmed PR with 5 features and a trillion bugs! I love bloat. Port of https://github.com/Simple-Station/Einstein-Engines/pull/1271

## Requirements
- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.
- [X] I have bombed an orphanage and will bomb another if I have to fill out this shit again.

**Changelog**
:cl: Mocho
- add: Added different step durations to each surgery step.
- add: Added a T2 research for advanced surgical tools
- add: Added a T3 research for an omnitool for surgery.
- add: Added Surgical and Advanced Surgical modules for Mediborgs
- add: Mediborgs can now perform surgery!
- add: Added lobotomies as an operation. Godspeed you psychopaths.
- add: Added cybernetic arms, legs and eyes.
- add: Added EMP weaknesses to all cybernetic parts (the day of reckoning will come for IPCs soon)
- add: Losing your eyes now blinds you.
- fix: Fixed a few species that did not inherit from BasePart's, thus taking damage types they shouldn't on their limbs.
- fix: Fixed harpy lungs not being usable in surgeries. 
- fix: Fixed fire being able to destroy your chest.
- fix: Fixed entities being able to take over your body by just inserting a brain or another head on top of you.
- fix: Fixed some shitcode that didnt let rejuvenate or godmode work properly.
- fix: Fixed bionic arm, and cybernetic eyes traits not working properly due to shitty networking.
- fix: Fixed cybernetic limbs being a free hand/feet generator due to shitcode.
- tweak: Increased tend wounds's speed by double, and bumped up the values on its calculations. DEATH TO TOPICALS, LEAVE THOSE TO TIDERS.
- tweak: Beheading an entity now doesnt let it move, speak, and forces it to the ground immediately (literally 1984!!11!!)
- tweak: Changed sprites on most surgical tools to now use /tg/ sprites.

## Summary by CodeRabbit

- **New Features**
	- Introduced targeting functions for left and right hands and feet, enhancing gameplay interactions.
	- Added new surgery options, including lobotomy and brain tissue repair procedures.
	- Implemented new cybernetic components and enhancements, expanding character customization.
	- New recipes for advanced medical tools and cybernetic enhancements added to crafting systems.
	- Enhanced body part management with new event subscriptions and refined logic for damage handling.

- **Bug Fixes**
	- Improved error handling and validation for surgery conditions and body part interactions.

- **Documentation**
	- Updated documentation for new features and components, including surgery steps and targeting mechanics.

### CODE REVIEW

**Comment by gluesniffler** [comment]
heisentests it seems

**Comment by Piras314** [comment]
Industrial felinid lobotomies

image

**Review by Piras314 — APPROVED** [review]

**Comment by JoeHammad1844** [comment]
are changeling heads vestigial yet?

**Comment by ARMOKS** [comment]
@gluesniffler you can no longer strip peoples shoes or gloves, cyber legs don't let you wear shoes, and cyber arms don't let you wear gloves.

**Comment by deltanedas** [comment]
rimworld parity, shoe and glove mods stop letting you wear gloves or shoes when you install 2 bionic legs/arms

**Pull request merged**
