### PR TITLE
refactor bluespace crystals, fix scram implant

### PR DESCRIPTION
**Pull request by Ilya246**
## About the PR
reverts the changes #569 makes to the scram implant and actually fixes it by porting https://github.com/space-wizards/space-station-14/pull/31482

nukes the bluespace crystal system and component and makes them more generic, also makes the bluespace implant use that

## Why / Balance
see wiz PR

## Technical details
see wiz PR; TLDR the solution which this reverts is straight up worse than what was before it, aka what i am reverting *to*, from testing this gives you much better teleports (less often into space, whereas the current solution will teleport you into space every time) and runs 20 to 50 times faster (and the current solution can take milliseconds to run at the full intended radius)

makes a new RandomTeleportComponent to store the teleportation data to deduplicate it, makes bluespace crystals and scram implants use it

## Media
tested, works

## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [ ] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes
ScramImplantComponent is no more, BluespaceCrystal-anything is gone as well

**Changelog**

:cl:
- fix: Scram implant will now properly randomly teleport you over long distances, and less often into space.

## Summary by CodeRabbit

- **New Features**
	- Introduced a new property for teleportation attempts, allowing up to 20 attempts to find a valid teleportation tile.
	- Added new components for random teleportation, including `RandomTeleportComponent` and `RandomTeleportOnUseComponent`, enhancing user interaction.
	- Added teleportation behavior to the MaterialBSCrystal entity.

- **Improvements**
	- Reduced the teleportation radius from 500 to 100, enhancing gameplay balance.
	- Streamlined teleportation logic for more reliable positioning and interaction handling during teleportation events.
	- Removed outdated teleportation components, simplifying the system.
	- Updated action delay for the scram implant, increasing from 30 to 300 for improved gameplay mechanics.

### CODE REVIEW

**Comment by Ilya246** [comment]
ok not done with this yet i can just nuke BluespaceCrystal-anything and be fine apparently, making this into also a refactor

**Comment by whateverusername0** [comment]
but the infinite scram :goberserk:

**Comment by Ilya246** [comment]
> but the infinite scram :goberserk:

yes.
can be made not infinite again if we want to, but i think it's okay; however yeah we could consider increasing its cooldown if we keep it as infinite

**Comment by Ilya246** [comment]
anyway this is ready, i tested it and it works as intended for both bluespace crystals and scram implant
the scram implant is no longer a scam implant

**Comment by whateverusername0** [comment]
> yes. can be made not infinite again if we want to, but i think it's okay; however yeah we could consider increasing its cooldown if we keep it as infinite

oh, so it's still infinite, great

**Comment by BombasterDS** [comment]
@Ilya246 Can you please remove ability to use it when cuffed if it's still infinite?

**Comment by Ilya246** [comment]
> @Ilya246 Can you please remove ability to use it when cuffed if it's still infinite?

would maybe be a better idea to just make it take like 5 minutes to recharge

**Comment by Piras314** [comment]
make the 5 minute recharge @Ilya246

**Comment by Ilya246** [comment]
> make the 5 minute recharge @Ilya246

done, now 300s recharge

**Review by Piras314 — APPROVED** [review]

**Comment by whateverusername0** [comment]
> > make the 5 minute recharge @Ilya246
> 
> 
> 
> done, now 300s recharge

:goberserk: make it 60

**Comment by whateverusername0** [comment]
@Piras314 5 minute cooldown is crazy. 60-90 seconds is more acceptable than the 30 seconds we have now, but not **5 minutes** :goberserk:

**Comment by Ilya246** [comment]
> @Piras314 5 minute cooldown is crazy. 60-90 seconds is more acceptable than the 30 seconds we have now, but not **5 minutes** :goberserk:

it's a teleport to anywhere on the grid, you will be literally uncatchable if you have an EVA

**Comment by BombasterDS** [comment]
> @Piras314 5 minute cooldown is crazy. 60-90 seconds is more acceptable than the 30 seconds we have now, but not **5 minutes** :goberserk: 

Implant removing only takes 60 seconds. So there is two options: 60 seconds CD, but you won't be able to use it when cuffed or 300 seconds cd

**Pull request merged**
