### PR TITLE
added toggelabel nigthvision to changeling

### PR DESCRIPTION
**Pull request by jorgun**
## About the PR

gives changeling super darkvision

## Technical details

dossent add any new abilities, just improves on Aubmentet vision
## Media

Before: 
image
After: 
image

## Requirements

- [X] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

### CODE REVIEW

**Comment by BombasterDS** [comment]
I don't think it's necessary right now, better wait good looking night vision than just disabling light for them. 

And you can see through walls that is very op. Changelings not weak antag after all.

**Comment by yglop** [comment]
> I don't think it's necessary right now, better wait good looking night vision than just disabling light for them.
> 
> And you can see through walls that is very op. Changelings not weak antag after all.

image

**Comment by BombasterDS** [comment]
> > I don't think it's necessary right now, better wait good looking night vision than just disabling light for them.
> > And you can see through walls that is very op. Changelings not weak antag after all.
> 
> image

Xray vision not works like that. In ss13 you can make meson goggles and see station behind one wall (but no creatures and objects) or make xray goggles to see thermal object behind wall, if i remember it right.

Plus night vision there is not fullbright. And they not become weaker to flashes.

**Comment by a-person5660** [comment]
it would be better imo if the night vision worked like RMC14s xenos night vision where it disables light and only lets you see living things through walls.

**Comment by whateverusername0** [comment]
@jorgun what if you copied thermals from RMC

**Comment by jorgun** [comment]
image
image
no more fov hacking

**Comment by jorgun** [comment]
image
i dont know how i made this work
but its RCM vision

**Comment by jorgun** [comment]
image
can even see a Ninja

**Comment by Aidenkrz** [comment]
No offense, but this is a terrible way to implement this. We do not need to hardcode more stuff into changeling when this could easily be a separate component and system.

**Review by Aidenkrz — CHANGES_REQUESTED** [review]
No offense, but this is a terrible way to implement this. We do not need to hardcode more stuff into changeling when this could easily be a separate component and system, not to mention the fact it looks terrible. They should not have lights completely disabled, and this doesnt incorporate the part where they're supposed to be weaker to flashes.

**Comment by jorgun** [comment]
your right, this shud be its own thing.

**Comment by whateverusername0** [comment]
> your right, this shud be its own thing.

@jorgun next PR add actual mesons to mesons :trollface:

**Pull request closed without merging**
