### PR TITLE
Removing the Removal of the Throngler

### PR DESCRIPTION
**Pull request by a-person5660**
removing the removal of the throngler, cargo mains rejoyce!

## About the PR
- Removed the removal of the throngler from the grand lottery

## Why / Balance
- The throngler should have never been removed in the first place, its a fun item and belongs on goob station.

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
:cl:
- tweak: Added the Throngler back to the grand lottery

### CODE REVIEW

**Comment by a-person5660** [comment]
hopefully this works lol

**Comment by CatMagic1** [comment]
i approve this mesage

**Comment by Aidenkrz** [comment]
No

**Comment by BeeRobynn** [comment]
image
the people have spoken, this should be reopened

**Comment by CatMagic1** [comment]
You have to give us at least a paragraph of argument durky (we will ignore it).

**Pull request closed without merging**
