### PR TITLE
my awesome fucking evil mald pr

### PR DESCRIPTION
**Pull request by starch70**
## About the PR
slimes/tarantulas/clown spiders are less strong and no longer ghostroles
HoP, captain, NTrep, BSO, and HoS now all need basic department playtime (i am too tired of these mfs not knowing shit!! you do not tell me how i manage the SM just because you have engi access!!!) (also cargo and sci requirements just werent in HoP and cap before)

## Why / Balance
mfw the randomly spawning ghostroles do cellular or have 180 HP + webs that slip you
> spawn at cryo
> roll syndie
> killed by random tarantula and left in morgue for rest of life

also the command roles are Fucking Stupid most of the time so maybe the ROLES WITH AA SHOULD KNOW HOW TO PLAY EVERY DEPARTMENT AT A MINIMUM

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**
:cl:
- remove: tarantulas clown spiders and slimes are no longer ghostroles fuck you
- tweak: i also nerfed them a lot fuck you
- tweak: hop cap hos ntr and bso now need at minimum 2 hrs of playtime in all departments learn to do a different job instead of Batong loser

## Release Notes

- **New Features**
	- Expanded job requirements for the Captain, Head of Personnel, Head of Security, Blueshield Officer, and Nanotrasen Representative roles to include additional departmental time commitments.
	- Added time requirements for the Cargo and Science departments for various roles, enhancing the complexity and engagement of these positions.

These updates aim to enrich the gameplay experience by encouraging broader departmental involvement for key roles.

### CODE REVIEW

**Comment by Ilya246** [comment]
spiders and stuff are fun ghost roles just make them less common and maybe remove cellular slimes

**Comment by JoeHammad1844** [comment]
awesome PR
having to make a reinforced spear beforehand to even have a chance against spiders is kinda fucked

**Comment by Ilya246** [comment]
ghosts already have little to do so i'm not sure about this, what if we made it try to spawn spiders away from people?

**Comment by BombasterDS** [comment]
Also, what you mean by changing fauna ghost roles if you only touch cap/hos/hop/bso/ntr roles in this PR??? Anyway, removing ghost roles from fauna because you died once from them is bad idea.

**Comment by Ilya246** [comment]
#931 real

**Comment by JoeHammad1844** [comment]
Tbh making them a ghost role is actually a nerf because of how robust the AI is

**Comment by starch70** [comment]
i will not be taking criticism my opinion is always correct

**Pull request closed without merging**
