### PR TITLE
add back the throngler to grand lottery.

### PR DESCRIPTION
**Pull request by lanse12**
## About the PR
added back the throngler to grand lottery with a chance of 0.0001% (same as pulse carbine)
also increases the chance of mosin, ak and chimp gun because they're ass items anyways

## Why / Balance
there was a poll to add it back a few months ago
doomsday is coming

**Changelog**

:cl:
- add: Throngler is back in the grand lottery. God save us.

### CODE REVIEW

**Comment by BeeRobynn** [comment]
Screenshot_20241207-161628

**Review by gluesniffler — APPROVED** [review]
peak

**Comment by JustSome1Nearby** [comment]
Last time i was QM we had 400k  cash wich is 40 grand lotos, 0,04 percent chance... God save us

**Comment by Piras314** [comment]
ngl there needs to be some kind of mechanical reinforcement of if or if not you're allowed to antag if you get a throngler

**Comment by JustSome1Nearby** [comment]
ngl if i get the Throngler as a QM, the urge to create cargonia will be too strong... I might not be able to hold it

**Comment by deltanedas** [comment]
throngler and bang sticks should make ypu a murderbone antag, showing killsigns for everyone and everyone sees killsign for you

**Comment by JustSome1Nearby** [comment]
Do you suggest rules of "aquired" antag privileges? Like becoming Morph in ss13 after injecting THAT ONE syringe from Lavaland dungeon floor?

**Comment by JustSome1Nearby** [comment]
It actually would be a funny idea to give out more antags based not just on luck, but things you DO in a round... Like after touching things of TOO HIGH VALUE, you become obsessed with money, rolling a midround Thief. 
Or you can roll ling AFTER DYING, so that your character is like "Oh, yeah, i am immortal" and jumps back up

**Comment by Aidenkrz** [comment]
no

**Pull request closed without merging**
