### PR TITLE
Standard Operating Procedure REAL?!

### PR DESCRIPTION
**Pull request by CerberusWolfie**
## About the PR

This adds the entirety of the SOP that Goob LRP and Goob MRP can use.

## Why / Balance

Staff wanted an SOP. Rouge2t7, Tikibomb, and I worked on the SOP and then I sorted, added the files, and compiled everything for a PR.

## Technical details

This adds more FTL entries to the guides underneath Goobstation directory in Resources. This also adds like 300+ lines of YML for making the guide entries for the FTL.

## Media

image
image
image

## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

This does not present any breaking changes, but if something crashes a client, there could potentially be a bad link (I tested them all).

**Changelog**

:cl: CerberusWolfie, Rouge2t7, and Tikibomb
- add: Standard Operating Procedure is here!

### CODE REVIEW

**Comment by whateverusername0** [comment]
goob MRP arc
don't make violating sop a bannable offense though.

**Comment by Aineias1** [comment]
Yeah uh, just make it mostly ic issues for non command and for command, if they constantly ignore sop, just ban them from command

**Comment by CerberusWolfie** [comment]
SOP on LRP is required for Command and Security since it's pseudo rules.

Everything else is mostly a guide and something you "can" follow.

**Comment by CerberusWolfie** [comment]
No, it wouldn't be bannable unless it violated server rules.

**Comment by JoeHammad1844** [comment]
make sure the sec shaker is SOP
image

**Comment by CerberusWolfie** [comment]
> > goob MRP arc don't make violating sop a bannable offense though.
> 
> It's a guideline more than a ruleset. Though some will likely be enforced harder than others.

This exactly. It's intended to be a guideline for everyone but a (semi) ruleset for Command/Security in LRP.

**Review by Piras314 — APPROVED** [review]
Didn't read a single line

**Comment by CerberusWolfie** [comment]
> Didn't read a single line

Mood

**Comment by yglop** [comment]
mrp bs :-1:

**Comment by Sarahon** [comment]
> mrp bs 👎

Thank you for that very insightful and constructive comment.

**Pull request merged**
