### PR TITLE
Set Outfit as an admin works again!!!!!!

### PR DESCRIPTION
**Pull request by Verbalase**
## About the PR

Fixed setting outfits for characters not working.

## Technical details

This was all taken from another PR, so I'm just going to use what they said. (https://github.com/space-wizards/space-station-14/pull/29672) It has not been merged yet it seems, but I'm PR'ing it here for review still.

- The list of outfits filters out any StartingGearPrototypes that are referenced by a LoadoutPrototype.

- When applying the outfit, if it is referenced as a JobPrototype's StartingGear, that job's RoleLoadout is now looked up and applied to the character if possible. If the target character is controlled by a player, their loadout for that job will be used if they have one. If the command is targeting an Urist instead, the default (species-appropriate) loadout for that job will be used.

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

https://github.com/user-attachments/assets/dc9c4eef-7526-4302-9a6d-7fa456c8bc75

## Breaking changes

None to my knowledge.

### CODE REVIEW

**Comment by Aidenkrz** [comment]
You need to link the original PR here, and you managed to fuck up the changelog again

**Comment by Verbalase** [comment]
> You need to link the original PR here, and you managed to fuck up the changelog again

Shall do, hold on.

**Comment by Verbalase** [comment]
> You need to link the original PR here, and you managed to fuck up the changelog again

Done, but one failing check chat...

**Comment by Verbalase** [comment]
I forgot to fix the changelog, hold on.

**Comment by Aidenkrz** [comment]
Removing CL actually because this is probably going to be added to wizden in a week anyway, we don't need it inside gooblog

**Comment by Verbalase** [comment]
cc8

**Pull request merged**
