### PR TITLE
Partly revert sprites update

### PR DESCRIPTION
**Pull request by BombasterDS**
Partly revert: #570 

## About the PR
Reverted:
Captain Hardsuit Helmet (not hardsuit) - previous one just looks much better and it good combines with new one
Clown Hardsuit and Helmet - new looks like syndie one and not like clown's one.
Head of Security Mantle - previous one looks better and more unique
Labcoats Icons - previous look better
Reptilian sprite and all reptilian related sprites - new lizard sprite look worse
APC and Substation - previous look better

## Summary by CodeRabbit

- **New Features**
	- Updated copyright statements for various clothing assets to clarify attribution and contributions.
	- Removed the "equipped-OUTERCLOTHING-reptilian" variant from multiple clothing items, streamlining options available to users.
- **Bug Fixes**
	- Corrected inconsistencies in naming conventions for certain clothing states to improve clarity.
- **Documentation**
	- Enhanced metadata documentation for clothing assets to reflect accurate authorship and modifications.

### CODE REVIEW

**Review by whateverusername0 — APPROVED** [review]
works

**Comment by Piras314** [comment]
idk about this

**Comment by BombasterDS** [comment]
> idk about this

Most reptilian players didn't like new sprites.
Captain helmet looks awful (really look at it)
Clown hardsuit not funny at all. Previous one looks much better.

APC, Substation and labcoats are negotiable (but imo previous one looked more unique and better)

**Comment by TooSillyFennec** [comment]
> > idk about this
> 
> Most reptilian players didn't like new sprites. Captain helmet looks awful (really look at it) Clown hardsuit not funny at all. Previous one looks much better.
> 
> APC, Substation and labcoats are negotiable (but imo previous one looked more unique and better)

Lizard sprites aren't just bad, they are literally broken. Colours and legs are pretty fucked- pretty sure the left direction leg sprites weren't even changed even. even if they weren't, 14 lizard sprites are already pretty good and a new sprite set would need to be similar honestly.

**Pull request merged**
