### PR TITLE
buff maxim hardsuit

### PR DESCRIPTION
**Pull request by lanse12**
## About the PR
makes maxim hardsuit 15% slowdown instead of 25%

## Why / Balance
it's rare as fuck so it's only correct that it is good

### CODE REVIEW

**Comment by Aviu00** [comment]
Isn't it supposed to be salvage jugg suit.

**Comment by lanse12** [comment]
> Isn't it supposed to be salvage jugg suit.

anti golaith cool suit

**Comment by TurboTrackerss14** [comment]
Comment from inquisitor-star in the #1107 
>I am the one who requested this bounty so I will be giving some additional information.

>As it stands the suits look to be overpowered but I will list several reasons as to why they aren't:

>First up is the argument its stronger than a bloodred/nukie hardsuit. While stat wise it has 20% more pierce resistance it also is 15% slower than a bloodred, bloodreds only have 10% slowdown whereas the maxim hardsuit has 25%, this suit statwise isn't close to a jugsuit.

>Secondly is where it spawns, it spawns on arguably the hardest place in the entire game surrounded by both goliaths and hivelords alike, getting to the suits would be a challenge.

>Thirdly it doesn't have a static spawn location furthermore it isn't guaranteed to spawn either, salvagers could mine the entire vgroid and not find one suit or they can but if the argument of salvagers aren't getting resources are the issue, this encourages salvage to mine a proportionately large size of the vgroid meaning salvage gets a reward for hard work, if they want good things they have to mine more meaning the station will always have materials.

This suit was given this slowdown as a rebalance around its introduction to the loot pool and in relation to some other stat changes. 
To give it an immediate buff before it's even been used enough to get some comparable use to other hardsuits feels very rushed and just begging for powercreep on top of what felt very powercreep to some of us already. 
But salv has to have their gamerloot I guess? 

Atleast do something with its resistances before unironically powercreeping it to what the original bounty creator argued it wasn't going to be.

**Comment by lanse12** [comment]
> Comment from inquisitor-star in the #1107
> 
> > I am the one who requested this bounty so I will be giving some additional information.
> 
> > As it stands the suits look to be overpowered but I will list several reasons as to why they aren't:
> 
> > First up is the argument its stronger than a bloodred/nukie hardsuit. While stat wise it has 20% more pierce resistance it also is 15% slower than a bloodred, bloodreds only have 10% slowdown whereas the maxim hardsuit has 25%, this suit statwise isn't close to a jugsuit.
> 
> > Secondly is where it spawns, it spawns on arguably the hardest place in the entire game surrounded by both goliaths and hivelords alike, getting to the suits would be a challenge.
> 
> > Thirdly it doesn't have a static spawn location furthermore it isn't guaranteed to spawn either, salvagers could mine the entire vgroid and not find one suit or they can but if the argument of salvagers aren't getting resources are the issue, this encourages salvage to mine a proportionately large size of the vgroid meaning salvage gets a reward for hard work, if they want good things they have to mine more meaning the station will always have materials.
> 
> This suit was given this slowdown as a rebalance around its introduction to the loot pool and in relation to some other stat changes. To give it an immediate buff before it's even been used enough to get some comparable use to other hardsuits feels very rushed and just begging for powercreep on top of what felt very powercreep to some of us already. But salv has to have their gamerloot I guess?
> 
> Atleast do something with its resistances before unironically powercreeping it to what the original bounty creator argued it wasn't going to be.

one of the rarest as if not the rarest item in game

**Pull request closed without merging**
