### PR TITLE
train station anchor

### PR DESCRIPTION
**Pull request by starch70**
## About the PR
add station anchor to train

## Why / Balance
I forgor

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**
:cl:
- fix: station anchor to train

## Summary by CodeRabbit

- **New Features**
	- Introduced a new map, **Train**, to the game map pool.
	- Added a new job, **StationAi**, to the **Train** map.
  
- **Improvements**
	- Adjusted player limits for the **Train** map: minimum players changed to 30 and maximum players to 60.
	- Updated job classification for available jobs on the **Train** map.
  
- **Bug Fixes**
	- Added a comment indicating that the **Cog** map is broken and should not be included in the pool.

### CODE REVIEW

**Comment by SkippyMcSkips** [comment]
Isn’t train supposed to be moving?

**Comment by SkippyMcSkips** [comment]
Wasn't talking about the parallax 👍

**Comment by starch70** [comment]
> Wasn't talking about the parallax 👍 Couple times I've been on train the station was moving but maybe that was admeme event or crew installing pilot computer

yeah that was an admeme train doesnt have a shuttle console normally

**Review by Piras314 — APPROVED** [review]

**Comment by Piras314** [comment]
merge conflict @starch70

**Comment by starch70** [comment]
> merge conflict @starch70

i dont have permission to fix the merge conflicts and its the map yaml anyways

**Pull request closed without merging**
