### PR TITLE
Duke Nukies & Stamcrit resistance

### PR DESCRIPTION
**Pull request by whateverusername0**
## About the PR
i changed the branch's name, so uhh it's literally #466 

the rest is a copy of #466
---
CL :trollface:
also added stamina damage resistance which can be enabled by simply adding a StaminaDamageResistance component with the coefficient to an entity. very cool
now all hardsuits have 25% stamdmg resistance, bloodred has 50%, elite - 75%, jugger - 65%
might add more stamdmg res to death squad or chrono gamer gear

## Why / Balance

i always wanted to balance nukies and i think i did a good job at it
GOD I LOVE TEH DUKE NUKEI

## Media
hardsuit stamcrit resistance check
image

roundstart nukie changes
image

cool new sprites
image

reinforcement changes
image

:cl:
- add: Now all hardsuits have different stamina damage resistance.
- add: Nuclear operatives now spawn without hardsuits but with 50 more TC.
- add: Nuclear operative reinforcements now spawn with a bonus uplink with 50 TC.
- tweak: Changed nuclear operative hardsuit sprites.
- tweak: Decreased raid suit price to 30 TC
- tweak: Increased syndicate elite suit price to 70 TC
- tweak: Increased juggernaut suit price to 100 TC
- tweak: Increased the chinalake price to 150 TC
- tweak: Decreased nukie reinforcement agent price to 125 TC

### CODE REVIEW

**Comment by Verbalase** [comment]
next objective

defend the PR with your life

**Comment by a-person5660** [comment]
new objective: survive

imo civ hardsuits (engi, salv, etc) shouldnt have stamina resistance.

**Comment by Piras314** [comment]
base hardsuits should not have stun resistance, only syndicate armour should have it, and not just syndicate hardsuits

**Comment by whateverusername0** [comment]
> imo civ hardsuits (engi, salv, etc) shouldnt have stamina resistance.

> base hardsuits should not have stun resistance, only syndicate armour should have it

you can consider stun resistance as shock resistance
since stun weapons electrify you to get you down

engineering hardsuits must have at lease some stun resistance because it just makes sense.
security - in case a tider wants to shit on them with his bolastunprod, which will not really work because it'll take like 4-5 hits instead of the usual 3 to get him down.
also, death squad not having stun resistance? come on man :trollface:

making stun resistance syndicate only is a mega traitor buff
so, instead of nerfing nukies in favor of _balance_:tm: (:trollface:), we buff the crew by making some of their hardsuits stun resistant too :+1:

**Comment by Aidenkrz** [comment]
put the sprites into a different pr and ill merge it

**Pull request closed without merging**
