### PR TITLE
syndie suit resprites

### PR DESCRIPTION
**Pull request by whateverusername0**
## About the PR

image
also #471 :trollface: 

:cl:
- add: The Syndicate has updated their drip to match the new fashion standart

### CODE REVIEW

**Comment by Verbalase** [comment]
i can kinda see the naked dudes, idk man

**Comment by whateverusername0** [comment]
> i can kinda see the naked dudes, idk man

you won't see them in game don't worry about it

**Comment by JoeHammad1844** [comment]
im not a fan of the nu-TG sprites, the current ones are too iconic and we dont even have modsuits

**Comment by whateverusername0** [comment]
> im not a fan of the nu-TG sprites, the current ones are too iconic and we dont even have modsuits

it's for future™️

**Comment by Aidenkrz** [comment]
> i can kinda see the naked dudes, idk man
Its because theyre zoomed in

**Review by Aidenkrz — CHANGES_REQUESTED** [review]
Not a single meta file updated ????

**Comment by JoeHammad1844** [comment]
dude you forgot commander and medic sprites

**Comment by whateverusername0** [comment]
> dude you forgot commander and medic sprites

blehh

**Comment by Aidenkrz** [comment]
Did you actually make these sprites?

**Comment by whateverusername0** [comment]
> Did you actually make these sprites?

@Aidenkrz i edited TG sprites

**Pull request merged**
