### PR TITLE
nukler planet tweaks

### PR DESCRIPTION
**Pull request by whateverusername0**
## About the PR

replaced angry slime with smile and added hotplate

:cl:
- tweak: nukie planet tweaks

## Summary by CodeRabbit

- **New Features**
	- Introduced new physics properties for enhanced entity interactions.
	- Added collision detection capabilities for specific entities.
	- Updated entity types and prototypes, improving gameplay dynamics.

- **Bug Fixes**
	- Adjusted the positioning of various entities for better spatial configuration.

### CODE REVIEW

**Comment by misandrie** [comment]
outpost and shuttle are still not named, jannies cant tp to the grids for shit

**Comment by whateverusername0** [comment]
> outpost and shuttle are still not named, jannies cant tp to the grids for shit

what

**Comment by misandrie** [comment]
> > outpost and shuttle are still not named, jannies cant tp to the grids for shit
> 
> what

The grids for both the outpost and the shuttle do not have names.
The shuttle shows up on IFF unnamed.

**Comment by whateverusername0** [comment]
> The grids for both the outpost and the shuttle do not have names. The shuttle shows up on IFF unnamed.

shuttle showing up as unnamed is fine
what about nukie planet?

**Comment by whateverusername0** [comment]
unrelated salvage rework test fail

**Comment by misandrie** [comment]
> shuttle showing up as unnamed is fine 

How is it fine if muh RP immersion is voided because there's a unnamed large shuttle.
IFF can be toggled on for identification. And its identifying fuckall if there's no name.

> what about nukie planet?

How do you tp to nukie planet if all ops have left the map

**Comment by whateverusername0** [comment]
> How do you tp to nukie planet if all ops have left the map

uhh good question. idk how wizden people made it

**Comment by Piras314** [comment]
@whateverusername0 you can TP to grids & maps in the (I believe) last tab of the admin panel, if you load up the shuttle and the planet and find them on that panel, you should be able to right click, view variables and set a name for them, then save them

**Comment by Aidenkrz** [comment]
Just put a beacon on the planet

**Comment by Piras314** [comment]
that's a good idea on top of it or if you can't figure it out

**Comment by whateverusername0** [comment]
ok
someone else added the hotplate and did some tweaks to the nukie planet
i feel :godmode:

**Pull request closed without merging**
