### PR TITLE
BSO Clothing Update.

### PR DESCRIPTION
**Pull request by Icepicked**
## About the PR

New clothes ported from Paradise Station.

taken from Paradise Station at commit https://github.com/ParadiseSS13/Paradise/pull/26498/commits/17c167b6648e8b67eb9c2f23f2f5b61e1a86f028

BSO was so unbelievably boring when it came to their clothing, decided to give them a refresh.

## Why / Balance

BSO gets thier own unique armour, its just a worse version of the Carapace. 
## Media

image
image

## Requirements

- [ ] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [ ] I have added media to this PR or it does not require an ingame showcase.

**Changelog**

:cl: 
- add: Added new attire for BSO

## Summary by CodeRabbit

- **New Features**
	- Introduced new clothing options including two officer berets, a Blueshield Armour Vest, a jumpskirt, and a jumpsuit for Blueshield officers.
	- Added a pair of medical sunglasses with a heads-up display, enhancing gameplay mechanics related to identity.

- **Bug Fixes**
	- Updated equipment configuration for the Blueshield Officer role to ensure accurate gear representation.

- **Documentation**
	- Added metadata files for new textures to support proper visual representation in various game states.

### CODE REVIEW

**Review by Piras314 — CHANGES_REQUESTED** [review]
- remove the word "Clothing" from the changelog

**Comment by Piras314** [comment]
accidentally said to localise the strings, don't

**Review by whateverusername0 — APPROVED** [review]

**Review by Piras314 — APPROVED** [review]
you can use the word clothing I just meant to keep the CL as it was before and remove the specific instance of it lol

**Comment by Icepicked** [comment]
didnt mean to do that :godo:

probably fine

**Comment by JoeHammad1844** [comment]
BSO needs jackboots by the way

**Comment by BombasterDS** [comment]
> ## About the PR
> New clothes ported from Paradise Station.
> 
> taken from Paradise Station at commit [ParadiseSS13/Paradise@17c167b](https://github.com/ParadiseSS13/Paradise/commit/17c167b6648e8b67eb9c2f23f2f5b61e1a86f028)
> 
> BSO was so unbelievably boring when it came to their clothing, decided to give them a refresh.
> 
> ## Why / Balance
> BSO gets thier own unique armour, its just a worse version of the Carapace.
> 
> ## Media
> image image
> 
> ## Requirements
> * [ ]  I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
> * [ ]  I have added media to this PR or it does not require an ingame showcase.
> 
> **Changelog**
> 
> 🆑
> 
> * add: Added new attire for BSO
> 
> ## Summary by CodeRabbit
> ## Summary by CodeRabbit
> * **New Features**
>   
>   * Introduced new clothing options including two officer berets, a Blueshield Armour Vest, a jumpskirt, and a jumpsuit for Blueshield officers.
>   * Enhanced character customization with specific uniforms and protective gear.
> * **Bug Fixes**
>   
>   * Updated equipment configuration for the Blueshield Officer role to ensure accurate gear representation.
> * **Documentation**
>   
>   * Added metadata files for new textures to support proper visual representation in various game states.

What about glasses? Looks like you have admin glasses on screenshot, but you have security glasses in prototype

**Comment by Icepicked** [comment]
Pretty sure its just a medhud in glasses form. ill add it :godo:

**Comment by JoeHammad1844** [comment]
I think BSO's are supposed to be allowed to choose what hud they come with. with them being in their locker.
I'd say give them blank sunglasses to start but add medglasses in their locker, your choice if you add secglasses aswell since they could just loot sec

**Comment by BombasterDS** [comment]
> I think BSO's are supposed to be allowed to choose what hud they come with. with them being in their locker. I'd say give them blank sunglasses to start but add medglasses in their locker, your choice if you add secglasses aswell since they could just loot sec

I think BSO need security glasses, but will blue sprite. Like, BSO only mission - protect heads.

**Comment by JoeHammad1844** [comment]
> I think BSO need security glasses, but will blue sprite. Like, BSO only mission - protect heads.

I believe the reason why BSO gets multiple glasses is so they can get closer to the head they are protecting in a way. for example: if you're protecting the HOS, wear the sec glasses. protecting CMO, wear medglasses

**Comment by Piras314** [comment]
glasses stuff can be tweaked in a future PR

**Comment by BombasterDS** [comment]
> > I think BSO need security glasses, but will blue sprite. Like, BSO only mission - protect heads.
> 
> I believe the reason why BSO gets multiple glasses is so they can get closer to the head they are protecting in a way. for example: if you're protecting the HOS, wear the sec glasses. protecting CMO, wear medglasses

Well. BSO glasses could be with sechud and medhud at same time

**Comment by JoeHammad1844** [comment]
> Well. BSO glasses could be with sechud and medhud at same time

Now that is just overpowered

**Comment by BombasterDS** [comment]
> > Well. BSO glasses could be with sechud and medhud at same time
> 
> Now that is just overpowered

This only pair in the game. Anyway, BSO only missions to protect heads.

**Pull request merged**
