### PR TITLE
ID card microwaving crate for cargo

### PR DESCRIPTION
**Pull request by starch70**
## About the PR
it gives cargo the ability to buy a crate for 150000 with 3 ID card boxes, 3 microwave flatpacks, and a ID card computer flatpack

## Why / Balance
gambling

## Technical details
adds prototypes for microwave and ID card computer flatpacks to goob's flatpacks.yml
also adds a cargo_materials.yml folder in resources\prototypes\_goobstation\fills\cargo
also also a resources\prototypes\_goobstation\fills\crates\materials.yml

## Media
this video except the ID card computer flatpack works because i used ComputerID instead of ComputerId
https://cdn.discordapp.com/attachments/1202734573247795303/1291151090833686608/2024-10-02_17-32-48.mp4?ex=66ff0da8&is=66fdbc28&hm=a0271761bc4ab42c27d3a20635a3be51e10e56efa1fcc9350e5318e2db151d2b&

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**
:cl:
- added a ID card computer flatpack, a microwave flatpack, and a ID microwaving crate to cargo for 150000 spesos in the materials tab

## Summary by CodeRabbit

- **New Features**
  - Introduced a new cargo product: Microwave with a cost of 150000.
  - Added a new crate: ID microwaving crate, containing microwaves and ID management components.
  - Added new flatpack entities: MicrowaveFlatpack (5 speso) and IDComputerFlatpack (200 speso).

These updates enhance the product offerings and improve user experience with new items for cargo and kits.

### CODE REVIEW

**Comment by BombasterDS** [comment]
Gambling is literally selfantaging.

**Comment by Piras314** [comment]
put it in the uplink and not cargo

**Comment by BombasterDS** [comment]
> put it in the uplink and not cargo

Not sure if it's good idea to add things that they can easily find on station in uplink. (suspect toolbox and flash lantern is rare maints loot that can't be obtained another way). In case of id cards agents can find them in hop's office. buy them in cargo or steal from crew.

**Comment by FungiFellow** [comment]
1. Gambling Access is self antag in 95% of circumstances

2. This Crate is far too cheap in terms of contents

3. Even as an Uplink Item I think the concept is lukewarm at best

**Comment by BombasterDS** [comment]
> 1. Gambling Access is self antag in 95% of circumstances
> 2. This Crate is far too cheap in terms of contents
> 3. Even as an Uplink Item I think the concept is lukewarm at best

Gambling is always antaging action.
You can order crate with ID cards in cargo, but with command access.

You shouldn't add something to make self-antaging easier (it won't make life easier for antags)

**Comment by starch70** [comment]
i'll have to ask my chat about this and putting it in uplink instead (maybe chef exclusive).... pondering...

**Comment by starch70** [comment]
ok i'll put it in uplink for like 55 TC but if i can i'll make it like 53 TC so its really inconveniently priced

**Comment by a-person5660** [comment]
Nah, you make it cost 100k at cargo :trollface: 

Syndies don't really have a use for this tbh.

**Comment by starch70** [comment]
ok i balanced it by making it cost 150000 spesos its not a problem if nobody can afford it

**Comment by starch70** [comment]
sh ut the fuck up metal man i know it costs 150000

**Comment by whateverusername0** [comment]
bro

**Comment by Piras314** [comment]
Oh brother, this PR stinks!

**Pull request closed without merging**
