### PR TITLE
Raise Phlogiston Reaction Priority

### PR DESCRIPTION
**Pull request by Speebr0**
## About the PR
Gave Phlogiston priority identical to CLF3, allowing for it's formation before smoke and foam removes it's reactants from the beaker.

## Why / Balance
Makes phlogiston more than just an alternative to CLF3 that doesn't explode.
I like plasma fires :godo:

## Technical details
- Phlogiston now has a priority of 20

## Media
hellmo

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

**Changelog**

:cl:
- tweak: Phlogiston now has a priority of 20, which makes it's reaction take place before foams and smokes :feelsgood:

### CODE REVIEW

**Comment by JoeHammad1844** [comment]
So what exactly does this mean for phlogiston? what chemical reactions are now possible?

**Comment by Speebr0** [comment]
This means that the phlogiston will now be created alongside it's PLASMA GAS. Before the foam goes out and sets everybody on fire with it. This causes an immediate plasma fire.

**Comment by JoeHammad1844** [comment]
right so if i make phlog foam it will flood the room in plasma and the foam will set people on fire?

**Comment by Speebr0** [comment]
yeah precisely

**Comment by JoeHammad1844** [comment]
hellfoam real

**Comment by Speebr0** [comment]
NGL I may have gone a bit crazy with this one, but the trade-off of less foam for more plasma is probably balanced unless bluespace beakers are used, then everything goes to hell!

**Comment by Speebr0** [comment]
And if nobody is caught in the foam then the plasma never ignites

**Pull request merged**
