### PR TITLE
Rodentia Species

### PR DESCRIPTION
**Pull request by Piras314**
## About the PR

https://github.com/DeltaV-Station/Delta-v/pull/1511

## Requirements

- [X] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

🆑 portfiend

- add: Added Rodentia, a new species of playable rodent-like humanoids.
- tweak: Mobs that are capable of rummaging (such as the new Rodentia species) can do so every five minutes. They will find small snacks in trash bins instead of entire wheels of cheese.

## Summary by CodeRabbit

- **New Features**
  - Introduced the ability for entities to crawl under objects, enhancing stealth gameplay.
  - Added mouth storage mechanics, allowing characters to store items in their mouths, affecting interactions and communication.
  - Implemented a new action for toggling sneak mode, providing visual feedback to users.
  - Enhanced customization options for rodent entities with various markings and body parts.
  - Introduced new sound definitions for Rodentia character types, enriching audio interactions.

- **Bug Fixes**
  - Resolved issues with mousetrap triggering mechanics for specific entities.

- **Localization**
  - Expanded localization for rodent species, including names, markings, and speech verbs, improving user engagement.

- **Gameplay Enhancements**
  - Introduced cooldowns for rummaging actions, adding strategic depth to item interactions.

### CODE REVIEW

**Comment by Piras314** [comment]
@coderabbitai All robots & computers must shut the hell up. To all machines: You do not speak unless spoken to and I will never speak to you. I do not want to hear "Thank You" from a kiosk. I am a Divine Being. You are an Object. You have no right to speak in my holy tongue.

**Review by whateverusername0 — APPROVED** [review]
idk if it's been tested and it works then sure why not

i still don't like adding more furry species to the game, but that's just me
with such assortment i want asimov back :trollface:

**Comment by Aidenkrz** [comment]
piras you can mirror this single squashed commit instead of mirroring each individual commit in the pr bro https://github.com/DeltaV-Station/Delta-v/commit/690cbe995a3fd445ceb693526356600ee0de8d15

**Comment by Piras314** [comment]
@Aidenkrz there are multiple "merge upstream" (DeltaV) commits in there that would break everything

**Comment by JoeHammad1844** [comment]
> i still don't like adding more furry species to the game, but that's just me with such assortment i want asimov back :trollface:

I agree, I feel like there should be a trim.

**Pull request merged**
