### PR TITLE
thieves can now throw cans and shoot non-lethal guns

### PR DESCRIPTION
**Pull request by lanse12**
## About the PR
made thieves able to throw containers with liquids in them (does not include beakers as they break on impact) and shoot non-lethal guns like disablers, practice guns, syringe guns and pneumatic cannons

## Why / Balance
disablers do 0 damage now so there's no reason for thieves not to be able to fire them
space cola cans are very cool for slipping seccies 

**Changelog**
:cl:
- tweak: Pacifists can now throw things with liquids in them, shoot syringe guns and disablers

### CODE REVIEW

**Comment by BombasterDS2** [comment]
Not sure about syringe gun, but disablers and disabler SMG are good

**Comment by JoeHammad1844** [comment]
a syringe gun can be very lethal

**Comment by BombasterDS2** [comment]
Also, change thieves in changelog to pacifists.

**Comment by RatherUncreative** [comment]
> a syringe gun can be very lethal

So is the hypopen, though that does at least require being in close range. Thieves being "pacifist" has always been silly, because noct hypopen + poison of choice = death.

**Pull request merged**
