### PR TITLE
Fix medborg surgery

### PR DESCRIPTION
**Pull request by AstroDogeDX**
## About the PR

Medborgs can do surgery again.

## Why / Balance

hehe fune robit cut u open :)

## Technical details

With the changes to how Cyborgs can now just morph into whichever type they want, this broke Medborgs having the necessary components to do surgery. `SurgeryTarget` and `Sanitized` has been added to the new prototypes that determine what a 'borg inherits when it morphs, allowing them to do surgery again.

## Media

it's shitmed, you know what it looks like

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl:
- fix: Medborgs can now perform surgery again.

### CODE REVIEW

**Comment by deltanedas** [comment]
dont need surgerytarget anymore

**Comment by AstroDogeDX** [comment]
> dont need surgerytarget anymore

I tried without it and it didn't work. Is there another component that is supposed to be used or do we need to define a different tag or - like what? I'm not familiar with the med code at all.

**Comment by gluesniffler** [comment]
> dont need surgerytarget anymore

nah you still do, the changes you had made were only for the bUI, but the VerbEvent was still checking for it, and I havent PR'd any C# to shitmed since, ill clean this up along with the refactors i need to port here

**Comment by AstroDogeDX** [comment]
I mean I just consider this a hotfix for now anyway. If shitmed refactors come before this is merged and thus becomes pointless then this can be closed 👍

**Comment by deltanedas** [comment]
oh real

**Pull request merged**
