### PR TITLE
re add bluespace crystal to protolathe

### PR DESCRIPTION
**Pull request by lanse12**
## About the PR
readded back bluespace crystals protolathe recipe
BUT made them much more expensive
also i nerfed their selling price

## Why / Balance
why are we going the wizden way of removing shit instead of fixing it

**Changelog**
:cl:
- add: bluespace crystal recipe to protolathe

### CODE REVIEW

**Comment by Aineias1** [comment]
JUST FORCE SALVAGERS TO MINE IT
JUST FORCE SALVAGERS TO MINE IT
JUST FORCE SALVAGERS TO MINE IT
JUST FORCE SALVAGERS TO MINE IT
JUST FORCE SALVAGERS TO MINE IT
JUST FORCE SALVAGERS TO MINE IT
JUST FORCE SALVAGERS TO MINE IT
JUST FORCE SALVAGERS TO MINE IT
JUST FORCE SALVAGERS TO MINE IT

**Comment by BombasterDS** [comment]
It should be rare ore, not craftable thing

**Comment by lanse12** [comment]
dude it's way too fucking rare as of now
there's like 10 crystals per vgroid

**Comment by BombasterDS** [comment]
> dude it's way too fucking rare as of now there's like 10 crystals per vgroid

Add more ore on vgroid. Craftable BScrystal ruining balance of antags and cargo. (You buffed craft price to ~200-300, but it one BScrystal still costs 10 times more)

**Comment by BombasterDS** [comment]
> why are we going the wizden way of removing shit instead of fixing it. 

What does that mean? We didn't remove bluespace crystal, we fixed it by deleting recipe. Bro, deleting some stuff is not bad thing.

**Comment by lanse12** [comment]
didn't you say remove the reclaimer on discord like an hour ago

**Comment by BombasterDS** [comment]
> didn't you say remove the reclaimer on discord like an hour ago

I think it should be deleted. Still i didn't pr it.

**Comment by AstroDogeDX** [comment]
imo I think diamonds and bs crystals should get a bump in ore distrib but I'm fine with them being uncraftable for the myriad of reasons already stated.

Any excuse to have more reasons to pressure salvage into actually playing the game properly is good.

**Comment by ARMOKS** [comment]
I balanced some alchemy stuff around the crystals being in the game, any shot you could keep them the same proto price but make them sell for far less?

**Comment by lanse12** [comment]
> I balanced some alchemy stuff around the crystals being in the game, any shot you could keep them the same proto price but make them sell for far less?

yea ngl it was a little too easy to for antags to get AA with crystals
on revs i'd rush sci, make myself 30 and get free fucking aa

**Comment by BombasterDS2** [comment]
> I balanced some alchemy stuff around the crystals being in the game, any shot you could keep them the same proto price but make them sell for far less?

I think that better solution are increasing diamonds and BScrystal amount on vgroid. They're to rare. Still, returning them to protolathe is ruining balance and not logical, because BScrystal should be rare ore.

**Review by whateverusername0 — CHANGES_REQUESTED** [review]
bro you didn't nerf their selling price
you just made them stack to 5

bring it back to 30 and actually change the price

**Comment by lanse12** [comment]
oh it's stacks lmaoo

**Comment by lanse12** [comment]
lowkey i don't give a fuck

**Pull request closed without merging**
