### PR TITLE
Mail JobTitle fixes. New mail teleporter sprites from FunkyStation.

### PR DESCRIPTION
**Pull request by BombasterDS**
## About the PR
Changed JobTitle check for LocalizedJobTitle check.

Better mail teleporter sprite from FunkyStation - https://github.com/funky-station/funky-station/commit/430be9247ac220367f338c2c1a716a7503b1446d

:cl:
- fix: Mail Teleporter works again

## Summary by CodeRabbit

- **New Features**
	- Enhanced mail recipient handling with improved job title matching.
	- Added a `scale` property to the `MailTeleporter` entity for better visual representation.

- **Bug Fixes**
	- Updated copyright information for the mailbox resource and adjusted its dimensions for consistency.

- **Documentation**
	- Minor adjustments to comments and formatting for clarity and style adherence.

### CODE REVIEW

**Comment by taydeo** [comment]
Hi, quick note on your PR.

We've had this issue on Funky Station where mail was completely broken. Our fix for this was to add `id.JobTitle = jobTitle` to `SharedIdCardSystem.cs`.

image

While this might not be the best fix, it was the fix that caused the least amount of issues, and restored functionality to broken aghost scripts and other miscellaneous errors.

**Comment by BombasterDS** [comment]
> Hi, quick note on your PR.
> 
> We've had this issue on Funky Station where mail was completely broken. Our fix for this was to add `id.JobTitle = jobTitle` to `SharedIdCardSystem.cs`.
> 
> image
> 
> While this might not be the best fix, it was the fix that caused the least amount of issues, and restored functionality to broken aghost scripts and other miscellaneous errors.

Wizden changed id card job title so thats why it get broken. I just replaced JobTitle with LocalizedJobTitle in mail code

**Comment by BombasterDS** [comment]
It works the same, but doesn't touch wizden code

**Comment by taydeo** [comment]
Alright, I'll do some tests with aghost scripts as we've had our admins complain about scripts not working (for example, admin PDA ID doesn't change title or name), and with this fix in, it was gone.

**Comment by BombasterDS** [comment]
Test fail unrelated

**Review by whateverusername0 — APPROVED** [review]

**Pull request merged**
