### PR TITLE
Head Antagonists but i'm on a different branch now

### PR DESCRIPTION
**Pull request by whateverusername0**
## About the PR
made department heads antaggable and removed their mindshield (except hos ofc)
leaving security, captain, NTR and BSO the only trustworthy people on the station and, hopefully, decreasing the amount of shitters on command, since they're now _one with the people™️_ ⭐

also in revolution gamemode ~~you will be able to get a win by revving all heads, instead of killing them (sec and captain are still mindshielded, so it's traditional kos)~~ heads are unrevvable no matter if they have a mindshield or not.

## Why
SS13 content. also would be good enough of an experiment

also for some reason my local branch pushed to master. literally how.

:cl:
- add: Heads of department can now roll antag

### CODE REVIEW

**Review by misandrie — CHANGES_REQUESTED** [review]
>Command headrevs

The better approach to this is to make traitor command be extremely unlikely but not an impossibility outside of admin fuckery - this will solve the antag metagaming of "command player is always right" and the difficulty of replacing command staff

**Comment by TooSillyFennec** [comment]
1: Yes, non-sec Command doesn't have mindshields on TG for example. But they are **_immune_** from being revs even with no shield for a reason on 13. The only reason they don't have them on TG is cult, actually, and not all servers follow TG with this. Also, Command's already weaker here due to less command players. Don't make command revvable, please god.

2: HoP maybe shouldn't be an antag- they are 2nd to the captain! and also they have general sec access for example.

3: Heads have a specifically decreased weight to be antag on 13, and paradise for example has a limit of 1-2 heads antags with the 2 heads being rarely allowed. Maybe implement that before adding head antags?

Anyways, blatantly refer to a maintainer not me, but these are general concerns that needed to be said. Anyways, good concept but the revs part is really bad.

**Comment by whateverusername0** [comment]
> 1: Yes, non-sec Command doesn't have mindshields on TG for example. But they are **_immune_** from being revs even with no shield for a reason on 13. The only reason they don't have them on TG is cult, actually, and not all servers follow TG with this. Also, Command's already weaker here due to less command players. Don't make command revvable, please god.

ok. making command revvable IS a bad idea.

> 2: HoP maybe shouldn't be an antag- they are 2nd to the captain! and also they have general sec access for example.

head of personnel afaik is literally the head of service, so why not leave him at that? how about we remove security and brig access from antaggable heads?

> 3: Heads have a specifically decreased weight to be antag on 13, and paradise for example has a limit of 1-2 heads antags with the 2 heads being rarely allowed. Maybe implement that before adding head antags?

still there can be 5 heads at max. the change of them becoming antags in, for example, a 50 pop is small enough to be ignored i believe

**Comment by Aidenkrz** [comment]
Closing for now, almost unanimous disagreement from admins on this, although I would've at least liked to playtest it in the future. For now if you want to make a command headrev gamemode that would be based ;-)

**Pull request closed without merging**
