### PR TITLE
aiming update (very robust)

### PR DESCRIPTION
**Pull request by whateverusername0**
## About the PR
nerf wideswing because it's stinky

not a mald PR, trust
it's just that wideswing is a literal upgrade to a normal precise attack, which it shouldn't be (see pre-nerf charging wide swing "heavy" attack)
and i want a challenge :trollface: 

we're growing a new robust generation of tiders
also preventing kids and raiders who only know wideswing, since they won't do shit after this gets merged :godo:

this won't affect weapons that deal stamina damage because there's a different system for that which does NOT support wideswing. i hate it and i really want to refactor it but... eh

media

normal attack
image

wideswing
image

hits it takes to robust a naked with precise attacks - 7
with wideswing - 15

:cl:
- tweak: Wideswing now deals significantly less damage than a precise hit.

### CODE REVIEW

**Comment by whateverusername0** [comment]
literally a 1 liner change :trollface:

**Comment by misandrie** [comment]
https://github.com/space-wizards/space-station-14/pull/19860

**Comment by whateverusername0** [comment]
> [space-wizards/space-station-14#19860](https://github.com/space-wizards/space-station-14/pull/19860)

image
hell naw

**Comment by whateverusername0** [comment]
image
he never did that

**Comment by a-person5660** [comment]
L+mald pr
Wideswings are fine.

**Comment by whateverusername0** [comment]
> L+mald pr Wideswings are fine.

hell naw bro learn to aim

**Comment by Aidenkrz** [comment]
> stam resist and wideswing nerf prs made at the same time
someone got baton'd by a cadet while playing nukie huh?

**Comment by Aidenkrz** [comment]
Besides, i plan on porting over the targetting doll from WD here soon enough, which will be an actual aiming update.

**Comment by whateverusername0** [comment]
> someone got baton'd by a cadet while playing nukie huh?

:trollface:
nah bro i'm on a nukie win streak, i just want to make lives harder

**Comment by JoeHammad1844** [comment]
just un-revert the left click damage bonus :trollface:

**Comment by whateverusername0** [comment]
> just un-revert the left click damage bonus :trollface:

it was what like 1.25x? if we make it sth like 1.75x then it'd be good :godo:

**Comment by packmore** [comment]
> > just un-revert the left click damage bonus :trollface:
> 
> it was what like 1.25x? if we make it sth like 1.75x then it'd be good :godo:

sus toolboxes being able to down people in three hits is actually unbelievably scuffed

**Pull request closed without merging**
