### PR TITLE
fix actions not actioning

### PR DESCRIPTION
**Pull request by whateverusername0**
## About the PR

actions did not want to move around
i made them move around
it was very hard and i spent a lot of time on this ( :trollface: )

:cl:
- fix: fixed actions not actioning

## Summary by CodeRabbit

- **Bug Fixes**
	- Disabled the `FrameUpdate` method in the actions system to resolve issues with action handling.
  
This change will impact how actions are processed during each frame, improving overall system stability.

### CODE REVIEW

**Comment by whateverusername0** [comment]
@coderabbitai do not review

**Comment by a-person5660** [comment]
merge now :trollface:

**Comment by a-person5660** [comment]
this seriously could not be merged faster...

**Comment by Piras314** [comment]
make them work with the greyed out system eventually though pls :pray:

**Pull request merged**
