### PR TITLE
Mp40

### PR DESCRIPTION
**Pull request by BorealStation**
## About the PR
Adds the MP40, the Atomwaffen commander is given it roundstart
:cl:
- add: Added the MP40 for Atomwaffen commanders

### CODE REVIEW

**Comment by BorealStation** [comment]
fvck

**Comment by BorealStation** [comment]
wrong fucking.. AGAIN

**Comment by whateverusername0** [comment]
image
bro :finnadie:

**Comment by BorealStation** [comment]
> image bro :finnadie:

sorry dude it was an accident, honest!

**Comment by BorealStation** [comment]
honestly would banning me from the repo prevent this? or would i be unable to merge master and such?

**Comment by Piras314** [comment]
it's not that hard to look at where you're making the pr before doing it, purely an issue of skill 🤓

**Comment by GroggleG** [comment]
> image bro :finnadie:

What in the actual FUCK

**Comment by BorealStation** [comment]
> it's not that hard to look at where you're making the pr before doing it, purely an issue of skill 🤓

definetly

**Comment by Piras314** [comment]
ngl after seeing what's in this pr you can get your repoban

**Pull request closed without merging**
