### PR TITLE
Port Supermatter To Goob

### PR DESCRIPTION
**Pull request by VMSolidus**
## About the PR
Oops, I dropped something really cool, I hope nobody merges this and then forces their mappers into a gulag to implement a funny new engine.

### CODE REVIEW

**Comment by Verbalase** [comment]
real

**Comment by a-person5660** [comment]
cant wait for engi to destroy the entire station in yet another spectacular way

**Comment by whateverusername0** [comment]
this from wd 😭

**Comment by Aidenkrz** [comment]
This doesnt support goob stations file schema at all, for shame VM!

**Comment by Teapug** [comment]
the first 10 rounds with suppermatter  are going to be like 3 minutes long

**Review by Aidenkrz — APPROVED** [review]

**Pull request merged**
