### PR TITLE
drastic ling changes

### PR DESCRIPTION
**Pull request by whateverusername0**
## About the PR
added biomass to changelings.
now they cannot die normally, as in getting gibbed because of it. (you can still cremate them but whatever)
biomass is now their health instead of the normal one.
biomass will drain once every minute with a max of 30 biomass. (for now i guess)
lings need to absorb people to get biomass back. one absorption regenerates ALL biomass.

image

after reaching certain thresholds of biomass lacking following things will happen:
ling will get notified
ling will start vomiting blood
ling will start shaking. slightly
at the last 3 minutes ling will go into a frenzy as a last resort, x3 chemicals and constant jittering
when biomass reaches 0 they will take 50 genetic damage each bio cycle until they finally die.

now entering stasis also costs 1 biomass.

now lings have only two objectives - survive and escape to centcom while being _person_.
survive as in actually manage to keep up with biomass demands

also each time you absorb someone you gain progressively less biomass, so going on an absorption frenzy is not a good idea, or you'll have to store up piles of dead bodies (or phalanx) if you want to live, i guess.

## Why / Balance
i saw that one design doc on wizden. i liked it and thought it would be a good idea

this also opens up more strats for security and for getting rid of lings overall, giving perma and **exile station grids** more chances to be useful in an average round, since i believe the most basic strat will be starving the ling to death.

## gameplay Breaking changes
yes

**Changelog**
:cl:
- add: Added biomass to changelings. Now they cannot die unless they run out of biomass.
- add: Changelings must absorb people to recover biomass.
- fix: Fixed changeling transform ability not transferring stuff correctly.
- fix: Fixed round end changeling prepend text not working correctly.
- tweak: Now absorbing another changeling gives a half of it's max chemicals, biomass and evolution points instead of a fixed amount.

### CODE REVIEW

**Comment by whateverusername0** [comment]
hold on one more commit

**Comment by whateverusername0** [comment]
ok cool

**Comment by misandrie** [comment]
does absorbing still round remove someone

**Comment by whateverusername0** [comment]
> does absorbing still round remove someone

yes

**Comment by JoeHammad1844** [comment]
is the CL referencing the whack ass crystal prison?

**Review by Piras314 — APPROVED** [review]

**Comment by whateverusername0** [comment]
> is the CL referencing the whack ass crystal prison?

@JoeHammad1844 yes

**Review by misandrie — CHANGES_REQUESTED** [review]
Simulate how many other players does the changeling have to consume to stay healthy for 80 minutes

**Comment by whateverusername0** [comment]
> Simulate how many other players does the changeling player has to consume to stay healthy for 80 minutes

3

**Comment by misandrie** [comment]
> > Simulate how many other players does the changeling player has to consume to stay healthy for 80 minutes
> 
> 3

Any way to prove that?

**Comment by whateverusername0** [comment]
> > > Simulate how many other players does the changeling player has to consume to stay healthy for 80 minutes
> > 
> > 
> > 3
> 
> Any way to prove that?

you have 30 max biomass. you get -1 biomass every minute. if you eat a person once every 25 minutes you'll need to eat 3 people

**Comment by misandrie** [comment]
> > > > Simulate how many other players does the changeling player has to consume to stay healthy for 80 minutes
> > > 
> > > 
> > > 3
> > 
> > 
> > Any way to prove that?
> 
> you have 30 max biomass. you get -1 biomass every minute. if you eat a person once every 25 minutes you'll need to eat 3 people

So 3 people at bare minimum if we assume ling player kills and absorbs someone almost at max hunger

**Comment by Piras314** [comment]
erm it's the rhombicosidodecahedron not the rhombiicosedodecahedron

**Comment by Aidenkrz** [comment]
make a real changelog before i merge this

**Comment by whateverusername0** [comment]
> make a real changelog before i merge this

@Aidenkrz done

**Comment by whateverusername0** [comment]
one more commit and it's ready to get merged hold on

**Pull request merged**
