### PR TITLE
false walls

### PR DESCRIPTION
**Pull request by whateverusername0**
## About the PR

port https://github.com/space-wizards/space-station-14/pull/27908\

:cl:
- add: Added false walls. To build one, apply crowbar on a girder and then use whatever sheet of metal you want your false wall to be.

## Summary by CodeRabbit

- **New Features**
	- Introduced a new construction graph node, `displacedGirder`, expanding construction options for various false walls.
	- Added multiple new false wall types, including `SolidFalseWall`, `PlasticFalseWall`, `GoldFalseWall`, and more, each with unique properties and construction requirements.
	- New entity `DisplacedGirder` added, representing a structurally unstable girder with specific damage behaviors.

- **Documentation**
	- Metadata files created for new texture assets, detailing dimensions, states, and licensing information for various false wall textures.

### CODE REVIEW

**Comment by BombasterDS** [comment]
It does the same thing as secret door?

**Comment by BombasterDS** [comment]
Also wall and reinf wall in this pr have wizden textures.

**Comment by whateverusername0** [comment]
> It does the same thing as secret door?
> 
> If so, i think it's better to change false walls craft to: crowbar -> 4 rods -> 4 lv cables -> other materials for walls. (maybe delete basic secret door because it will be useless)

why would you need cables and a powercell for a fake wall

**Comment by BombasterDS** [comment]
> > It does the same thing as secret door?
> > If so, i think it's better to change false walls craft to: crowbar -> 4 rods -> 4 lv cables -> other materials for walls. (maybe delete basic secret door because it will be useless)
> 
> why would you need cables and a powercell for a fake wall

just cables without powercell

**Comment by whateverusername0** [comment]
> just cables without powercell

where would you put wiring on a fake door without any power then

**Comment by BombasterDS** [comment]
> > just cables without powercell
> 
> where would you put wiring on a fake wall without any power then

secret doors work this way

**Comment by whateverusername0** [comment]
> secret doors work this way

these are fake walls not secret doors :goberserk:

**Comment by BombasterDS** [comment]
> > secret doors work this way
> 
> these are fake walls not secret doors :goberserk:

they have same functionality

**Comment by Piras314** [comment]
> Also wall and reinf wall in this pr have wizden textures.

**Comment by Piras314** [comment]
@whateverusername0

**Comment by Aidenkrz** [comment]
https://github.com/space-wizards/space-station-14/pull/32131
this is still open on upstream anyway.

**Comment by whateverusername0** [comment]
oh nice

**Comment by lanse12** [comment]
re open pleaseee

**Comment by Piras314** [comment]
reopen please

**Pull request closed without merging**
