### PR TITLE
fix borg limbs and make borg legs good

### PR DESCRIPTION
**Pull request by deltanedas**
## About the PR
you can now attach hands/feet

borg legs also make you 25% faster now

## Why / Balance
Body Modder Transformed +13
I asked for this.

## Technical details
shitcode only initializes body not bodypart

## Requirements
- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes
no

**Changelog**
:cl:
- fix: Fixed not being able to install hands onto cyborg arms.
- tweak: Cyborg legs make you 25% faster.

## Summary by CodeRabbit

- **New Features**
	- Enhanced definitions for cyborg body parts, including tool names and child entities for hands and feet.
	- Updated movement speeds for legs, providing a 25% speed boost for walking and sprinting.

- **Improvements**
	- Added sound paths for the SurgeryTool component, improving functionality and user experience.
	- Improved management of body parts with new event handling for initialization, removal, and enabling/disabling actions.

### CODE REVIEW

**Comment by deltanedas** [comment]
test fail caused by topical pr

**Comment by a-person5660** [comment]
give arms an accurace/melee damage boost or something while you are at it. myabe make borg arms stackable so we can have 4 arms like we can stack spider limbs.

**Comment by deltanedas** [comment]
wyci

**Comment by gluesniffler** [comment]
image
The change makes it so that the VV viewer for the Children shits itself because theres not an associated container with this lol. Should we just be lazy and comment it out, or do it properly?

**Comment by JoeHammad1844** [comment]
do arms come with hands or are they just arms?

**Comment by deltanedas** [comment]
> do arms come with hands or are they just arms?

no you still have to put human/whatever hands on

**Comment by deltanedas** [comment]
> do it properly?

3 line ops

**Comment by gluesniffler** [comment]
> > do it properly?
> 
> 3 line ops

pro

**Review by whateverusername0 — APPROVED** [review]
unrelated test fail. i approve

**Pull request merged**
