### PR TITLE
Cybersun Stealth Hardsuit

### PR DESCRIPTION
**Pull request by starch70**
https://discord.com/channels/1202734573247795300/1304950535186546718/1304950535186546718

## About the PR
add cybersun stealth hardsuit to uplinks for 75 TC
(raise it to 90 TC when HUD shit with stealthed entities stop appearing!! merge the upstream fix already!!)

## Why / Balance
https://discord.com/channels/1202734573247795300/1304950535186546718/1304950535186546718

## Technical details
i had to put stealthonmove apply from the hardsuit and stealth apply from the helmet lol because shitcode

## Media
https://github.com/user-attachments/assets/d28a0b98-596b-42df-a76d-e0de83e50d55

readgdfgcvhvcbhvbn

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**
:cl:
- add: Added the Cybersun Stealth Hardsuit to the syndicate uplink for 75 TC

## Summary by CodeRabbit

- **New Features**
	- Introduced the "Cybersun Stealth Hardsuit" to the uplink catalog, featuring stealth plating and unique attributes.
	- Added a "Cybersun Stealth Hardsuit Helmet" for enhanced stealth operations.
	- Launched a new hardsuit bundle, the "Syndicate Stealth Hardsuit Bundle," including various components.

- **Documentation**
	- Added metadata files for the new hardsuit and helmet graphics, detailing licensing and resource states.

### CODE REVIEW

**Review by whateverusername0 — APPROVED** [review]
can't really find any use for it but sure go for it 👍

**Comment by Agustron24** [comment]
This could prevent ninja metagaming a bit more, since now seeing cloak thing isnt instantly "NINJAAAAAAAAAAAAAAA!!!!" On comms.

**Comment by JoeHammad1844** [comment]
> This could prevent ninja metagaming a bit more, since now seeing cloak thing isnt instantly "NINJAAAAAAAAAAAAAAA!!!!" On comms.

ive seen ninja get called because of an anomaly infection turning someone partially invisible

**Comment by InfinityPandaRed** [comment]
HELL YEAH

**Comment by Agustron24** [comment]
> ive seen ninja get called because of an anomaly infection turning someone partially invisible

Whoever did that is to be ahelped and banned tbh

**Comment by whateverusername0** [comment]
> > ive seen ninja get called because of an anomaly infection turning someone partially invisible
> 
> Whoever did that is to be ahelped and banned tbh

you'll make best wizden admin

**Comment by starch70** [comment]
> can't really find any use for it but sure go for it 👍

it will be more useful when the fix for hud shit appearing on stealthed entities gets merged here :fire:

**Comment by deltanedas** [comment]
> ive seen ninja get called because of an anomaly infection turning someone partially invisible

this was me, i then got shot by sec and bled to death while a borg was beating me for "not having an id"

**Comment by Aineias1** [comment]
> This could prevent ninja metagaming a bit more, since now seeing cloak thing isnt instantly "NINJAAAAAAAAAAAAAAA!!!!" On comms.
Also lings with chamelion evolution

**Comment by Aineias1** [comment]
> This could prevent ninja metagaming a bit more, since now seeing cloak thing isnt instantly "NINJAAAAAAAAAAAAAAA!!!!" On comms.

Also me when i roll ling, i always pick the chameleon thingy

**Comment by JoeHammad1844** [comment]
> Also me when i roll ling, i always pick the chameleon thingy

I've seen sec forget to cremate a ling because they had invisibility.

They put him IN the crematorium but didn't turn it on, opened it and didn't see him because he was invisible and thought the job was done

**Comment by a-person5660** [comment]
i once got killed and cuffed as a ling then they lost me completely cause they couldnt find where they left me lmao

**Comment by Agustron24** [comment]
Omg an idea i suggested ended up in!.

Thanks for coding it in!!

**Pull request merged**
