### PR TITLE
Dynamic suffering vol. 5

### PR DESCRIPTION
**Pull request by whateverusername0**
## About the PR

fixed dynamic is a meme now
millions must roll
i hope this shit will finally fix dynamic

:cl: goob lord dynamic fixer shi john stun
- fix: Fixed dynamic.

### CODE REVIEW

**Comment by Aineias1** [comment]
Just a week away

**Comment by Aidenkrz** [comment]
please fucking reset your branch

**Comment by JustSome1Nearby** [comment]
"Dynamic ia fixed i swear bro"
Server -_- Restarting round...

**Comment by gluesniffler** [comment]
that feeling when ~~knee surgery~~ dynamic is working tomorrow

**Comment by Piras314** [comment]
use a new fucking branch from master please

**Pull request merged**
