### PR TITLE
The Grinch is here

### PR DESCRIPTION
**Pull request by Sarahon**
## About the PR
Added some christmas bads as syndicate suits.

## Why / Balance
It's chrimaaaa

## Media
image
image

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**
:cl:
- add: Christmas baddies for nukie suits

### CODE REVIEW

**Comment by starch70** [comment]
you forgor to resprite the stealthsuit...

**Comment by Sarahon** [comment]
> you need to update the meta.json files to give yourself credit for the sprites

grr forgor

**Comment by JoeHammad1844** [comment]
Can't tell between regular elite and medic hardsuit

**Comment by Sarahon** [comment]
> Can't tell between regular elite and medic hardsuit

there's no difference, that'd be why

**Comment by Piras314** [comment]
It'd be nice if someone made this as holdiayvisuals so that we don't have to cherry pick and revert this every time.

**Pull request merged**
