### PR TITLE
Add "Violet" by Mrjajkes to the Automatic Zombie Evacuation

### PR DESCRIPTION
**Pull request by Piras314**
## About the PR

Adds ["Violet" by mrjajkes](https://www.youtube.com/watch?v=ixCcviVDJEg) to the automatic emergency shuttle call for Zombies.

Currently does not work for an unknown and completely mysterious reason. It spams the console with an error:
```csharp
[ERRO] runtime: Caught exception in "entsys"
System.ArgumentException: Path must be rooted
   at Robust.Shared.Audio.Systems.SharedAudioSystem.SetupAudio(String fileName, Nullable`1 audioParams, Boolean initialize, Nullable`1 length) in C:\Users\admin\Documents\Programming\CS\Goob-Station\RobustToolbox\Robust.Shared\Audio\Systems\SharedAudioSystem.cs:line 311
   at Content.Server.Chat.Systems.ChatSystem.DispatchStationAnnouncement(EntityUid source, String message, String sender, Boolean playDefaultSound, SoundSpecifier announcementSound, Nullable`1 colorOverride) in C:\Users\admin\Documents\Programming\CS\Goob-Station\Content.Server\Chat\Systems\ChatSystem.cs:line 401
   at Content.Server.GameTicking.Rules.ZombieRuleSystem.CheckRoundEnd(ZombieRuleComponent zombieRuleComponent) in C:\Users\admin\Documents\Programming\CS\Goob-Station\Content.Server\GameTicking\Rules\ZombieRuleSystem.cs:line 135
   at Content.Server.GameTicking.Rules.ZombieRuleSystem.ActiveTick(EntityUid uid, ZombieRuleComponent component, GameRuleComponent gameRule, 
Single frameTime) in C:\Users\admin\Documents\Programming\CS\Goob-Station\Content.Server\GameTicking\Rules\ZombieRuleSystem.cs:line 159      
   at Content.Server.GameTicking.Rules.GameRuleSystem`1.Update(Single frameTime) in C:\Users\admin\Documents\Programming\CS\Goob-Station\Content.Server\GameTicking\Rules\GameRuleSystem.cs:line 142
   at Robust.Shared.GameObjects.EntitySystemManager.TickUpdate(Single frameTime, Boolean noPredictions) in C:\Users\admin\Documents\Programming\CS\Goob-Station\RobustToolbox\Robust.Shared\GameObjects\EntitySystemManager.cs:line 306
```

And spams the game with the text announcement in-game, but doesn't play the sound / song at all. This even occurs when the ogg path is taken from a working announcement, the one right above it in fact. Without the song added to the announcement, the announcement works perfectly fine and doesn't spam.

This PR also removes a duplicate of redsun.ogg.

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl: Piras314, mrjajkes
- add: The song "Violet" by mrjajkes now plays when the emergency shuttle is automatically called during Zombies.

## Summary by CodeRabbit

- **New Features**
	- Introduced a new sound announcement for the zombie shuttle call, enhancing gameplay feedback.
	- Added attribution details for the new audio file `violet.ogg`, including licensing and source information.

- **Bug Fixes**
	- Improved clarity in the zombification process by ensuring associated actions are properly managed. 

- **Documentation**
	- Added comments to key methods for better understanding and context regarding their functionality.

### CODE REVIEW

**Comment by Piras314** [comment]
discussion on wizden discord [here](https://discord.com/channels/310555209753690112/560845886263918612/1307364722286268426), could not solve the issue.

**Comment by Aidenkrz** [comment]
tests are unrelated so... seems to be working on linux at least?

**Comment by Aidenkrz** [comment]
Should retry this now that we've merged upstream

**Comment by Piras314** [comment]
The announcementSound part of DispatchStationAnnouncement is just broken, I can't find any place where it works, so I am making a new PR using PlayGlobal instead. It was completely unrelated to this PR though, it's broken on master.

**Pull request closed without merging**
