### PR TITLE
disable evasion

### PR DESCRIPTION
**Pull request by lanse12**
image

### CODE REVIEW

**Comment by Piras314** [comment]
evasion is so awful

**Comment by JustSome1Nearby** [comment]
POV Captain evaded your Armblade 17 times in a row

**Comment by gluesniffler** [comment]
might want to revert the armblade and esword buffs from armok too if you're gonna remove it, otherwise you'll have armblades beheading people in 2 hits lmao

**Comment by JustSome1Nearby** [comment]
> might want to revert the armblade and esword changes from armok too if you're gonna remove it, otherwise you'll have armblades beheading people in 2 hits lmao

Isnt that the point of an overpriced 4 points weapon
 wich makes you insta-valid to everyone, with sound AND visuals ,
 requiring precision to do atacks  (ELSE you loose a lot of stanina on wideswings) in quick succession (they WILL run away else and then proceed to magdump every tider in maints JUST TO BE SURE)

This weapon REWARDS for using strategy and sting synergy

**Comment by Aviu00** [comment]
I fixed it though... Only head can evade now and other issues are fixed. I like current esword delimbing combat.

**Comment by whateverusername0** [comment]
armblade users celebrating

**Comment by JustSome1Nearby** [comment]
I think we dont need this PR
Evading really DID get fixed and now applies only to Head
Since with "Fix Wheelchair Bound" people fall prone with 1 or more legs missing, Armblade will have better combat intereactions at LEAST against humanoids
(Ill break your knees - the Update)

**Comment by Piras314** [comment]
yea no it is fine now my bad

**Pull request closed without merging**
