### PR TITLE
mechops real

### PR DESCRIPTION
**Pull request by gluesniffler**
## About the PR
Ports [#32346 from Wizden](https://github.com/space-wizards/space-station-14/pull/32346). 

## Why / Balance
image

## Requirements
- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.
- [X] I was playing [HEATS](https://www.youtube.com/watch?v=EHOPTVBFpgM) while porting this PR.

**Changelog**
:cl: Mocho, ThunderBear2006, NULL882
- tweak: The H.O.N.K. has received an airtight cabin for honk operations in outer space.
- add: Added the Ripley MK-II, a heavy, slow all-purpose mech, featuring a pressurized cabin for space operations.
- add: Added the Clarke, A fast moving mech for space travel, with built in thrusters (not certain if they work properly though :trollface:)
- add: Added the Gygax, a lightly armored and highly mobile mech with enough force to rip walls, or someone's head off.
- add: Added the Durand, a slow but beefy combat suit that you dont want to fight in close quarters.
- add: Added the Marauder, a specialized mech issued to ERT operatives.
- add: Added the Seraph, a specialized combat suit issued to ??? operatives.
- add: The syndicate has started issuing units under the codenames "Dark Gygax" and "Mauler" to syndicate agents at an introductory price.
- add: The exosuit fabricator can now be emagged to reveal new recipes.
- add: There are 4 new bounties cargo can fulfill for mechs. Feedback on the cost/reward is welcome!

### CODE REVIEW

**Comment by gluesniffler** [comment]
no promises on tests passing, i on the other hand am certainly about to pass out

**Comment by whateverusername0** [comment]
> no promises on tests passing, i on the other hand am certainly about to pass out

YAML LINTER :goberserk:

**Comment by gluesniffler** [comment]
> > no promises on tests passing, i on the other hand am certainly about to pass out
> 
> YAML LINTER :goberserk:

seems to be a property thats not even a datafield right now? idk im just gonna use a placeholder value for now

**Comment by BombasterDS** [comment]
I'm not sure if it was ready on wizden. Better to wait when EE will finish them.

**Comment by gluesniffler** [comment]
> I'm not sure if it was ready on wizden. Better to wait when EE finish them.

does he know chat

**Comment by Aineias1** [comment]
ME WHEN MECH WARS

**Comment by gluesniffler** [comment]
2 pirasmas test fails, and that one heisentest related to profiles, should be good to merge once the merge button havers get to play around with the PR

**Comment by Aineias1** [comment]
Cog is such a shit map, it caused checkfail for mechs

**Review by DevLonelyV1 — APPROVED** [review]
LGTM

- Pencil

**Pull request merged**
