### PR TITLE
Remove evac emag

### PR DESCRIPTION
**Pull request by Aviu00**
## About the PR

Removed shuttle emag early launch (bounty).
Now you can't unanchor or easily destroy evac shuttle thrusters so you can't get to centcomm while outside of the shuttle. (except for meta shuttle, it had weird yaml).
~You also can't unanchor arrivals or evac pods thrusters to prevent people from building shittles out of them. So you have to interact with cargo to get thrusters.~

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl: Aviu
- remove: Now emagging evac shuttle console has a 10 second do-after.
- tweak: You can't unanchor evac shuttle thrusters anymore.

### CODE REVIEW

**Comment by deltanedas** [comment]
> you can't get to centcomm while outside of the shuttle. (except for meta shuttle, it had weird yaml).

you can with crates

**Comment by TurboTrackerss14** [comment]
Could we not just reenable the hijack evac shuttle objective, and put a check in so you can only emag the console if you have that objective? 

Or give it a fairly painfully long doafter not to different from the ss13 hijack objective where you take the shuttle to the syndicate base instead.

**Comment by Aviu00** [comment]
> you can with crates

What crates?

**Comment by Aviu00** [comment]
> Or give it a fairly painfully long doafter not to different from the ss13 hijack objective where you take the shuttle to the syndicate base instead.

I'll do something like this later maybe.

It's still possible to hijack, just harder. You have to actually kill a lot of people or just do some preparations beforehand: block all docks and take over cargo. Or you can just plasmaflood the evac, for example. Your hands are free if you have this objective, you can do whatever you want, it's like second DAGD.

**Comment by JoeHammad1844** [comment]
This would make hijack objective basically impossible if you didn't set the Tesla/singulo loose

**Comment by gluesniffler** [comment]
since when do we care about "interacting with cargo" as an excuse for removing gameplay options

**Comment by deltanedas** [comment]
> > you can with crates
> 
> What crates?

crates you make with 5 steel

**Comment by JoeHammad1844** [comment]
> since when do we care about "interacting with cargo" as an excuse for removing gameplay options

wizden tier :trollface:

**Comment by Aineias1** [comment]
Mald bounty

**Comment by Ilya246** [comment]
1984 pr

> since when do we care about "interacting with cargo" as an excuse for removing gameplay options

"interacting with cargo" aka being refused by cargo because thrusters are expensive or because cargo is a ghost town (happens more often than you'd think) or because cargo just doesn't listen to you

there should be several ways to obtain any one thing and we shouldn't force "interaction" on people whether they like it or not

also i think riding evac on the outside is fine and should be kept, only reason to remove it is 1984

**Comment by JustSome1Nearby** [comment]
Noo hijack my beloved

**Comment by TurboTrackerss14** [comment]
> 1984 pr
> 
> > since when do we care about "interacting with cargo" as an excuse for removing gameplay options
> 
> "interacting with cargo" aka being refused by cargo because thrusters are expensive or because cargo is a ghost town (happens more often than you'd think) or because cargo just doesn't listen to you
> 
> there should be several ways to obtain any one thing and we shouldn't force "interaction" on people whether they like it or not
> 
> also i think riding evac on the outside is fine and should be kept, only reason to remove it is 1984

https://github.com/Goob-Station/Goob-Station/blob/d2db9b2202c019ca1cd0c62675eaa79d590489ca/Resources/Prototypes/Entities/Structures/Machines/lathe.yml#L546
Their already are several ways to obtain thrusters.

**Comment by gluesniffler** [comment]
> > 1984 pr
> > > since when do we care about "interacting with cargo" as an excuse for removing gameplay options
> > 
> > 
> > "interacting with cargo" aka being refused by cargo because thrusters are expensive or because cargo is a ghost town (happens more often than you'd think) or because cargo just doesn't listen to you
> > there should be several ways to obtain any one thing and we shouldn't force "interaction" on people whether they like it or not
> > also i think riding evac on the outside is fine and should be kept, only reason to remove it is 1984
> 
> https://github.com/Goob-Station/Goob-Station/blob/d2db9b2202c019ca1cd0c62675eaa79d590489ca/Resources/Prototypes/Entities/Structures/Machines/lathe.yml#L546
> 
> 
> There already are several ways to obtain thrusters.

woe be upon the man that expects goob science to do something useful

**Comment by TurboTrackerss14** [comment]
> woe be upon the man that expects goob science to do something useful

Curse of 30 minute rounds, i guess.

**Comment by gluesniffler** [comment]
anyway, wholly against this PR solely for the thruster unanchoring thing, hijack changes are whatever considering that the objective usually results in a clusterfuck anyway :trollface:

**Comment by JoeHammad1844** [comment]
One may be stealing 3 command cards or a hop/cap card and making two more command cards

**Comment by Aviu00** [comment]
> since when do we care about "interacting with cargo" as an excuse for removing gameplay options

You don't disassemble the house you live in. It's not a gameplay option.

**Comment by Aviu00** [comment]
But fine, if people are complaining, I'll revert thruster unanchoring.

**Comment by JoeHammad1844** [comment]
im also complaining :trollface:

**Comment by Ilya246** [comment]
removing evac emag is fine yes, expecting people to wait at evac before it actually arrives has issues

**Comment by Aineias1** [comment]
You know, i am okay with unanchorbale thrusters on ARRIVALS shuttle, this should actually be implemented

**Comment by Aineias1** [comment]
Tho i need to check if it even matters

**Comment by Ilya246** [comment]
> You know, i am okay with unanchorbale thrusters on ARRIVALS shuttle, this should actually be implemented

it doesn't need them so doesn't matter

**Comment by TurboTrackerss14** [comment]
> > You know, i am okay with unanchorbale thrusters on ARRIVALS shuttle, this should actually be implemented
> 
> it doesn't need them so doesn't matter

It's not for the shuttles need for them.. its to stop grubby handed crew stealing them for their shuttles.

**Comment by gluesniffler** [comment]
> > > You know, i am okay with unanchorbale thrusters on ARRIVALS shuttle, this should actually be implemented
> > 
> > 
> > it doesn't need them so doesn't matter
> 
> It's not for the shuttles need for them.. its to stop grubby handed crew stealing them for their shuttles.

who cares

**Review by Piras314 — CHANGES_REQUESTED** [review]
Make evac emag have a long-ish doafter instead of removing it. You should still get your bounty reward for coding removing it anyway though.

**Comment by McBosserson** [comment]
To me, emagging evac doesn't make sense. The emergency shuttle would be monitored directly by CC, and any unreasonable early launches would be delt with accordingly. The same reasons going loud on evac doesn't make sense.

I guess these points are invalid, since goob is almost nrp anyways.

**Comment by Sarahon** [comment]
This shit is abused too much. Just get rid of the emagging ability, it's nonsense.

**Comment by JoeHammad1844** [comment]
> This shit is abused too much. Just get rid of the emagging ability, it's nonsense. It rewards shitter players.

cope

**Review by Piras314 — APPROVED** [review]
LGTM

**Comment by Sarahon** [comment]
> > This shit is abused too much. Just get rid of the emagging ability, it's nonsense. It rewards shitter players.
> 
> cope

What an intelligent and thorough retort to my grievance.

**Pull request merged**
