### PR TITLE
Readding Back The Powergaming Rule

### PR DESCRIPTION
**Pull request by Verbalase**
## About the PR
Adds back the powergaming rule with some changes. 

## Why / Balance
It was removed some time ago due to a Wizden update, so I'm bringing it back before some nerd thinks it's alright to powergame.

## Requirements

- [x] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
None.

**Changelog**
:cl:
- add: Added back the powergaming rule.

### CODE REVIEW

**Comment by whateverusername0** [comment]
you forgot to add that this rule does not apply to antags :godo:

**Comment by Verbalase** [comment]
> you forgot to add that this rule does not apply to antags :godo:

Thanks.

**Comment by Aidenkrz** [comment]
This doesn't actually add it into the main rules page.

**Comment by Verbalase** [comment]
> This doesn't actually add it into the main rules page.

Shit, how can I get it to work properly then?

**Comment by Verbalase** [comment]
> This doesn't actually add it into the main rules page.

i zink i fixed it now

**Comment by Aidenkrz** [comment]
you need to make a prototype for the rule

**Comment by Verbalase** [comment]
> you need to make a prototype for the rule

okat!!!!

**Comment by Verbalase** [comment]
> you need to make a prototype for the rule

erm actually where at...

**Comment by misandrie** [comment]
This don't mean the note is valid

**Comment by Verbalase** [comment]
> This doesn't mean the note is valid :trollface:

your note isn’t counted anymore, nerd :trollface:

**Comment by Verbalase** [comment]
grabbing maggyboots to not slip

what are you, sosa? slip and die like the rest of us, maggot!!

**Comment by misandrie** [comment]
> what are you, sosa?

I spam saylogs to hide the uncuff doafter, surely

**Comment by Verbalase** [comment]
> > what are you, sosa?
> 
> I spam saylogs to hide the uncuff doafter, surely

this MIGHT be sosa⁉️⁉️⁉️⁉️

**Comment by Verbalase** [comment]
anyway @Aidenkrz where do I do prototype…

**Comment by Verbalase** [comment]
just a week away

**Comment by Verbalase** [comment]
holy shit i figured this all by myself thanks a lot durk

**Pull request merged**
