### PR TITLE
Burglar outfit 

### PR DESCRIPTION
**Pull request by InfinityPandaRed**
## About the PR

I added a burglar inspired outfit that is available in the autodrobe and for chameleon clothing
## Why / Balance

Cool sneaky outfit for thiefs and tiders
## Media

Burglar
image

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

- added burgalar bienie
- added burgalar outfit
- added burgalar mask
- added burgalar clothes to autodrobe

## Summary by CodeRabbit

- **New Features**
	- Expanded inventory for the AutoDrobeInventory vending machine with new clothing items: burglar outfit, burglar mask, and Burglar Beanie.
	- Introduced new clothing entities with unique attributes and descriptions.

- **Documentation**
	- Added metadata files for new clothing textures, providing versioning and licensing information.

### CODE REVIEW

**Comment by InfinityPandaRed** [comment]
Also if your wondering why its called burgalar, its is because i thought its a funny and cool way to spell it 

(not because i realized only until i made the pr i was misspelling burglar the whole time and now am too lazy to go back and fix it)

**Comment by Aidenkrz** [comment]
basically everything the bot said, names misspelled, prototype naming schema should be followed for IDs, all names should be in 100% lowercase

**Comment by deltanedas** [comment]
lego city based

**Comment by Piras314** [comment]
orange with black stripes would be better in my opinion but this is nice other than what durk said... you really have to fix the spelling etc.

**Comment by Verbalase** [comment]
bloat :trollface: 

aww why closed?

**Pull request closed without merging**
