### PR TITLE
Siouxcide

### PR DESCRIPTION
**Pull request by misandrie**
## About the PR

image

## Why / Balance

Maintenance of average round-to-round quality.

## Technical details

NT, BSO now have the 21 age lower limit enforced in line with other command.
Felinids are barred from playing command, have their stamina threshold reduced from 85 to 75 and lose their slow on damage advantage over other species.

## Media

image

## Requirements

- [X] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

- tweak: Lowered stamina crit threshold for felinids (85 -> 75)
- remove: Felinids lose their slow on damage advantage over other species
- fix: NT and BSO missing the minimum age threshold
- tweak: Felinids are no longer eligible for command roles

### CODE REVIEW

**Comment by a-person5660** [comment]
urm, mald PR, clearly got robusted by one too many felinid command members! 🤓

**Comment by misandrie** [comment]
> urm, mald PR, clearly got robusted by one too many felinid command members! 🤓

Felinids existed in the nyanotrasen hierarchy as victims of oni players, who were able to almost immediately grab one and abuse it. Seeing as in-universe """specieism""" (felinids are not a species) is a no-go from impressionable young players with admin buttons aspiring to make everyone sing kumbaya on the station - a mechanical approach is better here.

**Comment by packmore** [comment]
> Seeing as in-universe """specieism""" (felinids are not a species) is a no-go from impressionable young players with admin buttons aspiring to make everyone sing kumbaya on the station - a mechanical approach is better here.

specism is banned because people use it as an excuse to self-antag or put others into extremely uncomfortable/obnoxious situations without caring about roleplay. also malding about rules on a PR is lame.

**Comment by a-person5660** [comment]
seriously? your just gonna bar felinids from command without any discussion and nerf felinids in general? they were already generally worse than humans and now they are statistically worse than humans AND cant be command.

**Comment by misandrie** [comment]
> seriously? your just gonna bar felinids from command without any discussion and nerf felinids in general? they were already generally worse than humans and now they are statistically worse than humans AND cant be command.

Consider cat ears in the uplink

**Comment by a-person5660** [comment]
do i really need to explane why mechanically forced speciesism is bad

**Comment by misandrie** [comment]
> specism is banned because people use it as an excuse to self-antag or put others into extremely uncomfortable/obnoxious situations without caring about roleplay. also malding about rules on a PR is lame.

Nobody stated anything about hating due to specie. Nyanotrasen required an good motive to keep throwing a felinid player at the wall repeatedly despite mechanically being an insignificant action.

> do i really need to explain why mechanically forced speciesism is bad

Specie*s*ism against who, exactly? And what specieism exactly? You're not getting 18 year old catgirl mary sues playing blueshield, that's the entire point of it. Advantages felinids had no reason to be there in absence of onis.

**Comment by a-person5660** [comment]
why do felinids need to be nerfed? they were perfectly balanced, if anything felinids were worse than humans. i get having 18 year old cat girls as command is bad, the fix to that is making the age req 21, i dont see why we are arbritrarily barring felinids? is it because of the type of player they attract or what?

**Comment by misandrie** [comment]
> why do felinids need to be nerfed? they were perfectly balanced, if anything felinids were worse than humans. i get having 18 year old cat girls as command is bad, the fix to that is making the age req 21, i dont see why we are arbritrarily barring felinids? is it because of the type of player they attract or what?

Every single sentence here was already answered outright or in implication

**Comment by packmore** [comment]
i have no issue with keeping the minimum age for NTR and blueshield, but that change is pretty much entirely irrelevant to felinids.

**Comment by a-person5660** [comment]
> Consider cat ears in the uplink
what does this have to do with anything

> Every single sentence here was already answered outright or in implication
your answers are literally awful and illogical.

felinids are statistically worse than humans now, they worked perfectly fine before, the advantages and disadvantages were fine.

minimum age for NTR and BSO is just fine, i have no issue with that at all. 

but to also completely bar felinids from command as a whole seems completely illogical. not only is it saying that nanotrasen wont hire a specific species for their traits, why not also ban vox for needing air tanks to breathe or slimes for dying when touching water or any other thing, your banning felinids (from what i can tell) for being easy to shove and to fix this you are making them... easier to shove....

i literally cant understand your reasoning as to why this PR needs to be changed. if you have any argument other than "cat girl bad"  then please explain it.

**Comment by misandrie** [comment]
> nerfed felinids

No counterbal to their existence and changes that barely made sense. Minmaxxing felinids into a fully agility kind of specie (negative modifier on weapons, gun spread, etc) was on the table however this will cause a lot of  balance ping pong.

> * bumped up the age of NTR/blueshield

Made in line with other command staff being at 21 age minimum requirement

> * _and_ removed felinids from command entirely

Counterargument - why were they allowed there in the first place? On initial addition they had thieving which was temp removed by durk and never readded. From a design point the "specie" is not suited for command play for that and interactions with other species where its often disadvantaged and a liability.

**Comment by packmore** [comment]
> Counterargument - why were they allowed there in the first place? On initial addition they had thieving which was temp removed by durk and never readded. From a design point the "specie" is not suited for command play for that and interactions with other species (or a bag) where its often disadvantaged and a liability.

that's why you nerf the species instead of removing them from command entirely. forcing players to engage with certain roles while not being allowed to play their favorite characters/species is a really poor way of handling the issue. if they aren't fit for 'command play' (which isn't really a thing as far as i'm aware) then they're probably bad for the game in general and need some tuning.

**Comment by misandrie** [comment]
> that's why you nerf the species instead of removing them from command entirely.

LOOC: HoS McMetaPowerGamer: >Felinid captain okay gg I cryo

**Comment by packmore** [comment]
just to be clear, i am fine with the nerf, just not the idea of nerfing them _and_ banning them from command. the nerf feels like it fixes the issue, banning them from command just seems really bizarre and poorly thought out.

**Comment by a-person5660** [comment]
> > that's why you nerf the species instead of removing them from command entirely.
> 
> LOOC: HoS McMetaPowerGamer: >Felinid captain LOOC: HoS McMetaPowerGamer: okay gg I cryo

are you trying to say that the hos is cryoing because they think that a felinid captain is bad and is going to die or what? i literally have no fucking idea what you are trying to convey here.

**Comment by misandrie** [comment]
> just to be clear, i am fine with the nerf, just not the idea of nerfing them _and_ banning them from command. the nerf feels like it fixes the issue, banning them from command just seems really bizarre and poorly thought out.

The nerfs are either to reel them back with the rest (slowondamage buff revert) or make them relevant with the stamina damage value changes over the last 18 months (85->75).

Their haha funny silent step (a defining feature together with thieving, which is up to @Aidenkrz) is kept as-is else it would be a worse human.

Current disadvantages are good enough for thieving to be reintegrated with the species to counterbalance the nerf, however things like getting owned by a duffel bag are not traits permissible to round-critical positions. Either completely redesign felinids from the ground up instead of relying on ancient nyano concepts with missing parts that interact with them, make it a direct boring reskin of humans (thus killing the novelty of cat ears off uplink).

**Comment by Aidenkrz** [comment]
I'm going to shut down this conversation because you guys are falling for ragebait and its stupid.
I merged it because **its funny** and it was intended to be a thing since i first added felinids, but just wasnt possible to exist until around a week ago.

**Comment by misandrie** [comment]
Its fundamentally over

**Pull request merged**
