### PR TITLE
Crew, i swear im not rogue

### PR DESCRIPTION
**Pull request by Vlax2nd**
## About the PR
malf ai from the hit game space station 13

## Why / Balance
say it, say it, say it
spaceship universe
U-S-A

## Technical details
not yet

## Media
later

## Requirements

- [X] I have NOT read and am NOT following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have NOT added media to this PR or it does not require an ingame showcase.

## Breaking changes
this is a shittest which WILL break (or not, i have no idea)

**Changelog**

:cl:
- add: malf ai is here, currently only activated with antimov

### CODE REVIEW

**Comment by Vlax2nd** [comment]
i have menaged to already break it by making the admin antag menu crash the game due to the invalid "MalfunctionalAi" entity protoype

**Comment by GroggleG** [comment]
its SPACESHIP UNIVERSE not fucking spaceship noodle

**Comment by JoeHammad1844** [comment]
detonate RCD real

**Comment by JoeHammad1844** [comment]
https://www.youtube.com/watch?v=J3HubVyNYrs

**Comment by Vlax2nd** [comment]
how to github 101

**Comment by Aidenkrz** [comment]
looks like it hasnt been touched since it was originally PRd, feel free to reopen when you start working on it again.

**Comment by deltanedas** [comment]
malf fell off

**Comment by Vlax2nd** [comment]
as much as i would like to finish this i simply dont know how
tried making abilities use charges, dont know how
maybe i will continue to work on this when i will know ss14 coding more but for now making flockmind antag sounds easier

**Comment by a-person5660** [comment]
> as much as i would like to finish this i simply dont know how tried making abilities use charges, dont know how maybe i will continue to work on this when i will know ss14 coding more but for now making flockmind antag sounds easier

Look at how ling chemicals work, a system similar to that would be cool.

**Comment by Vlax2nd** [comment]
> Look at how ling chemicals work, a system similar to that would be cool.

the APC hijacking and store systems already work, you get 15 points per APC and you cant hijack that APC again
i wanted to make the machine overload get 2 charges per purchase, the ability is displaying 2/2 charges but they dont decrease, same with RCD overload

**Comment by Fat-Engineer-Gaming** [comment]
ermm accually is
One, two...
Say it, say it, say it
Spell... Spaceship universe
U-S-A
Correct!
But seriously though i can't wait for this to be finished AHHH

**Pull request closed without merging**
