### PR TITLE
Update job-description.ftl / change assistant hover-text to prevent s…

### PR DESCRIPTION
**Pull request by Pologuys**
…elfantag

Changes passenger/assistant job description to something that prevents self-antag

## About the PR

Change assistant flavor/hover-text in the lobby.
## Why / Balance

Prevents self-antag because you listened to the game. (If you're an admin, read this link; https://discord.com/channels/1202734573247795300/1203113931422568488/1299076770649083904)
## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

- tweak: Changed the assistant job hover text description, nosugarplumnovember was here!

## Summary by CodeRabbit

- **New Features**
	- Updated the job description for the "passenger" role to emphasize collaboration and exploration within the station.
	- Revised description now encourages assisting other departments rather than focusing on negative outcomes.

### CODE REVIEW

**Comment by JoeHammad1844** [comment]
sovl destroyed

**Comment by whateverusername0** [comment]
sovl destroyed

**Comment by whateverusername0** [comment]
better do sth like "Get your space legs, ask HoP for a job, become the maintenance's next legend"

**Comment by whateverusername0** [comment]
also idk how is job description encouraging self antag.
the fact that most assistants break into places to tide shit is engraved in their descriptions, there's nothing wrong in it

**Comment by Pologuys** [comment]
> also idk how is job description encouraging self antag. the fact that most assistants break into places to tide shit is engraved in their descriptions, there's nothing wrong in it

become staff and see the link 🤫 
join our secret society

**Comment by JoeHammad1844** [comment]
how about "slip security officers, get abused by everyone and die in maints"

**Review by Piras314 — APPROVED** [review]

**Pull request merged**
