### PR TITLE
Make Meth Explosive!

### PR DESCRIPTION
**Pull request by Speebr0**
## About the PR
Meth will now explode when heated to 420K, with a small area of effect that destroys adjacent machines.

## Why / Balance
Adds some danger/excitement to chem, and more pyrotechnics options.
An attentive chemist will take their meth off the hotplate when it finishes cooking without any issue,
the inattentive chemist or one that uses ChemMaster temperature jank will have their meth explode in their face

Considering the SS13 equivalent happens at only 10K above it's creation temperature, this is significantly more lenient

## Technical details
- New explosion type that deals mainly blunt damage, will allow tweaking of tile destruction if someone makes the explosion more powerful
- Heating Desoxyephedrine to 420K will make it explode strong enough to take out directly adjacent machines

**Changelog**

:cl:
- tweak: Desoxyephedrine, aka METH, now explodes at 420K, 50K above the temperature it is made at.

### CODE REVIEW

**Comment by BombasterDS** [comment]
Reagent temperature works really bad right now. You can heat up beaker with 10000K for a seconds and it'll save temperature even without any reagent in it. I think it'll just randomly explode sometimes without real chances to control it.

**Comment by Speebr0** [comment]
I believe it's only the chemmaster that "retains" the temperatures of the reagents when adding anything.

The chem dispenser and sinks likely output at room temp, 293K, and mixing chems in containers probably evens out the energy?
It might be a bit more screwy than I know, but I suppose I should check it out

**Comment by deltanedas** [comment]
lavabeaker is exclusive to chemmaster yes

**Comment by Speebr0** [comment]
fortunately/unfortunately, depending on your stance, you can still bulk-produce desoxy in the chemmaster as it does not change the temperature, so you only have to wait for it to heat once.

**Comment by Piras314** [comment]
eh it's funny

**Pull request merged**
