### PR TITLE
More drinks for bar!

### PR DESCRIPTION
**Pull request by Tonk-GCR**
## About the PR

Five more drinks: Gin and Sonic, Golden Cat, Pineapple Blast, Torpedo Juice and Bees Knees. (credit to ray-boop)
## Why / Balance

Alcoholism
## Technical details

Added drink files to goob files
## Media

New drinks below the sigmajuice (goob special).
YIPPEE

## Requirements

- [X ] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [ X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

None (hopefully)
**Changelog**

:cl: ray-boop and Tonk
- add: Added a set of new drinks for bartenders to mix: Gin and Sonic, Golden Cat, Pineapple Blast, Torpedo Juice and the Bee's Knees.

### CODE REVIEW

**Comment by Tonk-GCR** [comment]
@coderabbitai full review

**Review by Piras314 — COMMENTED** [review]
This is from Frontier, right?

**Comment by Tonk-GCR** [comment]
> This is from Frontier, right?

Yeah its from Frontier, here's the PR https://github.com/new-frontiers-14/frontier-station-14/pull/1662

**Review by Piras314 — COMMENTED** [review]
Can you replace the media with a screenshot of it working in goob?

**Comment by Tonk-GCR** [comment]
> Can you replace the media with a screenshot of it working in goob?

Done (dont  ask how it took me an hour lmao)

**Comment by ray-boop** [comment]
have fun exploding ^^

**Pull request merged**
