### PR TITLE
Weapons for command and contractor baton for traitors

### PR DESCRIPTION
**Pull request by Aviu00**
## About the PR

Ported and reworked [this](https://github.com/Simple-Station/Einstein-Engines/pull/1144).
Telebaton was given to all command members except for hos and bso. It knocks down people with 4 second cooldown, by default it doesn't force to drop items but if you hit a person immediately after extending it, it does.
Added contractor baton for traitors (bounty), a stronger telebaton that deals a lot of stamina damage, stuns borgs, has lower cooldown and always forces to drop items (if the person is standing). Cost - 35tc.
Captain now starts with n1984 pistol, its accuracy buffed.
Mateba firerate buffed so it's better than n1984.
Bso now starts with atreides, its accuracy nerfed so it's no longer a direct upgrade to c20-r.
Removed lifeline implanter from bso, why the hell does he have it, crew shouldn't have acidifiers.

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl: Aviu
- add: Telebaton for command.
- add: Contractor baton for traitors.
- add: Captain now has n1984 pistol.
- tweak: N1984 accuracy buffed.
- add: Bso now has atreides.
- tweak: Atreides accuracy nerfed.
- tweak: Mateba firerate increased: 3 -> 5.
- remove: Removed bluespace lifeline implanter from bso.

### CODE REVIEW

**Comment by starch70** [comment]
this is tider racism

**Comment by SolsticeOfTheWinter** [comment]
every other change here is GREAT but the removal of BSOs lifeline

**Comment by Aviu00** [comment]
> every other change here is GREAT but the removal of BSOs lifeline is terrible imo. The whole point is that BSO has super strong gear and works for centcomm, so he'd have better implants and weaponry etc. This would make BSO a pinata

If bso gets killed and looted, then it's a skill issue, and skill issues should be punished. And also bso now can actually be revived.

**Comment by Aviu00** [comment]
And also bso can be a target for heretic sacrifice (impossible with lifeline implanter).

**Comment by SolsticeOfTheWinter** [comment]
I'm not very keen on the idea of the whole crew being punished because one person downed the BSO. This is exactly why cadets got their pistols removed. 
Keep in mind that in the _same_ update you are adding a baton which can stun people comedically quickly. These changes combined turn it bso into a walking pinata unless they stay next to the captain 24/7

**Comment by Aidenkrz** [comment]
> Telebaton was given to all command members except for hos and bso. It knocks down people with 4 second cooldown, by default it doesn't force to drop items but if you hit a person immediately after extending it, it does.

What? In what fucking world does a one hit instant stun sound fair?

> Removed lifeline implanter from bso, why the hell does he have it, crew shouldn't have acidifiers.

Because he isn't crew, he is centcomm, basically a permenant ERT.

**Comment by lanse12** [comment]
it's not even stun it's knockdown and you can't inf stun people

**Comment by Aviu00** [comment]
> What? In what fucking world does a one hit instant stun sound fair?

It knocks down, not stuns. Telebaton deals almost no stamina damage, contractor baton deals 85, which means it 1 hit stuns felinids only.

> Because he isn't crew, he is centcomm, basically a permenant ERT.

Ok, brought it back.

**Comment by Aidenkrz** [comment]
> > What? In what fucking world does a one hit instant stun sound fair?
> 
> It knocks down, not stuns. Telebaton deals almost no stamina damage, contractor baton deals 85, which means it 1 hit stuns felinids only.
> 
> > Because he isn't crew, he is centcomm, basically a permenant ERT.
> 
> Ok, brought it back.

oh okay, I'm cool with this then

**Pull request merged**
