### PR TITLE
Frictionfull Space.

### PR DESCRIPTION
**Pull request by Aidenkrz**
## About the PR
Gives ATS and the station a minor amount of friction, meaning cargo techs bumping into them no longer sends them into the void. Mirror of https://github.com/Simple-Station/Einstein-Engines/pull/514

## Why / Balance
See above

## Technical details
See original PR.

**Changelog**
:cl:
- tweak: The station and ATS now have a minor amount of friction.

### CODE REVIEW

**Comment by RealFakeSoof** [comment]
PEAK

**Comment by Verbalase** [comment]
we’re so back

**Comment by whateverusername0** [comment]
peak, merge now

**Comment by VMSolidus** [comment]
I can't believe y'all have somehow went an entire month with your cargo techs basically not being able to play the game LMAO.

**Pull request merged**
