### PR TITLE
the great rename

### PR DESCRIPTION
**Pull request by Piras314**
## About the PR

renamed all Goobstation folders to _Goobstation, and renamed the Goobstation namespace to the _Goobstation namespace because of some xml ui guidebook shitcode

## Why / Balance

this is because _ will show up first, meaning you don't have to scroll a bunch to find the goob folder.

## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

this will break a lot of current PRs, but in a way that's very very easy to fix.

**Changelog**

no cl no fun

## Summary by CodeRabbit

- **New Features**
	- Updated sound file paths for various components, enhancing audio consistency.
  
- **Bug Fixes**
	- Corrected namespace declarations across multiple components and systems for better organization.

- **Chores**
	- Restructured directory paths for improved code management without affecting functionality.

### CODE REVIEW

**Comment by Piras314** [comment]
@coderabbitai don't review this pr

**Comment by JoeHammad1844** [comment]
i dont think the risk of breaking a ton of stuff is worth not having to scroll down a little bit

**Comment by whateverusername0** [comment]
you should merge it NOW

**Review by whateverusername0 — APPROVED** [review]
my browser is lagging from the amount of files god let's just handle future errors after it gets merged i can't possibly review it all

**Comment by Aidenkrz** [comment]
you forgot deltav and nyano

**Comment by Piras314** [comment]
I won't rename delta and nyano's folders for them so it's easier to cherry-pick

**Pull request merged**
