### PR TITLE
HERETIC QUICKFIX (URGENT)

### PR DESCRIPTION
**Pull request by whateverusername0**
## About the PR

i could not forsee heretic ascensions not giving needed perks
oh well!!

🆑 
- fix: Fixed ascensions not giving out items properly.

### CODE REVIEW

**Comment by whateverusername0** [comment]
hold on... wtf

**Comment by whateverusername0** [comment]
waiting for checks to pass and then do fuckall

**Comment by Aineias1** [comment]
Me when selfmergr

**Comment by starch70** [comment]
Fuck the checks. Merge it now. Better idea; automatically mark every maintainer PR as approved like wizden.

**Comment by whateverusername0** [comment]
> Me when selfmergr

it was durk... :trollface: 
anyways IM FIXING IT NOW because heretics without ascensions are NOT BROKEN ENOUGH

**Comment by whateverusername0** [comment]
image

unrelated check fails...

**Pull request merged**
