### PR TITLE
Re-add The "Throngler" to The Grand Lottery

### PR DESCRIPTION
**Pull request by Scruq445**
## About the PR

Added a Special Throngler-Based Toy to the Grand Lottery lootpool.
## Why / Balance

Because Lord Throng told me to.
## Media

[](https://github.com/user-attachments/assets/653b16ba-f1b7-465b-bde7-3148d00efce9)

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: Readded The Throngler to The Grand Lottery

### CODE REVIEW

**Comment by Piras314** [comment]
check the checks.

Also, the thing about the Throngler is it's just a mass murdering tool and self antag isn't allowed even if you have a throngler so... it's not great

**Comment by Scruq445** [comment]
wtf that's weird now it's reading the old foam throng from the goobstation folder. lemme remove it.

**Comment by Scruq445** [comment]
also damn git for not removing the lines from the goobstation toys.yml

**Comment by Scruq445** [comment]
oh thanks for removing it for me

**Comment by lanse12** [comment]
swings too slow

**Comment by Piras314** [comment]
check the checks still please

**Comment by Scruq445** [comment]
Problem is that SS14 is not reading entities from Goonstation/Entities/Objects/Fun

**Comment by Urufusan** [comment]
> check the checks still please
image
lgtm

**Comment by Scruq445** [comment]
orrrr it'll start reading the files now, PR Completed

**Comment by Scruq445** [comment]
image
image

It's an image of the throngler printed on a foam cut-out like the Foam Cutlass.

**Comment by Aidenkrz** [comment]
gotcha

**Pull request merged**
