### PR TITLE
Fixing my eyes

### PR DESCRIPTION
**Pull request by GitHubUser53123**
## About the PR
Blueshield's drip updated
## Why / Balance
The blue jumpsuit was fucking shit, so I replaced it with NT cloak and NT jumpsuit

## Technical details
No.

image

>Fix this shit
>Perfect
image

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
No.

**Changelog**
Changed blueshield's jumpsuit to be Nanotrasen Jumpsuit. Also added NanoTrasen cloak.

### CODE REVIEW

**Comment by Verbalase** [comment]
Yeah, I like this one more tbh.

**Comment by Aidenkrz** [comment]
mr guy backpacks are missing from them now, fix it !!!

**Comment by GitHubUser53123** [comment]
FUCKING RAHHHH

**Comment by GitHubUser53123** [comment]
not my problem btw i didnt cause it:3

**Comment by Aidenkrz** [comment]
yeah i already fixed it

**Pull request merged**
