### PR TITLE
Chrono Legionnaire

### PR DESCRIPTION
**Pull request by BombasterDS**
## About the PR
Adds Chrono Legionnaire, almost invincible time warrior who destroys living anomalies in time.

Resolves: #294 

### Stasis
Stasis is a state in which an entity cannot interact with the world in any way, and the world cannot interact with that entity either. In addition, an entity in stasis will not take any damage, making it completely safe from other entities. (The entity can still be removed by something like the singularity)

Stasis can be applied on target in two ways:
- Stasis gun - ranged weapon that will try apply stasis on anyone it hits (stasis lasts one minute). Required stasis storage (chrono legionnaire backpack) to shot. If it was thrown or wearer was disarmed it will return on the belt slot or in user hands (works only if wearer stasis immune).
- Stasis container - container that tries apply stasis on anyone who inside it. If you open container stasis effect will disappear immediately. Have medium size and 2x2 grid, so you can place in backpack. Can be used to move targets through the maps when you admin.

Stasis immunity can be obtained with special equipment (e.g. future hardsuit). While wearing the equipment, the user will not be able to be placed in stasis by any means, but will be able to interact with players in stasis.  

https://github.com/user-attachments/assets/d9efe514-a7a0-41bf-854e-d5f9fdf856cf
 
### Timeline Disruptor 

Device flatpack of which spawns in chrono legionnaire backpack. Can be packed back into flatpack with screwdriver.

The main function of the device is to remove entities from the round by erasing them. To do this, it is necessary to catch an entity in stasis container then put in on timeline device. After click on it starts process of disrupting. It can be stopped just by removing container from device. If crew will get device's flatpack they can sell it for 1500 spesos.

https://github.com/user-attachments/assets/af79bb8a-cc36-4361-bf0b-6f36042fd6b0

### Stasizium

Stasizium is new medicine reagent. It heals all types of damage and rotting. Works even on dead bodies and don't require specific temperature. Overdose (>21u) makes enormous blunt damage to body that will gib body in the end.

Not craftable, but can be found in new futuristic medipen (10u) that will spawn in chrono legionnaire backpack.

https://github.com/user-attachments/assets/65d18c4c-681e-4bf9-95fd-a089d09031ab

### Chrono Legionnaire equipment

Because it's admeme job, all equipment will be overpowered like hell. To make yourself Chrono Legionnaire just set your outfit with ChronoLegionnaireGear. Almost all equipment is unremoveable, so crew won't be able to use this staff if you won't give it to them yourself.

**Clothing:**

- Futuristic hardsuit gives you 95% damage reduction to all types damage in game (excluding damage made by reagents). Helmet also give you additional 90% damage reduction (97.75% if calculated right) and gives you half life 2 combine speech effect. In additional it boosts your stamina and stamina regeneration 10 times, so it won't be easy to stamina crit you. And also it gives you teleport ability, so you hunt your target everywhere on station. Main disadvantage - it decrease speed to 30%.
- Futuristic boots - advanced magboots with cool heavy steps sound
- Futuristic gloves - insulated and fingerprintsless gloves.
- Futuristic gasmask - gives you additional 5% damage reduction and voice changer in it
- Futuristic visor - omnihud.
- Futuristic headset - headset with every radio in it (including Handheld, Freelance and Syndicate, but not changeling).
- Futuristic jetpack - jetpack with extreme gas volume. It takes 1/4 of canitser to refill it. Uses as gas tank.
- Futuristic PDA with futuristic ID card and pen - admin PDA with all access id card in it (including CC and Syndicate access). ID card have special job icon on huds and Future Agent job title. Pen does nothing (real).

**Tools:**
- Sonic screwdriver - compact omnitool
- Futuristic RCD - RCD with 100 regenerating charges
- Futuristic stunbaton - stunbaton with 50 stun damage
- Futuristic teleporter - just RD teleporter with new sprite

image

- [X] I have added screenshots/videos to this PR showcasing its changes ingame

**Changelog**

:cl:
- add: ChronoLegionnaire was added as admeme tool

### CODE REVIEW

**Comment by whateverusername0** [comment]
HOLY SHIT MERGE NOW

**Comment by Piras314** [comment]
read the checks please

**Comment by BombasterDS** [comment]
> read the checks please

fixed

**Comment by GitHubUser53123** [comment]
holy shit

**Comment by Aidenkrz** [comment]
Genuinely based as hell, beat me to it and put in way more effort than I was going to. Good shit.

**Review by Aidenkrz — APPROVED** [review]

**Pull request merged**
