### PR TITLE
Sec Hardsuit resprite

### PR DESCRIPTION
**Pull request by InfinityPandaRed**
## About the PR

resprited the security hardsuit. the new look is a combination of the wizden sec hardsuit and the current goob station hardsuit. the hardsuit has the basic form of the wizden suit but with the color palate and extra elements of goob station suits. 

## Why / Balance

I just thought that the look of the basic sec hardsuit look strange. i think this version suits sec better

## Media

sec hardsuit

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

- resprited sec hardsuit
- resprited sec hardsuit helmet

## Summary by CodeRabbit

- **New Features**
	- Updated copyright information for security hardsuit textures, providing clearer attribution to the sprite creators.
- **Bug Fixes**
	- Corrected attributions in the metadata for both the head and outer clothing hardsuits to reflect the latest contributions and redesigns.

### CODE REVIEW

**Comment by BombasterDS** [comment]
check failure seems unrelated

**Comment by InfinityPandaRed** [comment]
> check failure seems unrelated

i dunno why is it showing failure i didn't remove any script

**Comment by GroggleG** [comment]
Dark Samus, no way.

**Comment by BombasterDS** [comment]
> > check failure seems unrelated
> 
> i dunno why is it showing failure i didn't remove any script

not your fault, check failure unrelated to this pr

**Review by whateverusername0 — APPROVED** [review]

**Pull request merged**
