### PR TITLE
chud minor changes

### PR DESCRIPTION
**Pull request by starch70**
## About the PR
spears are now large size instead of giant
secoffs favorite reasons to arrest tiders (mesons, combat gloves, boots) are no longer contra (combat gloves are just reskinned insuls lol, you can buy them irl for like $50 on amazon too, no reason for it to be contra)

## Why / Balance
Many annoying secoffs arrest instantly over minor shit like your OH SO EVIL AND HORRENDOUS RECOLORED INSULS
You can buy this highly illegal contra on amazon for like $50-$100

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl: Yakub
- tweak: Engineering goggles are renamed to meson goggles.
- tweak: Combat gloves, combat boots, jackboots, and mesons are no longer contraband.
- tweak: Spears fit in backpacks now.
- tweak: Mini jetpacks are actually smaller than jetpacks in inventory now.

### CODE REVIEW

**Comment by Plyushsune** [comment]
Is this a mald pr?

**Comment by starch70** [comment]
> Is this a mald pr?

its a tide PR

**Comment by TurboTrackerss14** [comment]
Holy mald pr batman. 

Just PR the removal of the contraband system entirely if you are this assmad about getting your ill begotten gear taken from you.

**Comment by Plyushsune** [comment]
> Holy mald pr batman.
> 
> Just PR the removal of the contraband system entirely if you are this assmad about getting your ill begotten gear taken from you.

Holy shit that is the biggest wizden response i seen in a year

**Review by Piras314 — APPROVED** [review]
To be fair, you have to have a very high IQ to understand Rick and Morty. The humor is extremely subtle, and without a solid grasp of theoretical physics most of the jokes will go over a typical viewer's head. There's also Rick's nihilistic outlook, which is deftly woven into his characterisation - his personal philosophy draws heavily from Narodnaya Volya literature, for instance. The fans understand this stuff; they have the intellectual capacity to truly appreciate the depths of these jokes, to realize that they're not just funny- they say something deep about LIFE. As a consequence people who dislike Rick and Morty truly ARE idiots- of course they wouldn't appreciate, for instance, the humour in Rick's existencial catchphrase "Wubba Lubba Dub Dub," which itself is a cryptic reference to Turgenev's Russian epic Fathers and Sons I'm smirking right now just imagining one of those addlepated simpletons scratching their heads in confusion as Dan Harmon's genius unfolds itself on their television screens. What fools... how I pity them. 😂 And yes by the way, I DO have a Rick and Morty tattoo. And no, you cannot see it. It's for the ladies' eyes only- And even they have to demonstrate that they're within 5 IQ points of my own (preferably lower) beforehand.

**Comment by starch70** [comment]
> Holy mald pr batman.
> 
> Just PR the removal of the contraband system entirely if you are this assmad about getting your ill begotten gear taken from you.

Yes i actually own some shitty $20 airsoft fake combat gloves irl so next time i get seen by a police officer while im wearing them im gonna get beaten and thrown in jail for possesion charges

**Comment by Piras314** [comment]
trvth nvke

**Comment by TurboTrackerss14** [comment]
Do your knockoff fake combat gloves provide protection from shocks and heat?
Do your knockoff jays offer slowdown reduction from damage? (something that was given as a secbuff) 
Do your knockoff timbs offer stuntime reduction? (same as above)

Also if we are gunna make muh realism arguments, Please show me a picture of you fitting multiple body length spears into a backpack.

**Comment by whateverusername0** [comment]
> Holy mald pr batman.
> 
> Just PR the removal of the contraband system entirely if you are this assmad about getting your ill begotten gear taken from you.

wizmaint in chat everyoen scram

**Comment by githubuser4141** [comment]
> > Holy mald pr batman.
> > Just PR the removal of the contraband system entirely if you are this assmad about getting your ill begotten gear taken from you.
> 
> Yes i actually own some shitty $20 airsoft fake combat gloves irl so next time i get seen by a police officer while im wearing them im gonna get beaten and thrown in jail for possesion charges

well to be fair you can buy a lot of ss13 contra legally, guns depending on where you live, armor and NVGs are legal in many places even NZ, syndie toolbox or tools are just higher quality variants of the NT ones, aside from things like biological weapons there's probably very few things in the uplink that are outright illegal *everywhere*, i guess it depends on where you live

**Comment by starch70** [comment]
> Do your knockoff fake combat gloves provide protection from shocks and heat? Do your knockoff jays offer slowdown reduction from damage? (something that was given as a secbuff) Do your knockoff timbs offer stuntime reduction? (same as above)
> 
> Also if we are gunna make muh realism arguments, Please show me a picture of you fitting multiple body length spears into a backpack.

ok so you can put 2 shotguns and a GPMG in your bag but not spears

also i dont know why u guys are fighting so hard to prevent my tider phalanx from happening with spears or why u guys wanna keep combat gloves as contra so damn bad

**Pull request merged**
