### PR TITLE
Last Call (New nuke song)

### PR DESCRIPTION
**Pull request by Piras314**
## About the PR

This PR adds Last Call, a new nuke song made by mryikes / he1acdvv with permission.

https://www.youtube.com/watch?v=r29OdkQRYbg

[wizden PR](https://github.com/space-wizards/space-station-14/pull/30047)

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl: mryikes
- add: A new nuke song, Last Call has been added!

### CODE REVIEW

**Comment by Aidenkrz** [comment]
Lets stop trying to add PRs that are still open on upstream, its dumb and will cause more issues than its worth if it gets merged.

**Comment by Verbalase** [comment]
exactly man :trollface:

**Comment by Piras314** [comment]
I called it https://github.com/space-wizards/space-station-14/pull/30047

**Comment by he1acdvv** [comment]
the freeze is real........

**Comment by Piras314** [comment]
@Aidenkrz

**Pull request merged**
