### PR TITLE
flamethrower

### PR DESCRIPTION
**Pull request by toasterpm87**
## About the PR

add flamethrower because i was watching "The thing" by john carpenter and thought that would be an awesome weapon to murder fellow spessman with
## Why / Balance

flamethrower that should not instantly incinerate things 
## Requirements

- [ ] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [ ] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

### CODE REVIEW

**Comment by Aidenkrz** [comment]
uh yeah spraying incendiary bullets as "fire" is dumb, it should actually spray reagents like the spray gun thing.
Now that I think about it, isn't it highly likely that RMC already has a flamethrower? should probably check for that.

**Comment by toasterpm87** [comment]
> uh yeah spraying incendiary bullets as "fire" is dumb, it should actually spray reagents like the spray gun thing. Now that I think about it, isn't it highly likely that RMC already has a flamethrower? should probably check for that.

God bless the rmc/j
Anyways I haven't been able to test it, im still trying to get the prototype to work correctly. 
I look at rmc code in a bit

**Comment by toasterpm87** [comment]
Also if it spraying dragons breath doesn't work then I just base it off the incinerator from fallout

**Comment by JoeHammad1844** [comment]
Try out how 13 does it and have it spray out gasses and ignite them

**Comment by Aineias1** [comment]
> Try out how 13 does it and have it spray out gasses and ignite them

I am certain that it's kind of bad. I remember white dream they had flamethrower like this, and it always caused lots of people who weren't even set on fire, dying and ashing from the temperature

**Comment by toasterpm87** [comment]
> > Try out how 13 does it and have it spray out gasses and ignite them
> 
> I am certain that it's kind of bad. I remember white dream they had flamethrower like this, and it always caused lots of people who weren't even set on fire, dying and ashing from the temperature

I think the shotgun route might work then

**Comment by toasterpm87** [comment]
im gonna close this because i want to work on things

**Pull request closed without merging**
