### PR TITLE
fixing Fland engineering for the 63th time (AI Edition)

### PR DESCRIPTION
**Pull request by BombasterDS**
## About the PR
Updated Fland:
- Reduced number of SM spaghetti pipes
- TEG moved to previous location
- Reduced size of cooler loop under SM to fix gases pressure lock
- Connected AME and SM to SMESes, not directly to station power
- Added tesla room right of SM
- Maints hallway right of tesla room reduced

## Why / Balance
Remove Fland means no power round (real)

## Media
image
image
image

## Summary by CodeRabbit

- **New Features**
	- Introduced a new job role, `StationAi`, expanding the list of available jobs for users in the application.

### CODE REVIEW

**Comment by Piras314** [comment]
1. add the teg back if you can I like tegs
2. you have to maintain this map if we're modifying it because we won't be able to get upstream changes
@BombasterDS

**Comment by BombasterDS** [comment]
> 1. add the teg back if you can I like tegs
> 2. you have to maintain this map if we're modifying it because we won't be able to get upstream changes
>    @BombasterDS

1. I'll try to add teg somewhere in atmos.
2. I can do it, it doesn't take much time.

**Comment by Piras314** [comment]
@BombasterDS failed check is related btw

**Comment by whateverusername0** [comment]
tesla near SM might not be a smart move

**Comment by BombasterDS** [comment]
> tesla near SM might not be a smart move

i left it for 40 minutes with invincible tesla coils. It won't lose and SM was fine.

**Comment by BombasterDS** [comment]
> tesla near SM might not be a smart move

Still, tesla loose means round end and SM loose means round end because it spawn tesla, so...

**Comment by BombasterDS** [comment]
> @BombasterDS failed check is related btw

last fail check seems unrelated

**Comment by BombasterDS** [comment]
it just fixed itself xdxd

**Comment by Piras314** [comment]
I re-ran it cause it was unrelated :)

**Comment by whateverusername0** [comment]
if you actually fixed all the wiring this is golden
still i don't like the tesla setup

**Review by whateverusername0 — APPROVED** [review]

**Pull request merged**
