### PR TITLE
Assultborg bug fix

### PR DESCRIPTION
**Pull request by jorgun**
## About the PR

replaces assultboirgs double energysword whit a  normal e -sword

## Why / Balance

sword is bugged

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- tweak: Syndicate Assult borg now has a one handed e-sword

### CODE REVIEW

**Comment by a-person5660** [comment]
Why not just fix the desword bug or make a unique esword for borgs with the same stats as the desword, a lot of borg modules already have unique versions of items so it wouldn't be shitcode.

**Comment by jorgun** [comment]
the diference between the swords. was mostly for the defensive.
                E Sword           DE-sword
damage        30                  24
attack rate     1                    1.5
reflect           25%                 75%
i tryed making this whit adding to the borgs armor but that one got denied, so now im trying whit just swaping the nonfunctional blade for a functional one

**Comment by Aidenkrz** [comment]
Add comments.

**Comment by a-person5660** [comment]
> the diference between the swords. was mostly for the defensive. E Sword DE-sword damage 30 24 attack rate 1 1.5 reflect 25% 75% i tryed making this whit adding to the borgs armor but that one got denied, so now im trying whit just swaping the nonfunctional blade for a functional one

This would effectively be a nerf, can't you just fix the bug with the original desword or as I said earlier, make a borg unique esword and just copy the desword stats, maybe name it something unique and it could be reused in the future.

**Comment by jorgun** [comment]
added a custom sword. please dont give somone 2 off these sword as it basecly give them 2x 75% reflect, makign them bullerproof.

**Comment by a-person5660** [comment]
> added a custom sword. please dont give somone 2 off these sword as it basecly give them 2x 75% reflect, makign them [bulletproof](https://www.youtube.com/watch?v=Kk8eJh4i8Lo).

I'm pretty sure reflect chance is capped now anyway so two swords wouldn't help.

**Comment by jorgun** [comment]
> > added a custom sword. please dont give somone 2 off these sword as it basecly give them 2x 75% reflect, makign them [bulletproof](https://www.youtube.com/watch?v=Kk8eJh4i8Lo).
> 
> I'm pretty sure reflect chance is capped now anyway so two swords wouldn't help.

tested whit a L6, dumped a full magazine, 2 bullets hit

**Comment by a-person5660** [comment]
This is no longer needed as there is a pr upstream to fix the bug [https://github.com/space-wizards/space-station-14/pull/30229](#30329)

**Comment by jorgun** [comment]
> This is no longer needed as there is a pr upstream [here](https://github.com/space-wizards/space-station-14/pull/30229)

**Pull request closed without merging**
