### PR TITLE
Bits Over

### PR DESCRIPTION
**Pull request by Aidenkrz**
## Why / Balance

Most of these changes were just one day bits.

The felinid change was also a social experiment. I want all of you to know you failed miserably. Every single one of you who decided that your 32x32 pixel sprite of an anime cat girl not being allowed to play as captain on a space station is equivalent to real-life racism needs a serious reality check.

**Changelog**
:cl:
- remove: Removed fun.

### CODE REVIEW

**Comment by ARMOKS** [comment]
Can we at least keep them as grimlins

**Comment by gluesniffler** [comment]
its so joever tidebros

**Comment by Ilya246** [comment]
should've added "Sincerely, [your name]" to end of PR description

**Comment by Aineias1** [comment]
fakest apology ever

**Comment by cherubdev** [comment]
coward

**Pull request merged**
