### PR TITLE
Changelings playtest

### LINKED ISSUE #289: Changelings
cling in maints!!!!
https://paradisestation.org/wiki/index.php?title=Changeling

### PR DESCRIPTION
**Pull request by whateverusername0**
## About the PR

title
need to playtest it on a real server (real) to make further changes
resolves #289 

## Why / Balance

it's changelings !!!

## Technical details

a lot of shittery, ik it needs a lot of refactors but it just works and it's a playtest so whatever

:cl:
- add: Added changelings.

### CODE REVIEW

**Comment by whateverusername0** [comment]
ignore the RSI validator check it's for the animated armblade which doesn't work. so it's just there.

**Comment by Verbalase** [comment]
all zem checks need ta be checked

**Comment by Verbalase** [comment]
> all zem checks need ta be checked

zevermind

**Review by jorgun — APPROVED** [review]
tested and it worked. 
made 2 pr for some changes i wanted

**Comment by a-person5660** [comment]
10:1 crew to changelings seems like a few too many changelings imo, especially on goob where sec is non existant and unrobust.

**Comment by whateverusername0** [comment]
> 10:1 crew to changelings seems like a few too many changelings imo, especially on goob where sec is non existant and unrobust.

i'll make it 15:1 after the playtest, i just need to see how lings would integrate into society :trollface:

**Comment by a-person5660** [comment]
durk, please merge, i need my lings! 
trollface

**Comment by Verbalase** [comment]
PEAK!?!?!?!?!??!?!????!?!?!?!?!?!?!???!?!?!?!?!?!?!?!?!?!?!?!?!?!?

**Review by Piras314 — DISMISSED** [review]
Read the checks.

**Comment by whateverusername0** [comment]
> Read the checks.

ikr. trying to make armblade animated is hard

**Comment by whateverusername0** [comment]
image
bad check, not even relevant to the PR

**Comment by Verbalase** [comment]
temp playtest then revert when durk says so or does it himself. if this fucks with whatever, im doing what i gotta do

**Pull request merged**
