### PR TITLE
Vgroid Buff

### PR DESCRIPTION
**Pull request by Tonk-GCR**
## About the PR

Buffs maxim hardsuit from 40%  Blunt and slash to 50%, increases piercing from 50% to 70% and adds a 25% slow down.
Adds:
Maxim Hardsuit
Clarke Mech
Drills
Retro Laser
Medtek cartridge
Mining Hardsuit
Plasma glass and Plassteel
## Why / Balance

 It gives incentive for salvage to go mine at the vgroid while having the rewards match the risks.
## Technical details

Map file change 
## Media

VgroidUpdate
maxim1

## Requirements

- [ X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [ X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

None hopefully 
**Changelog**

:cl:
- add: Added the Maxim Hardsuit, Mining Hardsuit, Clarke Mech, Retro Laser, Medtek Cartridges, drills, plasteel and plasma glass to the vgroid.
- tweak: Buffed the Maxim Hardsuit to have 10% more blunt and slash resistance, increased piercing resistance to 70%, and added a 25% movement debuff.

### CODE REVIEW

**Comment by a-person5660** [comment]
Maxim hardsuit is literally just a jug suit lmao

**Comment by BombasterDS** [comment]
Are there two maxim suit in one room?

**Comment by inquisitor-star** [comment]
I am the one who requested this bounty so I will be giving some additional information.

As it stands the suits look to be overpowered but I will list several reasons as to why they aren't:

First up is the argument its stronger than a bloodred/nukie hardsuit. While stat wise it has 20% more pierce resistance it also is 15% slower than a bloodred, bloodreds only have 10% slowdown whereas the maxim hardsuit has 25%, this suit statwise isn't close to a jugsuit.

Secondly is where it spawns, it spawns on arguably the hardest place in the entire game surrounded by both goliaths and hivelords alike, getting to the suits would be a challenge.

Thirdly it doesn't have a static spawn location furthermore it isn't guaranteed to spawn either, salvagers could mine the entire vgroid and not find one suit or they can but if the argument of salvagers aren't getting resources are the issue, this encourages salvage to mine a proportionately large size of the vgroid meaning salvage gets a reward for hard work, if they want good things they have to mine more meaning the station will always have materials.

**Comment by inquisitor-star** [comment]
Furthermore a recent pr that was added made goliaths do way more damage, so I sincerely believe one hardsuit protected by mobs that can two hit kill you is warranted.

**Pull request merged**
