### PR TITLE
Clown Resprite 

### PR DESCRIPTION
**Pull request by InfinityPandaRed**
## About the PR

Changed the clown uniform to have more details
## Why / Balance

to bring clown outfit up to date with other uniforms of goob station
## Media

clown

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl:
- tweak: Updated the clown's clothing sprites to fit in better with the new style.

## Summary by CodeRabbit

- **New Features**
	- Updated copyright information in multiple texture files to acknowledge "InfinityRedPanda(github)" as a contributor.
- **Bug Fixes**
	- No bug fixes were included in this release.
- **Documentation**
	- No new documentation was added in this release.

### CODE REVIEW

**Comment by JoeHammad1844** [comment]
please dont, he's too iconic to change

**Comment by whateverusername0** [comment]
can't even notice the difference

**Comment by JoeHammad1844** [comment]
still, it's the principal

**Comment by InfinityPandaRed** [comment]
> can't even notice the difference

if you look at the shirt there are a few more pixels

**Comment by InfinityPandaRed** [comment]
> still, it's the principal

its not that different looking its just a few more pixels on the shirt and mask

**Comment by Piras314** [comment]
i like the clown jumpskirt

**Review by Piras314 — CHANGES_REQUESTED** [review]
update the credits and don't remove equipped sprites that you don't have new versions for

**Comment by InfinityPandaRed** [comment]
> update the credits and don't remove equipped sprites that you don't have new versions for

what credits?

**Comment by InfinityPandaRed** [comment]
how do i do that?

**Comment by Piras314** [comment]
edit the meta.json files in each of the folders where you changed the sprites and add credit to where you got them from by going to the github of where you took it from, going into the data folder or wherever they keep their sprites then at the near-top-right clicking on the 3 dots and pressing "copy permalink" and adding "Taken from paradise station at commit https://blablablainsertyourlinkhere" to the copyright section.

**Comment by InfinityPandaRed** [comment]
oh no i edited the sprites myself i didnt take it from anywhere

**Comment by Piras314** [comment]
then credit yourself

**Comment by InfinityPandaRed** [comment]
done

**Comment by Piras314** [comment]
> don't remove equipped sprites that you don't have new versions for

**Comment by InfinityPandaRed** [comment]
you mean the clown masks? 
the new ones have a little bit more detail on the wig

**Comment by Piras314** [comment]
You deleted some equip sprites like the hamlet ones it looks like, you don't have to redo them but don't delete them.

**Comment by InfinityPandaRed** [comment]
how do i do this because i didn't delete the sprites they are still in the repo folder

**Review by Piras314 — APPROVED** [review]
you're right, github is just showing it weirdly

**Pull request merged**
