### PR TITLE
Made chinalake realistic

### PR DESCRIPTION
**Pull request by Teapug**
In real life the chinalake can carry a round in the chamber, which is easely accesable.

## About the PR

Chinalake has a 4 round capacity now
## Why / Balance

In real life the chinalake can carry a round in the chamber
## Technical details

literally changed a 3 to a 4
## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

it changed one fucking number
**Changelog**

:cl:
- tweak: Raised chinalake capacity to 4 rounds.

## Summary by CodeRabbit

- **New Features**
	- Increased the grenade capacity of a launcher weapon from 3 to 4, allowing for greater ammunition storage.

### CODE REVIEW

**Comment by a-person5660** [comment]
>buffs China lake
>tells maintainer to merge now
>refuses to elaborate

**Comment by Teapug** [comment]
> > buffs China lake
> > tells maintainer to merge now
> > refuses to elaborate

yes.

**Comment by JoeHammad1844** [comment]
you should add ghost loading so it can hold 5 at once

**Review by whateverusername0 — APPROVED** [review]

**Comment by Piras314** [comment]
no explanation for why you want to buff the chinalake other than "realism"

**Pull request closed without merging**
