### PR TITLE
Minor Inconsistency fix

### PR DESCRIPTION
**Pull request by InfinityPandaRed**
## About the PR

This pr changes some minor inconsistencies between sprites in game
## Why / Balance

some sprites like the wood door sprite just dint look good compared to the other wooden structure. i also recolored bruise packs and ointments to better differentiate between the two at a glance as well as so they fit in better with burn and brute kits
## Media

minor sprite incosistancy fix

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

- recolored ointment
- recolored bruise pack
- recolored wood door
- recolored wood bench
- recolored briefcase

## Summary by CodeRabbit

- **New Features**
	- Updated copyright information for various resources, including:
		- Tourniquet sprite now credits additional contributor for recolor.
		- Brown briefcase texture includes attribution for recoloring.
		- Wood door resource now acknowledges redesign by a new contributor.

### CODE REVIEW

**Comment by RealFakeSoof** [comment]
These are juicy. You cooked.

**Comment by whateverusername0** [comment]
wrong cl

it should be like

:cl:
- tweak: resprite shit

**Review by whateverusername0 — APPROVED** [review]

**Review by Piras314 — APPROVED** [review]
straight up fire

**Comment by Piras314** [comment]
if durk isnt reviewing im merging so here we go

**Pull request merged**
