### PR TITLE
Vulps can now determine solutions innately (sense of smell)

### PR DESCRIPTION
**Pull request by AstroDogeDX**
## About the PR

Give Vulpkanin the innate ability to 'scan solutions' ala the chem analysis goggles/beer goggles.

## Why / Balance

Almost all non-human species have an advantageous quirk; lizards can pull with their tail, felinids can hide in bags/hairball, rodents can hide under tables/rummage trash, harpies are walking soundboards, spiders got webs - but vulps get nothing unique. This aims to change that. Vulps are canids, canids are known for their sense of smell (yes I'm sure some chemicals are odourless but just work with me here), ergo vulps can smell chemical compositions in solutions.

### On the matter of balance
I don't see there being an issue with balance by giving one specific species built in chem goggles. They're typically not hard to get your hands on anyway (ask your friendly bartender) and the use case for being able to determine exactly what chems are in a solution are niche unless it's your job in chemistry most of the time.

## Technical details

Literally a one line addition to the `.../mob/species/vulpkanin.yml` that adds the `SolutionScanner` component to them.

## Media

dotnet_WN6SoeqByt

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

There are no breaking changes.

**Changelog**

:cl:
- add: Vulpkanin can now sniff out chemicals in solutions, similar to Chem Analysis Goggles or Beer Goggles.

## Summary by CodeRabbit

- **New Features**
	- Introduced the `SolutionScanner` component to the `Urist McVulp` entity, enhancing its sensory capabilities for identifying solutions. 

- **Bug Fixes**
	- No changes or issues reported with existing components of the `Urist McVulp` entity or the `Vulpkanin Dummy`.

### CODE REVIEW

**Comment by JoeHammad1844** [comment]
yeah lets just invalidate some job items
I personally wouldn't like this at all, but it should have a whitelist, so you cant determine every single reagent, like lexorin or romerol. some reagents like romerol also intentionally have unique textrues (not like how water or blood are automatically identified by other species) so you can know what it is without chem goggles

**Comment by AstroDogeDX** [comment]
> yeah lets just invalidate some job items
Better remove `HarpySinger` component to rebalance the Musician. /s

Understandable, but given how "OP" some of the other species traits are, this feels mostly in balance.

To your suggestion, though, I kinda vibe with it. Would need a whole new component, though - perhaps a milder form of `SolutionScanner` that can't provide exact units or temperature (because tbf that doesn't make sense), and sure, can't identify _all_ reagents. Perhaps it'd report back like;
```
Contains:
Water
Vodka
Orange Juice
...and something else
```
Where the something else is all blacklisted/non-whitelisted reagents. I'onno though, I still don't see this as invalidating anything since it's a singular specific species. The point is to give 'em something since they're pretty lacking compared to the other non-human species. ¯\(°_o)/¯

**Comment by deltanedas** [comment]
doesnt even matter because every pro gamer knows the reagent list off by heart

**Comment by JoeHammad1844** [comment]
> doesnt even matter because every pro gamer knows the reagent list off by heart

that's a skill issue

**Comment by ARMOKS** [comment]
time to PR the indomitable human spirit buff for humans

**Comment by JoeHammad1844** [comment]
> time to PR the indomitable human spirit buff for humans

20 more damage before crit :trollface:

**Comment by Aidenkrz** [comment]
Nah, I think this PR should be ported instead, https://github.com/Simple-Station/Einstein-Engines/pull/715

**Pull request closed without merging**
