### PR TITLE
Reflect and esword stuff

### PR DESCRIPTION
**Pull request by Aviu00**
## About the PR

Fixed desword humming sound not turning of when toggling it off.
Fixed desword not reflecting sometimes.
Cherry-picked [this](https://github.com/space-wizards/space-station-14/pull/32869).
Ported [this](https://github.com/WWhiteDreamProject/wwdpublic/pull/6).
Now energy weapons now these reflect chances: desword - 100% energy 25% ballistic, esword - 50% energy 12.5% ballistic, epen - 25% energy 0% ballistic.
To compensate, I buffed esword and desword slightly:
Esword is now slightly cheaper (37 tc), because now desword is crafted from 2 eswords and I want it to be purchasable with vest and noslips when [this](https://github.com/Goob-Station/Goob-Station/pull/1134) gets merged.
Desword now has 40 structural damage.
Captain sabre reflect chance removed (crew shouldn't have reflective weapons), its damage increased by 2 to compensate.
Shuttle walls no longer reflect (why they were able to in the first place?).

## Why / Balance

Desword was too op, a team of nukies with deswords and mechs is an easy win (I'll nerf/rework mechs later probably).

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl: Aviu
- add: New reflect chances for energy weapons: desword - 100% energy 20% ballistic, esword - 50% energy 10% ballistic, epen - 25% energy 0% ballistic.
- add: Now desword is not purchasable from uplink. Instead, it is crafted from 2 eswords (click 1 esword on another).
- add: Now you flip when hitting something using a desword, as god intended.
- fix: Fix desword not reflecting.
- fix: Desword can't be used one-handed anymore.
- tweak: Captain sabre doesn't reflect anymore but deals more damage.
- remove: Shuttle walls no longer reflect.
- tweak: Esword price lowered 40 -> 37.
- tweak: Desword structural damage increased 15 -> 40.

### CODE REVIEW

**Comment by Aidenkrz** [comment]
I like most of this, but dont know how I feel about
> Captain sabre reflect chance removed (crew shouldn't have reflective weapons), its damage increased by 2 to compensate.

I'll have the admins decide.

**Comment by lanse12** [comment]
> I like most of this, but dont know how I feel about
> 
> > Captain sabre reflect chance removed (crew shouldn't have reflective weapons), its damage increased by 2 to compensate.
> 
> I'll have the admins decide.

the reflect is 10% as of now so it's basically the same

**Comment by BombasterDS2** [comment]
As i said a lot of times - random reflection is very poor mechanic and i don't like it that you won't be able to hit someone with desword.

When crew main defense weapons is laser this will buff nukies a lot. If you want fight disablers and stun meta - just add stamina damage resistance to gear (we have that component for 2-3 months already?)

**Comment by Aviu00** [comment]
> As i said a lot of times - random reflection is very poor mechanic and i don't like it that you won't be able to hit someone with desword.
> 
> When crew main defense weapons is laser this will buff nukies a lot. If you want fight disablers and stun meta - just add stamina damage resistance to gear (we have that component for 2-3 months already?)

Most nukies wear elite suits to counter uranium bullets and x-ray cannons anyway, so this wouldn't impact much. But now you can actually kill desword wielding nukie with bullets!!!
Stamresists suck, it's way worse than this.

**Comment by Sarahon** [comment]
Caps sabre should have some reflect chance, and I don't think anything should have a 100% chance of reflect. Like Bomb had said, most of the time crews only option is lasers, not xray. There's too many rogue variables to account for that. You also put cap in a bad spot with 0 reflect when crew die and drop the lasers and bullets that is used against them. Way too much of a nukie buff when they're already strong enough as is.

**Comment by BombasterDS2** [comment]
Also, the PR you cherry picked was merged with upstream long ago.

**Comment by BombasterDS2** [comment]
> > As i said a lot of times - random reflection is very poor mechanic and i don't like it that you won't be able to hit someone with desword.
> > When crew main defense weapons is laser this will buff nukies a lot. If you want fight disablers and stun meta - just add stamina damage resistance to gear (we have that component for 2-3 months already?)
> 
> Most nukies wear elite suits to counter uranium bullets and x-ray cannons anyway, so this wouldn't impact much. But now you can actually kill desword wielding nukie with bullets!!! Stamresists suck, it's way worse than this.

Bullet firearms is limited on station when energy typed firearms can be crafted. Most crew will have energy-type firearms and this will make it absolutely useless, making desword more disbalanced.

Also with captain saber - + 2 damage not equal 25% reflect chance (25% damage evading != +1% max HP target damage)

**Comment by Aviu00** [comment]
> Caps sabre should have some reflect chance, and I don't think anything should have a 100% chance of reflect. Like Bomb had said, most of the time crews only option is lasers, not xray. There's too many rogue variables to account for that. You also put cap in a bad spot with 0 reflect when crew die and drop the lasers and bullets that is used against them. Way too much of a nukie buff when they're already strong enough as is.

Yeah, it's a fun gameplay when nukies are forced to take down AI because otherwise it will bolt every door on them and they will be overwhelmed by lasers, with these changes nukies can desword through the bolted doors. And it's not a nukie buff, before the only 2 ways to take down a nukie with desword were pies and batons. Now you can actually gun them down. Lasers are not an option during nukeops at this point anyway because most nukies wear elite hardsuits. 30% cap sabre reflect chance is too insane compared to esword which has now 12.5%, and it shouldn't be better than esword.

**Comment by Aviu00** [comment]
> Also, the PR you cherry picked was merged with upstream long ago.

No it was merged 2 weeks ago.

**Comment by Aviu00** [comment]
> Bullet firearms is limited on station when energy typed firearms can be crafted. Most crew will have energy-type firearms and this will make it absolutely useless, making desword more disbalanced.

Cargo can buy guns. Secfab can print ammo. Nukies wear elite hardsuits with 80% heat resists.

**Comment by BombasterDS2** [comment]
> > Also, the PR you cherry picked was merged with upstream long ago.
> 
> No it was merged 2 weeks ago.

Yeah, saw it. I thought it was merged long ago.

**Comment by CerberusWolfie** [comment]
I'm on the side of leaving the Captain Sabre as is. If you want to buff the damage, go ahead, but the reflect chance should remain for now. The justification being that the crew shouldn't have reflective weapons is not a good justification.

**Comment by BombasterDS2** [comment]
100% reflection energy chance still too much. If you want to keep it, i guess crew need some energy variant that can't be reflected. You can change x-ray hitscan projectile to make less damage, but it'll have true strike that can't be reflected.

**Comment by JoeHammad1844** [comment]
this is epic

**Comment by WhiteGorila** [comment]
this + removing the dogshit wizden movement reflect thing would be peak. reflects literally dont work because of this

**Comment by JoeHammad1844** [comment]
> this + removing the dogshit wizden movement reflect thing would be peak. reflects literally dont work because of this

pretty sure the movement reflect thing was already reverted on wizden a while ago

**Comment by Aviu00** [comment]
I'm going to port telebatons for command, I'm going to give cap and bso actual ballistic guns, just merge this as it is. Cap's sabre having almost triple ballistic reflect chance compared to esword is stupid.

**Comment by Aviu00** [comment]
Reduced desword ballistic reflect by 5% and esword by 2.5%. Will probably make them EMPable later in another PR so you can't counter a baton too easily.

**Comment by Aidenkrz** [comment]
still dont know how i feel about 100% reflection chance on energy weapons but whatever....

**Pull request merged**
