### PR TITLE
remove cap sabre reflect

### PR DESCRIPTION
**Pull request by lanse12**
## About the PR
removed cap sabre reflect but upped damage to 20

## Why / Balance
why the fuck does he even have reflect only antags should

### CODE REVIEW

**Comment by Plyushsune** [comment]
Malder

**Comment by Aviu00** [comment]
#1137

**Comment by JustSome1Nearby** [comment]
"HOW DO YOU DEFLECT 
BULLETS WITH A SIMPLE STEEL SWORD, CAPPY?"
"NANOMACHINES, SON"

**Comment by HenhenIII** [comment]
Malder

**Comment by lanse12** [comment]
nvm already pr'd

**Pull request closed without merging**
