### PR TITLE
Revert "multi page action bar (#469)"

### PR DESCRIPTION
**Pull request by Aviu00**
This reverts commit 9cc4c63ca536bfabcc5ba8c2334272af69023744.

## Why / Balance

Multi page action bar is not needed since now action bar [dynamically resizes](https://github.com/space-wizards/space-station-14/pull/31759). Also swapping actions by dragging is a nice feature.

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl: Aviu
- add: Improved action bar.

### CODE REVIEW

**Comment by Aineias1** [comment]
you should merge this... NOW!
 Also @whateverusername0 refer to this when someone malds about hotbar beign too smal

**Comment by deltanedas** [comment]
lings so back

**Review by whateverusername0 — APPROVED** [review]

**Comment by Piras314** [comment]
Really the only reason we have the multi page action bar still is for mapping, the new action bar completely destroyed the mapping action's usefulness

**Comment by Aidenkrz** [comment]
> Really the only reason we have the multi page action bar still is for mapping, the new action bar completely destroyed the mapping action's usefulness

we had it for changeling and heretic.

**Comment by Piras314** [comment]
I meant the only reason that I didn't do this already is because of mapping

**Comment by JoeHammad1844** [comment]
THIS SHIT FUCKING SUCKS IT RESETS MY PDA POSITION EVERY TIME I HOLD IT

**Comment by deltanedas** [comment]
dont hold your pda then

also flashlights really dont need actions imo you can press e

**Comment by JoeHammad1844** [comment]
> dont hold your pda then

ever playeed medical?

**Comment by deltanedas** [comment]
put id in id slot and hold empty pda 24/7 no risk of slips

**Pull request merged**
