### PR TITLE
Sprite Inconsistency Fix 1

### PR DESCRIPTION
**Pull request by InfinityPandaRed**
## About the PR

This pr makes very minimal changes to some sprites in order to bring them up to date with other goob station assets
## Why / Balance

Due to some sprites being copied from other stations there are some inconsistency between some goobstation sprites. this pr aims to fix that by recoloring some sprites to match others of its type and adding more detail to others. most changes are very minor
## Media

inconsistancy

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

- grey jumpsuit
- rubber gloves
- cargo softcap
- bartender
- chef
- BSO armored suit
- lawyer suits
- Hydro
- Librarian
- wood  tables 
- mailman
- trooper
- safari

## Summary by CodeRabbit

- **New Features**
	- Updated copyright attributions for the janitor, cargosoft, and wood textures to acknowledge recoloring by InfinityRedPanda.
  
- **Bug Fixes**
	- Corrected copyright information to ensure proper credit for the recoloring of resources.

### CODE REVIEW

**Review by ElPidor — COMMENTED** [review]
looks good, but i feel it doesnt worth time to changing 1-2 pixels to fit something
image
like why..,

**Comment by InfinityPandaRed** [comment]
> looks good, but i feel it doesnt worth time to changing 1-2 pixels to fit something image like why..,

**Comment by InfinityPandaRed** [comment]
do you want me to change it back?

**Comment by Aidenkrz** [comment]
I wanted to get in contact with you on discord but im not sure what your tag is, mind throwing me a DM @ gaming420 on disc?

**Pull request merged**
