### PR TITLE
Swap UI Sounds for HL2

### PR DESCRIPTION
**Pull request by Scruq445**
## About the PR
Change's SS14 UI Sounds to that of HL2's UI Sounds

## Why / Balance
cuz it's fuuuunny

## Technical details
Changes the UI click.ogg and hover.ogg with HL2's buttonrollover.wav and bottonclickrelease.wav

## Media
[](https://github.com/user-attachments/assets/e6059f42-10f3-4a6c-bc52-d3925a2a43b4)

**Changelog**

:cl:
- tweak: Changed UI Sounds to HL2 UI Sounds

### CODE REVIEW

**Comment by yglop** [comment]
"Custom License" looks like DRM violation.

**Comment by a-person5660** [comment]
as far as im aware these sounds are free use as long as we are not charging for them.

**Comment by Scruq445** [comment]
> "Custom License" looks like DRM violation.

The sounds I could only trace back to the Source SDK, but most sounds that valve uses are stock sfx. but with it being only traceable to the Source SDK, and Valve having their own custom license on the SDK (which says that you may use it's contents in a free product without a fee)

**Comment by Aidenkrz** [comment]
Wheres the source.

**Comment by Scruq445** [comment]
> Wheres the source.

https://github.com/ValveSoftware/source-sdk-2013/blob/master/README

**Comment by Aidenkrz** [comment]
Thats the license, not a source.

**Comment by Scruq445** [comment]
source for what?

**Comment by Aidenkrz** [comment]
bro, the sounds, what else. its literally all thats in this pr

**Comment by Scruq445** [comment]
I said it came from the assets of Half-Life 2, why else would I plaster it's name all over the PR

**Pull request closed without merging**
