### PR TITLE
Revert "Moth Maggots"

### PR DESCRIPTION
**Pull request by JoeHammad1844**
Reverts Goob-Station/Goob-Station#852

ROACHES ARE BETTER

## Release Notes

- **New Features**
	- Introduced new entities, including `diona nymph` and various `Cube` types, enhancing gameplay diversity.
	- Added new microwave meal recipes, expanding culinary options.

- **Changes**
	- Renamed roles and items from "SyndiMaggot" to "SyndiRoach" and updated associated descriptions.
	- Updated the `moth maggot` entity to `mothroach` with a refined description.

- **Documentation**
	- Updated copyright information for texture resources to reflect new attributions.

### CODE REVIEW

**Comment by BeeRobynn** [comment]
PR denied, feel free to contribute NEVER

**Comment by JoeHammad1844** [comment]
Uploading old man screaming into camera.mp4…

**Comment by whateverusername0** [comment]
reconsidering thee options with @Piras314 rn...

**Comment by whateverusername0** [comment]
durk must not selfmerge

**Comment by JoeHammad1844** [comment]
Why can't we have both roaches and maggots?

**Comment by Erisiaa** [comment]
mothmaggots are the better mothroach, you guys are just blind, YOU HATE CHANGE!! Y'ALL JUST BEING HATERS!!! MOTHROACHES ARE WORSE THEN MOTHMAGGOTS!! MOTHMAGGOTS LOW DIFF MOTHROACHESS!!!

**Comment by HenhenIII** [comment]
Durk managed to close his own PR revert twice now, bluh

**Comment by HenhenIII** [comment]
**1984**

**Comment by whateverusername0** [comment]
1984

**Comment by Aineias1** [comment]
1984
(mothmaggots suck)

**Comment by deltanedas** [comment]
*chitters x603

**Comment by yglop** [comment]
1984

**Comment by JoeHammad1844** [comment]
Can we lynch durk

**Pull request closed without merging**
