### PR TITLE
Nuclear operatives can buy surplus crates

### PR DESCRIPTION
**Pull request by a-person5660**
## About the PR
Nukies can now buy surplus crates!

## Why / Balance
I think its funny and thought that it would be worth having a discussion about.

## Requirements
- [x] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
🆑 
- tweak: Nuclear operatives can now purchase surplus crates, gambleops rejoyce!

### CODE REVIEW

**Comment by misandrie** [comment]
>more than doubling effective tc count

**Comment by Aidenkrz** [comment]
With the ammount of TC nukies/warops has, this basically guarantees they will all get jugg suits and chinalakes. I do not see how this is a good idea at all.

**Comment by a-person5660** [comment]
the way i think it should be done is have a seperate crate with lower margins so they are less likely to get stuff thats worth way more than the TC they spend on it, and it should consume the entire nukies TC to buy, then a super variant for warops.

**Comment by Piras314** [comment]
> i think gambleops has some fun gimmic potential and might also force nukies to use different strategies if they dont get the meta items they want.

Honestly if this is going to be a thing (and it sounds pretty cool) it should be done with its own gamemode, something like surplus ops or recyled ops or something and everyone spawns without an uplink and just with random gear worth a normal ops tc.

**Comment by a-person5660** [comment]
> Honestly if this is going to be a thing (and it sounds pretty cool) it should be done with its own gamemode, something like surplus ops or recyled ops or something and everyone spawns without an uplink and just with random gear worth a normal ops tc.

i really like this idea, gonna close this and come back to it later with a seperate gamemode for gambleops (maybe admin only)

**Pull request closed without merging**
