### PR TITLE
Revert "Emag works as laws board for syndicate lawset on AI (#637)"

### PR DESCRIPTION
**Pull request by BombasterDS**
## About the PR
Feature was added on goob with AI. Now, game have Antimov lawboard, so we don't need this because it's too OP and makes antimov useless.

:cl:
- remove: EMAG no longer works as Syndicate lawboard for AI upload.

## Summary by CodeRabbit

- **New Features**
	- Updated `Emag` entity with new `LimitedCharges` and `AutoRecharge` components for enhanced functionality.
- **Changes**
	- Removed the `SiliconLawProvider` component from `EmagUnlimited`, streamlining its structure.

### CODE REVIEW

**Comment by deltanedas** [comment]
antimov is completely different from syndicate lawset

**Comment by BombasterDS** [comment]
> antimov is completely different from syndicate lawset

I know, but anyway this feature is too OP for nukies and traitors. AI will 100% work with them, emag is cheaper than antimov and emag is more useful than antimov.

It was made when AI got merged on Goob to allow AI works with antags, but now it's just overpowered feature.

**Comment by lanse12** [comment]
this might be a mald pr

**Comment by BombasterDS** [comment]
> this might be a mald pr

okay, what mald pr even means???

**Comment by Piras314** [comment]
add a syndicate lawset board to the uplink then, don't just remove things, replace them, move them around, etc.

**Comment by BombasterDS** [comment]
> add a syndicate lawset board to the uplink then, don't just remove things, replace them, move them around, etc.

I made this feature to add something when we didn't have anything... Now, we just don't need it, antimov works fine.

**Comment by JoeHammad1844** [comment]
Mald pr

**Comment by deltanedas** [comment]
> Now, we just don't need it, antimov works fine.

traitor lawset can be used as antimov but not vice versa, you cant tell the ai to keep you alive at all costs since that would violate law 1 for example

**Comment by Aidenkrz** [comment]
yall he made the original pr.

**Comment by ShootsTheMoon** [comment]
This is a good PR thank you for fixing this issue I too thought 60 tc for an entire crew death was op.

**Pull request merged**
