### PR TITLE
Core Rule 13 Update Real?

### PR DESCRIPTION
**Pull request by Verbalase**
## About the PR
Updated Core Rule 13.

## Why / Balance
Species having names outside of their usual naming schemes looks awfully weird without at least a lore reason for it, like for example, having a human with a reptilian naming scheme would just be unrealistic. 

Having roman numerials, or "Jr" and certain other family titles allowed in names are fine since they basically DO go in legal documents, y'know? They're something that you can put on a birth certificate, but having "Dr", "Mrs" or other titles like such obviously wouldn't.

Also, since the Rodentia naming scheme wasn't added, I did it myself. Other changes too included!!!

## Requirements
- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes
Erm, none.

**Changelog**
:cl:
- tweak: Core Rule 13 updated.

## Summary by CodeRabbit

- **New Features**
	- Clarified guidelines on character naming, emphasizing originality and cultural alignment.
	- Expanded naming conventions for various species with specific examples.
- **Bug Fixes**
	- Improved readability of the list of unacceptable names and examples.
- **Documentation**
	- Restructured sections for clarity, including exceptions for clowns and mimes.

### CODE REVIEW

**Review by Piras314 — DISMISSED** [review]
add [color=#449944]Good:[/color] to all the good examples

e.g.
Examples
- [color=#449944]Good:[/color] Sierra Lightseeker
- [color=#994444]Bad:[/color] Joe Mamma

**Comment by Verbalase** [comment]
> [color=#449944]Good:[/color]

im actually going to choke you

**Comment by Verbalase** [comment]
i did it bro

**Comment by Verbalase** [comment]
ugh i take it back

**Comment by Verbalase** [comment]
ok now we lit. any other things?

**Review by Piras314 — APPROVED** [review]

**Comment by Verbalase** [comment]
test run ig?

**Comment by Piras314** [comment]
mark things that arent ready for merge as drafts or tell me!

**Comment by Verbalase** [comment]
> mark things that arent ready for merge as drafts or tell me!

we had an ongoing discussion

**Pull request merged**
