### PR TITLE
cadets can roll antag

### PR DESCRIPTION
**Pull request by starch70**
## About the PR
Added fun!

## Media
ac64a7d88cf28ab7

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**
:cl:
- add: Added fun!

it took me longer to write the info about this than it did to actually make it

## Summary by CodeRabbit

- **New Features**
	- The Security Cadet role can now participate as an antagonist.
	- Removed the special ability related to the MindShield Implant from the Security Cadet.

### CODE REVIEW

**Comment by JoeHammad1844** [comment]
finally, a good fucking PR

**Comment by ElPidor** [comment]
I understand but it can provide following things. 
Ahelp Crying 
Rulemaxxing 
Metamaxxing 
And the thing that counter this PR is 
Mindshilding from start of the game, because they're security -> so they cant become antag if not roundstart 
In general it seems to be a very funny addition for cadets being silly and shooting random people that is what goob needs

**Comment by HenhenIII** [comment]
Wdym? They are already an antag :godmode:

**Comment by BombasterDS** [comment]
Security is only department that should be protected from being antag.

**Comment by whateverusername0** [comment]
bro no

**Comment by Piras314** [comment]
### **Cadets are already antagonists.**









_this is a joke_

**Pull request closed without merging**
