### PR TITLE
remove zeds

### PR DESCRIPTION
**Pull request by lanse12**
## About the PR
removed zeds gamemode from rotation and increased chance of heretic subgamemode

## Why / Balance
zeds fucking suck ass and heretics are fun

## Breaking changes
removed zeds, increased heretic chance by 10% and game zed's 5% to traitors

**Changelog**

:cl: Syndie
- tweak: Removed zombies from rotation, increased chance of heretics by 10%, increased traitors chance by 5%

### CODE REVIEW

**Comment by toasterpm87** [comment]
attachment-1

**Comment by gluesniffler** [comment]
hello? based department?

**Comment by gluesniffler** [comment]
yaml linter fail lmao

**Comment by Verbalase** [comment]
image

**Comment by JoeHammad1844** [comment]
Cope seethe mald

**Comment by Piras314** [comment]
you know you fucked up when kira closes your PR

**Pull request closed without merging**
