### PR TITLE
adds tails and matryoshka plush

### PR DESCRIPTION
**Pull request by toasterpm87**
bkv3
^
communist

(oh yeah, also it adds fox tails to felinids)

### CODE REVIEW

**Comment by toasterpm87** [comment]
the error is for a thing i never touched

**Comment by toasterpm87** [comment]
image

**Comment by toasterpm87** [comment]
image

**Comment by CatMagic1** [comment]
add a commit that says you're gonna kiss durk

**Comment by Aidenkrz** [comment]
> add a commit that says you're gonna kiss durk

I'm gonna bash ur head in with a big rock

**Comment by toasterpm87** [comment]
> add a commit that says you're gonna kiss durk

i will

**Comment by Aidenkrz** [comment]
Remove the plushies from the loadout and its fine.

**Comment by Aidenkrz** [comment]
blud, i said remove the plushies from the loadout, not remove the one plushie

**Comment by toasterpm87** [comment]
> blud, i said remove the plushies from the loadout, not remove the one plushie

bleh, should i add the plushie back then?

**Comment by toasterpm87** [comment]
i added them back anyways

**Pull request merged**
