### PR TITLE
syringe ops real

### PR DESCRIPTION
**Pull request by gluesniffler**
## About the PR
Ask and ye shall receive. Added the syringe gun and unbitchmade-ified it based on [our lord and saviour SS13](https://tgstation13.org/wiki/Medical_items#:~:text=Medical%20dispensers.-,Syringe%20Gun,-Found%20in%3A).

It can now load 15u syringes. The default version can only load one at a time. Theres an unlockable rapid version that takes 6 shots. The CMO gets the rapid version for themselves round start. None of these can penetrate armor. These guns are also large, and take about as much space as a Kammerer.

Theres also a traitor version for 30tc which can penetrate armor, only holds one syringe, and is only purchaseable by medical traitors. It can also fit in pockets.

Did I mention that these inject all of their contents on embed now too? Fun times. Additionally, the CMO has gotten a few new goodies:

- A box of pax syringes on their locker to use with the funny gun
- Swapped their toolbelt with a webbing with no whitelist that holds a set of advanced surgical tools (a medical analogue to the CE's advanced shit), and their usual round start topicals.

## Why / Balance
Medical is fairly defenseless against shitters, tiders and other would-be-evildoers, this gives them a bit more of an edge to defend themselves ~~and potentially validhunt better~~. Also parity with 13 is good :blunt:

Before anyone starts bitching about balance, let it be known that I held back. I should've added this one as well but decided to test the waters first.
image

## Media
[Syringe Gun Demo](https://www.youtube.com/watch?v=JHCROPoko-g "Syringe Gun Demo")

## Requirements
- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.
- [ ] I have added defelinization surgery.

**Changelog**
:cl: Mocho
- add: Added 3 different flavors of syringe guns, 2 obtainable by crew, 1 by traitors
- add: CMOs lockers now contain a Rapid Syringe Gun and a box filled with 6 pax syringes. Don't validhunt too much with them will you?
- tweak: The CMO now spawns with a webbing filled with advanced surgical instruments along with their usual gear.
- tweak: Syringes shot from a syringe gun do not pierce armor unless they are shot from a gun with the necessary components.
- tweak: Throwing syringes now embeds them on entities, and transfers 2u of the contents. Doesn't pierce armor.

## Release Notes

- **New Features**
	- Introduced new syringe-based weapons: Syringe Gun, Rapid Syringe Gun, and Dart Syringe Gun, each with unique functionalities.
	- Added a new `SyringeGunComponent` for instant injection of syringe contents.
	- Enhanced injection mechanics for syringes, allowing for varied interactions based on conditions.
	- New technology entries related to medical defense and advanced treatments.
	- Added new item to the uplink catalog: Dart Syringe Gun.

- **Bug Fixes**
	- Improved error handling and control flow in injection processes.

- **Documentation**
	- Updated catalog entries and descriptions for new items and technologies.

- **Chores**
	- Added metadata files for new textures and assets related to the syringe guns.

### CODE REVIEW

**Review by Piras314 — CHANGES_REQUESTED** [review]
Chemists don't need syringe guns

**Comment by Piras314** [comment]
update CL, fix conflicts @gluesniffler

**Comment by gluesniffler** [comment]
> update CL, fix conflicts @gluesniffler

done

**Comment by JoeHammad1844** [comment]
How much armor is required to block a syringe? Is ANY outer wear enough?

**Pull request merged**
