### PR TITLE
Re-add Kettle

### PR DESCRIPTION
**Pull request by Piras314**
## About the PR

re-adds kettle (before it was gemini), almost a year old now, with BSO, NTR, new chemistry equipment, AI, more cameras for AI, tesla, etc.

## Why / Balance

everybody likes it

## Media

Kettle-0

image

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl:
- add: Added Kettle (before it was Gemini)!

## Summary by CodeRabbit

- **New Features**
	- Introduced a new game map, **Kettle**, with defined player roles and emergency protocols.
- **Changes**
	- Removed two maps, **Cog** and **Train**, from the available map pool due to player feedback.
	- **Kettle** is now part of the game map pool, enhancing gameplay options.
- **Author Updates**
	- Updated authorship for **barratry.yml** and **kettle.yml** to include **Piras314**.

### CODE REVIEW

**Comment by Piras314** [comment]
Kettle-0

**Comment by JoeHammad1844** [comment]
Pillar when

**Comment by HenhenIII** [comment]
I approve this. This must be self merged now

**Comment by deltanedas** [comment]
NSS Cyberiad when

**Comment by Verbalase** [comment]
> NSS Cyberiad when

wymi

**Comment by Piras314** [comment]
box station is the cyberiad

**Comment by Piras314** [comment]
self merge let's gooooooooooooooooo

**Comment by deltanedas** [comment]
real box is cyberiad all along

**Comment by yglop** [comment]
thank you penguin

**Pull request merged**
