### PR TITLE
Bagel Update

### PR DESCRIPTION
**Pull request by Icepicked**
## About the PR

Updated Bagel: 
- added Biogenerators to Perma and Botany.
- Remodeled the "Abandoned" Dock area. 
## Media

image
image

## Requirements

- [ ] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [ ] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl:
- add: Added Biogenerators to Bagel.
- tweak: Bagel has a proper shuttle building area now.

### CODE REVIEW

**Comment by Piras314** [comment]
It would be nice to have some dark green decals around the green tiles to make them less starkly contrasted

**Comment by Icepicked** [comment]
@Piras314 around the Bio Generator and Seed extractor?

**Comment by Icepicked** [comment]
image
this work?

**Comment by Piras314** [comment]
hell yes

**Review by whateverusername0 — APPROVED** [review]

**Pull request merged**
