### PR TITLE
Fix reenable pipestacking.

### PR DESCRIPTION
**Pull request by jorgun**
## About the PR

number of atmoisians keeping the station alive is droping

## Why / Balance

image

## Technical details

commented out the line that disabled pipestacking

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

- fix: pipes can now be stacked agein. for now

### CODE REVIEW

**Comment by Piras314** [comment]
change your cl to

Pipes can now be stacked again.

**Review by Piras314 — APPROVED** [review]
seems good to me

**Comment by Aidenkrz** [comment]
nahhhhhhh

**Comment by jorgun** [comment]
how about a compromise?

**Comment by Piras314** [comment]
make your own bigger burn chambers ig

**Pull request closed without merging**
