### PR TITLE
X-01 Multiphase Energy Gun (Delta-V #385, Frontier-#587)

### PR DESCRIPTION
**Pull request by Icepicked**
## About the PR

The Head of Security's special energy gun from TG Station.

ported from DeltaV and Frontier Station
https://github.com/new-frontiers-14/frontier-station-14/pull/587
https://github.com/DeltaV-Station/Delta-v/pull/385

## Why / Balance

The BSO needs something to help them protect Command. the X-01 Multiphase has both Disabling and lethal shots that allow them to do so. The X-01 spawns in their locker.

## Technical details

A new system and component was made for the EnergyGun that allows for it to change between lethal and disable firemode while also changing sprites. It's the stunbaton and firemode system duct taped together.

## Media

https://github.com/DeltaV-Station/Delta-v/pull/385
## Requirements

- [ ] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl: FluffiestFloof, dvir01, BombasterDS, Icepicked
- add: Added the X-01 MultiPhase for the BSO

## Summary by CodeRabbit

- **New Features**
	- Introduced an energy gun with multiple firing modes, enhancing gameplay dynamics.
	- Added new projectile types: "energy bolt" and "ion bolt," each with distinct behaviors and visual effects.
	- Implemented visual effects for bullet impacts, providing clearer feedback during gameplay.
	- Added the "X-01 multiphase energy gun," featuring detailed attributes and functionalities.

- **Bug Fixes**
	- Resolved issues related to the interaction and feedback mechanisms for the energy gun.

- **Documentation**
	- Updated metadata for the multiphase energy gun, including visual states and licensing information.

### CODE REVIEW

**Comment by whateverusername0** [comment]
why would you need a separate system for that when there's an already working existing system that does the exact same thing?
see energy shotgun prototype pls

**Comment by whateverusername0** [comment]
OK i see why you need a separate system now

another issue
why is the ion mode commented out?

**Comment by Icepicked** [comment]
> OK i see why you need a separate system now i just don't know how to read
> 
> another issue why is the ion mode commented out?

Because it doesnt exist, Im just porting this and didnt feel like (or know how to) make a new bullet :godo:

**Comment by dvir001** [comment]
I won't lie to you the code on this was never fixed as it should and the sprite still buggy, 
if you want to actually fix it cool but other than sprite issue on mod switch it's working ok.

**Comment by Piras314** [comment]
what errors are preventing you from putting certain components into the proper folders? @Icepicked

**Review by Piras314 — APPROVED** [review]

**Comment by BombasterDS** [comment]
daaamn, when i saw ion mode i thought you added ion damage for borgs :(

**Comment by BombasterDS** [comment]
Actually, cold damage on ion mode looks too op because most armor just don't have resist against it

**Review by whateverusername0 — APPROVED** [review]
works

**Pull request merged**
