### PR TITLE
Medglasses flash protection

### PR DESCRIPTION
**Pull request by Icepicked**
## About the PR

Adds flash protection to medglasses (i forgotteded)

## Media

https://github.com/user-attachments/assets/743c689b-dcdf-498a-9eda-45ddd39964a9

## Requirements

- [ ] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [ ] I have added media to this PR or it does not require an ingame showcase.

**Changelog**

:cl:
- tweak: Medglasses are now Medsecglasses.

## Summary by CodeRabbit

- **New Features**
	- Introduced new attributes for glasses: `FlashImmunity` and `EyeProtection`.
	- `EyeProtection` now includes a `protectionTime` property set to 5, enhancing gameplay related to vision and environmental hazards.
	- Updated eyewear for the "blueshield officer" role to a more specialized design, reflecting enhanced security features.

### CODE REVIEW

**Review by whateverusername0 — APPROVED** [review]
ok

**Comment by Piras314** [comment]
might as well make the bso glasses have the sec hud too and rename them to medsecglasses

**Comment by Icepicked** [comment]
@Piras314 there you go :godo:

**Comment by Icepicked** [comment]
bruh thats not my fault 
image

**Comment by JoeHammad1844** [comment]
shouldnt medglasses and medsec glasses be different items?

**Comment by Icepicked** [comment]
@lanse12 its for BSO not med. 

@JoeHammad1844 because I didnt feel like figuring out how crafting recipes work :godo:

**Pull request merged**
