### PR TITLE
Ion damage

### PR DESCRIPTION
**Pull request by BombasterDS**
## About the PR
Added Ion damage and Electronic damage group.
Works only on borgs for now.

Weapons with ion damage:
- X-01 Ion mode will deal 20 ion damage instead of cold damage.
- Disabler and Disabler SMG will deal 10/5 ion damage
- X-ray deal 15 ion damage

All borgs got protection:
All NT borgs now have 5 flat brute damage and 20% heat damage resistance. 
Syndicate assault borg now have 5 + 40% brute damage, 50% heat damage, 50% explosive damage resistance. 
Electro and Ion damage won't be reduced.

Syndicate borg price increased from 325 to 375 tc.

## Why / Balance
X-01 ion mode looks boring with just cold damage + borgs weren't feel like threat to anyone without any protection. 

## Media

https://github.com/user-attachments/assets/c0ba78eb-e34f-4ad2-8110-99f934780535

:cl:
- add: Added new damage type - Ion. Some disabling weapons can now make this damage. Most electonic creatures are weak against this type of damage.
- add: All borgs get slight damage resistance for brute and heat damage. Syndicate borgs get more protection.
- tweak: X-01 Ion mode now deal Ion damage instead of cold damage.
- tweak: Syndicate assault borg price increased from 325 to 375 tc.

## Summary by CodeRabbit

- **New Features**
	- Added localization support for "Electronic" and "Ion" damage types, enhancing user experience for English-speaking users.
	- Introduced a new damage group for electronic damage, improving gameplay mechanics.
	- Enhanced weapon mechanics by adding "Ion" as a new damage type across various projectiles and weapons.

- **Gameplay Adjustments**
	- Increased the cost of specific in-game items to balance gameplay.
	- Modified the damage handling for Cyborg entities, improving their resilience against various damage types.

- **Performance Enhancements**
	- Adjusted fire costs for certain weapons to improve usability and effectiveness.

### CODE REVIEW

**Comment by JoeHammad1844** [comment]
cold damage was just basically be AP lol

**Comment by whateverusername0** [comment]
i like it
revert x-ray changes though or change it to ion cannon that can *still* deal radiation damage

**Comment by whateverusername0** [comment]
also make only syndicate borgs have armor

**Comment by BombasterDS** [comment]
> i like it revert x-ray changes though or change it to ion cannon that can _still_ deal radiation damage

X-ray cannon deals Ion and Radiation damage.

**Comment by BombasterDS** [comment]
> also make only syndicate borgs have armor

I wanted to make every borg more healthy. Borg is real iron man, but have 0 protection. I can remove percent damage from standart borgs, but leave flat

**Review by whateverusername0 — APPROVED** [review]

**Comment by JoeHammad1844** [comment]
Do we have an ion gun yet? Or will that be later

**Comment by Icepicked** [comment]
@JoeHammad1844 The X-01 Mulitphase (Ion Mode), X-Ray Cannon, Disabler, and Diabler SMG deal ion damage

**Comment by JoeHammad1844** [comment]
> @JoeHammad1844 The X-01 Mulitphase (Ion Mode), X-Ray Cannon, Disabler, and Diabler SMG deal ion damage

but will there be a dedicated ion gun? like other ss13 servers?

**Comment by BombasterDS** [comment]
> > @JoeHammad1844 The X-01 Mulitphase (Ion Mode), X-Ray Cannon, Disabler, and Diabler SMG deal ion damage
> 
> but will there be a dedicated ion gun? like other ss13 servers?

I found only Ion Rifle and X-01 on tg wiki that shoot ion bolts. Anyway, Ion rifle useful against mechs, but battle mechs won't be added soon.

**Comment by JoeHammad1844** [comment]
> > > @JoeHammad1844 The X-01 Mulitphase (Ion Mode), X-Ray Cannon, Disabler, and Diabler SMG deal ion damage
> 
> > 
> 
> > but will there be a dedicated ion gun? like other ss13 servers?
> 
> 
> 
> I found only Ion Rifle and X-01 on tg wiki that shoot ion bolts. Anyway, Ion rifle useful against mechs, but battle mechs won't be added soon, so i see no point to add ion rifle for now.

What about borgs?

**Comment by BombasterDS** [comment]
> > > > @JoeHammad1844 The X-01 Mulitphase (Ion Mode), X-Ray Cannon, Disabler, and Diabler SMG deal ion damage
> > 
> > 
> > > 
> > 
> > 
> > > but will there be a dedicated ion gun? like other ss13 servers?
> > 
> > 
> > I found only Ion Rifle and X-01 on tg wiki that shoot ion bolts. Anyway, Ion rifle useful against mechs, but battle mechs won't be added soon, so i see no point to add ion rifle for now.
> 
> What about borgs?

Borgs not that kind of enemies to special weapon to counter them. You won't run into brig to get ion rifle if some rogue borg attacks you - you'll shoot him with pistol or disabler.

**Comment by BombasterDS** [comment]
> standard borg protection is far too high

I decreased it to 5 flat brute protection and 20℅ heat.

**Pull request merged**
