### PR TITLE
Recycle update - Part one

### PR DESCRIPTION
**Pull request by BombasterDS**
## About the PR
Updates recycling in the game:
- Now recycler respects stacks, item slots and entity containers
- Fixed recycler was able to process one item several items
- Changed Physics Composition to match crafting recipes. Recycler efficiency changed 1 -> 0.25.
- All items from autolathe and protolathe and most items from uniform printer can be recycled too.
- All organs except brain can be recycled to biomass.
- Added all species cubes to biocube fabricator. Added skibidi cube to emagged version.
- Crates and lockers can be recycled. Secured lockers and crates can be recycled only when unlocked.

## Why
Recycling should be more useful in the game.

:cl:
- add: All species humanoid cubes can be crafted on biocube fabricator 
- tweak: All protolathe and autolathe items now can be recycled
- tweak: All organs except brains can be recycled to biomass
- tweak: Crates and lockers now can be recycled with all containment in it.
- fix: Recycler now respects stacks
- fix: Fixed recycler was able to process one item several times

### CODE REVIEW

**Comment by Aineias1** [comment]
You mean we can mass print urists?

**Comment by BombasterDS** [comment]
> You mean we can mass print urists?

If you'll have enough biomass. Anyway, all humanoids have random appearance and names.

**Comment by BombasterDS** [comment]
Well shit... Test don't care about recycler efficiency... I guess i'll need to change all prices again T_T

**Comment by TurboTrackerss14** [comment]
Interesting commit to move the svallin to secfab only. 
Why?

**Comment by BombasterDS** [comment]
> Interesting commit to move the svallin to secfab only. Why?

Svalinn is full-fledged weapon and should be i security techfab, i don't know why it was craftable in protolathe. I wanted to move more recipes, but i think i'll do it later.

**Comment by TurboTrackerss14** [comment]
>i don't know why it was craftable in protolathe.

It used to be the RD's pistol. 
When it got removed it got put into a t3 research. 
https://github.com/space-wizards/space-station-14/pull/22045
(in the nicest way possible this took 5 minutes max to learn and like 3 github searches. ask around or look yourself?)

It has remained a weak, ineffectual, throwaway weapon for the longest time. 
However the recent changes to battery damage [here](https://github.com/Goob-Station/Goob-Station/pull/895) made it half decent for mass production or even just arming a small militia. 
It's not anywhere near strong enough to be pushed to "secfab only" status in my opinion. 

if the path of this pr is secretly turning from "recycling update" to "maybe reorganizing fabricator item lists" I would suggest actually renaming it or drafting it. Because that by itself is just straight up not in the scope of a "recycle update" to go around doing weird changes.

**Pull request merged**
