### PR TITLE
Alchemy bones

### PR DESCRIPTION
**Pull request by ARMOKS**
About the PR
Added the following chems:
Alchemical Precursor
Tenebris
Albedo
Brass
Disgusting mess
Bluespace essence
Citrinitas
King's yellow
Empowered lead
Aqua fortis
Aqua regia
Aqua tofani
Aqua vitae
Rubedo

Some chems can change metals into other metals, or create chems that were previously impossible to make.
Some chems have overheat temperatures that will cause negative effects to happen.
Massive part 2 coming soon based off citrinitas and rubedo

Why / Balance
Chem currently has very little to do, now they will have more, also allows chem to help the station overall and not just medbay.

Requirements:
- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-
- [X] I have added media to this PR or it does not require an ingame showcase. (too much to show, but it works)

Changelog

:cl:
add: Alchemy fundamentals
add: TONS of chemicals
add: omni recipe based on alchemy
add: vestine recipe based on alchemy
tweak: Nerfed omni to incentivize the creation of more advanced chems

### CODE REVIEW

**Comment by WhiteGorila** [comment]
Im conjuring my shit, mixing potions in my cauldron, turning tiders into frogs

**Comment by JoeHammad1844** [comment]
ghetto maint chemistry should be more possible, but without a chem master its impossible to separate chems.. I wanna grind flares and shit to make bicard

**Comment by Aviu00** [comment]
Changelog doesn't work like that.
It should be:
:cl:
- add: Added fun!

and not:
:cl:
add: Added fun!

Also yaml linter fail (don't use backslashes)

**Comment by ARMOKS** [comment]
goddamn it

**Comment by ARMOKS** [comment]
the fail is most likely a a heisenbuild error on goob, all the content works correctly and runs fine for me

**Comment by a-person5660** [comment]
you gotta make kings yellow turn you to stone or some shit, its too peak of a refrence to do nothing.

**Comment by ARMOKS** [comment]
> you gotta make kings yellow turn you to stone or some shit, its too peak of a refrence to do nothing.

doing this now

**Comment by a-person5660** [comment]
and alchemic precursor when mixed with blood should make gold bars (noita refrence)

**Comment by ARMOKS** [comment]
IT IS DONE I HAVE WON OVER THE MACHINES

**Pull request merged**
