### PR TITLE
Paranormal damage

### PR DESCRIPTION
**Pull request by RealFakeSoof**
## About the PR

Added (and fixed)paranormal damage which consists of holy, unholy, and psychic damage. Also gave chaplain/ert chaplain a gun that does 15 holy damage.
## Why / Balance

Chap and heretic need more features
## Technical details

Slightly less shitcode 
## Media

https://discord.com/channels/1202734573247795300/1236697829171527841/1307186963996086402
## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl:
- add: Made chaplain great again

## Summary by CodeRabbit

- **New Features**
	- Added new damage types: Holy, Unholy, Psychic, and Paranormal.
	- Introduced new entities including various animals and the WeaponGodGun.
	- New action: ActionBibleSummon for summoning bibles.

- **Enhancements**
	- Expanded damage container configurations for better gameplay mechanics.
	- Updated starting gear for roles, particularly the Chaplain and Security.

- **Bug Fixes**
	- Minor adjustments made to ensure proper functioning of existing entities and damage calculations.

- **Documentation**
	- Updated metadata for health analyzer and weapon resources.

### CODE REVIEW

**Comment by RealFakeSoof** [comment]
hopefully i didn't forget something massive with this one

**Comment by RealFakeSoof** [comment]
i forgot to say this in the pr, but here's a list of what heals what:
- Ethanol - Heals small amounts of paranormal
- Holywater - Heals the same amount as ethanol, but also heals some extra unholy
- Bible - Heals large amounts of paranormal, and some extra unholy
- Necronomicon - Heals holy for the same amount bible heals unholy
- Blood - Drinking it heals small amounts of unholy
- Mannitol - Heals psychic

If you think that that is "not enough healing" the only one of these damage types that is currently used(holy) only affects like 2ish mobs and is only used by one weapon

**Review by ia74 — APPROVED** [review]
LGTM :+1: Best code ever written. This guy also saved me from a car crash and is basically Tyler, the Creator, but better. Call him Tyler, the Betterer.

**Comment by Aidenkrz** [comment]
image

**Pull request closed without merging**
