### PR TITLE
Rifle Buffs

### PR DESCRIPTION
**Pull request by TwoDucksOnnaPlane**
## About the PR

Buffed .30 and .20 rifle damage, to set them apart from SMGs and increase viability
Also renamed .30 in flight to actually be .30 rifle.
## Why / Balance

Should hopefully result in people actually picking them up instead of a drozd first.

The only major upset I see is the L6SAW and ROW getting a buff since they use .30 also.

Do note that these were balanced around wearing a basic armor vest and rifles will 5 shot from perfect condition and 4 shot from slight damage.
## Technical details

couple line yaml change
## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl:
- tweak: Buffed .30 and .20 caliber damages.

## Summary by CodeRabbit

- **New Features**
	- Updated names for various light rifle ammunition types to reflect accurate caliber specifications.
- **Bug Fixes**
	- Enhanced damage values for several bullet types, improving their effectiveness in gameplay:
		- Increased Piercing damage for light rifle bullets.
		- Adjusted damage values for incendiary and uranium bullets across both light and standard rifle categories.

### CODE REVIEW

**Comment by JoeHammad1844** [comment]
I agree

**Comment by whateverusername0** [comment]
4 bullets to kill someone :goberserk:

**Comment by TwoDucksOnnaPlane** [comment]
no no no, 4 bullets to kill someone *unarmored* :trollface:

**Comment by a-person5660** [comment]
8-9 bullets to kill a nukie :trollface:

**Comment by deltanedas** [comment]
crew stealing an l6 now instant crew major

**Comment by Aviu00** [comment]
Just nerf pistol rounds instead :trollface:

**Comment by JoeHammad1844** [comment]
The only guns nukies can buy that uses 30 rifle is the mosin and L6 by the way

**Comment by whateverusername0** [comment]
just don't
you must close pr NOW :godmode: ⚡

**Comment by JoeHammad1844** [comment]
> just don't you must close pr NOW :godmode: ⚡

.20 rifle only does one more point of damage than .35 auto

**Comment by JoeHammad1844** [comment]
I think nukies would have to be able to buy AKs for this to go through otherwise it's a massive crew buff

**Comment by JoeHammad1844** [comment]
yay

**Pull request merged**
