### PR TITLE
Nukie planet update

### PR DESCRIPTION
**Pull request by BombasterDS**
## About the PR
- Added hotplate, electolyzer and centrifuge to nukie med.
- Added directional sighs for easier navigating.
- Removed RCD.
- Added intellicard and intercom electronics for interactions with AI.
- Shuttle turrets not disposable anymore, Their amount inside the shuttle decreased and they don't block the passage. Moved outside turrets from shuttle walls. Added two more turrets near north entrance.
- Axe moved from inaccessible air chamber to fireaxe case with nukeops access (You can find it near atmos).
- Two papers of codes replaced with nuke codes folder on shuttle.

:cl:
- tweak: Nukie planet medbay now has more tools
- tweak: The nukie planet now has signs for easier navigation
- tweak: The nuke code papers now come in a folder
- tweak: Nukies now get an intellicard and intercom electronics to interact with AI
- fix: The nukie planet's fire axe is now accessible
- fix: The nukie shuttle's turrets are not disposable anymore, and there aren't as many of them.

### CODE REVIEW

**Comment by JoeHammad1844** [comment]
you should also make the fireaxe actually accessible without breaking a window

**Comment by BombasterDS** [comment]
uuuhh, no sure about check fail...

**Comment by whateverusername0** [comment]
my man what did RCD do to you

**Comment by BombasterDS** [comment]
> my man what did RCD do to you

Though it to strong for nukies to have it roundstart. (anyway, that have many stuff there)

**Comment by whateverusername0** [comment]
btw can you make the nuke code folder spawn codes for each nuke? because nukies losing their nuke/tider hiding the nuke somewhere in maints is a big round staller
also the note wouldn't make sense then :trollface:

**Comment by JoeHammad1844** [comment]
> Though it to strong for nukies to have it roundstart. (anyway, that have many stuff there)

it's pretty temporary. will only get you through a few walls and doors before its empty and you have to toss it.
You COULD loot engis for more charges but you could already do that before hand so it doesnt really matter

**Comment by BombasterDS** [comment]
> btw can you make the nuke code folder spawn codes for each nuke? because nukies losing their nuke/tider hiding the nuke somewhere in maints is a big round staller also the note wouldn't make sense then :trollface:

I removed half of the text in note :trollface:

**Comment by whateverusername0** [comment]
> I removed half of the text in note :trollface:

mad
ok

**Review by whateverusername0 — APPROVED** [review]

**Pull request merged**
