### PR TITLE
ling check & guidebook entry

### PR DESCRIPTION
**Pull request by whateverusername0**
:cl:
- add: Added a guidebook entry for changelings.
- add: Added a ling check. Read more about it in the guidebook.

### CODE REVIEW

**Comment by whateverusername0** [comment]
what why

**Comment by whateverusername0** [comment]
i think diffs are broken

**Comment by whateverusername0** [comment]
not anymore

**Review by Piras314 — APPROVED** [review]

**Comment by a-person5660** [comment]
Will slime lings bleed red blood? I think they will need their own blood prototype, also it should probably be meat kudzu not regular kudzu that spawns out of the centrifuge.

**Pull request merged**
