### PR TITLE
IPC thief objective: steal power cells

### PR DESCRIPTION
**Pull request by jorgun**
## About the PR

give IPC a race objective

## Why / Balance

a silicone driven race, when they get greedy it is collecting power.
the ammoints is 5-30 becuse i dont know, its not that hard to collect powercells but lugging around duffels full of it will be sus.

## Media

image

## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl:
- add: IPC thiefs have a new objective to collect power cells

### CODE REVIEW

**Comment by Piras314** [comment]
why does it say "cellses"
image

**Comment by Piras314** [comment]
ah you didn't make a localization at all, see yaml linter fail

**Comment by jorgun** [comment]
never been good whit localisation

**Comment by jorgun** [comment]
image

**Comment by jorgun** [comment]
ah wrong button

**Comment by deltanedas** [comment]
making 30 items in an autolathe isnt fun at all

**Comment by JustSome1Nearby** [comment]
Its TOO EASY. YOU CAN JUST PRINT EM

**Comment by JustSome1Nearby** [comment]
Cap s lazer pistol got infinite ancient battery, make thief steal that

**Comment by jorgun** [comment]
cap lazer is already a objective.
it is true you can just print these. that is not the point it is the silicone having adiction to power cells, the same way moths have to lamps

**Comment by deltanedas** [comment]
still isnt fun to print 30 things then put them in a crate because you physically cant hold them all

**Comment by a-person5660** [comment]
make it require high capacity cells instead of any capacity so its a bit harder.

**Comment by Piras314** [comment]
It's fine to have easy objectives man.

**Review by Piras314 — APPROVED** [review]

**Pull request merged**
