### PR TITLE
Louie plushie (hi louie <3)

### PR DESCRIPTION
**Pull request by BeeRobynn**
adds louie plush to the game
higher spawn in maints lockers than other plushies because rat mode
first ever pr, big wins for the bee community

image

### CODE REVIEW

**Comment by Aidenkrz** [comment]
Lower the locker chance to 0.05
and add to plushie crate 
then this is good 👍

**Comment by BeeRobynn** [comment]
That's, fine, will do in a bit

**Comment by Piras314** [comment]
thats a BIG plushie...

**Comment by BeeRobynn** [comment]
> thats a BIG plushie...

image
 
 hes a big guy

**Pull request merged**
