### PR TITLE
Adding Phobos for Goob station!

### PR DESCRIPTION
**Pull request by Starbuckss14**
## About the PR

This adds Phobos station a small to mid pop map with a asteroid theme. Has a verry chaotic feeling thus making it good for Goob!

## Why / Balance

I added more walls to prevent the issues with spacing as mentioned in the wizden PR. Also added a NTR office and BlueShield office both with spawns.

## Media

mapren
Screenshot (73)
Screenshot (74)
Screenshot (75)
Screenshot (76)
Screenshot (77)
Screenshot (78)
Screenshot (79)
Screenshot (80)

FYI the map render is out of date but still gives a general view of the map (the map renderer is still fucked)
- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: Added Phobos map

### CODE REVIEW

**Comment by CatMagic1** [comment]
That isn't what the changelog is for.
Changelog only communicates the changes made to players, like... A pr that adds a new gun would say "Added a new gun" in the changelog. So just keep the "Added Phobos Map"

**Comment by Starbuckss14** [comment]
> That isn't what the changelog is for. Changelog only communicates the changes made to players, like... A pr that adds a new gun would say "Added a new gun" in the changelog. So just keep the "Added Phobos Map"

Ok I will fix that sorry. HONK!
download

**Comment by Aidenkrz** [comment]
mf check failer

**Comment by CatMagic1** [comment]
Love the blueshield & nt rep rooms

A second sectech in the blueshield room may be a bit much though, considering

- The blueshield is already right next to sec
- There is a sectech full of gear and the only thing between it and maints is a reinforced window

**Comment by Starbuckss14** [comment]
> Love the blueshield & nt rep rooms
> 
> A second sectech in the blueshield room may be a bit much though, considering
> 
> * The blueshield is already right next to sec
> * There is now a sectech full of gear and the only thing between it and maints is a reinforced window

Thanks! I fixed the sec tech! Let me know if there are any other issues?

**Comment by CatMagic1** [comment]
I'd say keep the med doors in morgue but add syndicate airlocks to the the room that has syndie stuff.
Also the big wood plank tiles in the nt rep room look a bit off but you can choose to keep those or not

**Comment by Starbuckss14** [comment]
> I'd say keep the med doors in morgue but add syndicate airlocks to the the room that has syndie stuff. Also the big wood plank tiles in the nt rep room look a bit off but you can choose to keep those or not

It used to have syndi doors when it was open as a PR on wizden but they said to change it. I wish to keep them as med doors if that's ok?

As per the NTR floor I am a fan of it and it makes him look more special from the other wood in other rooms.

Do you like the stolen nukie shuttle as a add on to med?

**Comment by CatMagic1** [comment]
> > I'd say keep the med doors in morgue but add syndicate airlocks to the the room that has syndie stuff. Also the big wood plank tiles in the nt rep room look a bit off but you can choose to keep those or not
> 
> It used to have syndi doors when it was open as a PR on wizden but they said to change it. I wish to keep them as med doors if that's ok?
> 
> As per the NTR floor I am a fan of it and it makes him look more special from the other wood in other rooms.
> 
> Do you like the stolen nukie shuttle as a add on to med?

I just think the syndie doors work better since the 2 rooms have syndie items (syndie soap is actually pretty strong) and also it's work well as a little syndie base which isn't really found on any other station.

Also I can't see the stolen nukie shuttle, the maprender ain't workin send screenshots\

Also you don't have to do anything I say, I'm not a maintainer

**Comment by CatMagic1** [comment]
Also try and add 1-2 more water tanks next to welding tanks in maints. I only see one.

**Comment by Aidenkrz** [comment]
Closing as it appears [Starbuckss14](https://github.com/Starbuckss14) isn't working on this anymore.

**Comment by Starbuckss14** [comment]
> Closing as it appears [Starbuckss14](https://github.com/Starbuckss14) isn't working on this anymore. 
Dog. I was told the content freeze was going to delay it? I was just waiting for the freeze to be lifted.

**Pull request closed without merging**
