### PR TITLE
Adds more lobby backgrounds + round end audios

### PR DESCRIPTION
**Pull request by BeeRobynn**
Adds more lobby background from the discord and round end audios from funny videos

### CODE REVIEW

**Comment by Aidenkrz** [comment]
Lets remove the round end audios, the videos are funny but lets keep it to music for the lobby audios.

**Comment by BeeRobynn** [comment]
the round end audios are the stingers that play when the round restarts, not the music that plays in the lobby

**Comment by Aidenkrz** [comment]
point still stands, no moar audios!!!1!

**Comment by Aidenkrz** [comment]
unless they are public domain music

**Pull request merged**
