### PR TITLE
Fix Applicable Medication bug.

### PR DESCRIPTION
**Pull request by Tmanzxd**
## About the PR

- Fixed a bug where applicable medication stacks would revert back to 10 after 1 use.

## Why / Balance

- Did you know maxstacks were stored in a separate YML? Me neither, until now.

## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl:
- fix: Fixed a bug where applicable medication stacks would revert back to 10 after 1 use from fullstack.

## Summary by CodeRabbit

- **New Features**
	- Introduced new healing items: `tourniquet` and `healing toolbox`.

- **Improvements**
	- Enhanced healing effectiveness for several existing items, including `ointment`, `regenerative mesh`, `bruise pack`, and `medicated suture`.
	- Increased maximum stack counts for multiple items from 10 to 15, improving inventory management.

- **Adjustments**
	- Standardized sound paths for healing actions across various entities.

### CODE REVIEW

**Review by Piras314 — CHANGES_REQUESTED** [review]
Needs # Goobstation comments

**Comment by Tmanzxd** [comment]
Damn no being lazy.

**Review by Piras314 — APPROVED** [review]
You forgot to do it in healing.yml but I did it for you

**Comment by Tmanzxd** [comment]
ah those vals were not added previously or were reverted to their original vals

**Pull request merged**
