### PR TITLE
Gamemode Adjustments: Dynamic Just A Week Away Edition

### PR DESCRIPTION
**Pull request by TooSillyFennec**
## About the PR
A decent amount of gamemode adjustments! - event and secret Weight changes, new midround antag events [Late Ling and Heretic], survival removal, traitors rolling at 30-60 delay, revs at 20 player ratio, and changeling dual antag gamemodes have received an increase in changelings.

## Why / Balance
**Survival Removal -** Legitimately unfun. Better than kessler for the fact antags eventually exist- but the same exact problem: absolutely zero player created threat but extremely chaotic. Never really that fun of a gamemode and the weight's better shifted elsewhere, we have the antags to fill the "void" that's there. No, I'm not counting miss flukie "Here and Dead", and Weeb Antisocial "Never sees the crew ever" the Ninja as player created threat.

**Weight Changes -** Nukies have been decreased to 15% and from an overall 22% Spawnrate at 30+ Ready to 18% as Nukelings have been increased to 2%. Had enough of 5 nukler games in a row? Here's your fix :3 - Kinda. Barely a spawnrate decrease at 30+ Players ready, but a pretty major one at lowpop. As there's 9% Left from these gamemodes, 4% went to Lings [15%],  and 5% to Traitorlings. [10%],

**Antag Event Weight Decreases & New Mid Antag Events-** Makes games generally last longer than the current 1 hour average as ghost role antags have a 50% Decrease and Sleeper agents a 25% Decrease to their chances. Midround Antags are more common however by 50% due to the new Genome Awakening [Late Changeling] and Sudden Enlightenment [Late Heretic] events at half the weight of Sleeper Agent. Same announcement w/ a max of 2 Lings and 1 Heretic respectively. All Midround Antag events now start at 20 minutes, including sleeper agents.

**CalmLing Changes -** Calmling has only 2 Lings compared to CalmTraitor's 5 agents. This generally neutered the gamemodes that use it. Calmling now has a max of 4 but a player ratio of 20, as lings are generally stronger than agents. Traitorling now has a max of 9 antags. Dual antag games can't even roll sub gamemodes and Traitorling/Revling/Nukeling had less antags than normal games and their agent counterparts even before sub gamemodes. This fixes that.

**Traitor Roll Delay Change -** Every antag similar to traitor now uses 30-60 delay, and antag rolling may actually be easier when people know the times they roll at :godo: - So I made them match their counterparts at 30-60 delay. This generally places them at the same start as their counterparts, and prevents people from just cryoing after 8 minutes have passed to antag roll with barely any trace. 

**Revs at 20 Player Ratio -** Revs generally have an easier time here than Wizard's den for example. also, having less at lower player counts and preventing them at player counts that normally barely ever have more than 1-2 command/sec helps them not crush the command staff that easily. That starting flash isn't worth an entire third of the crew anymore!

## Technical details
0 C#, but the heretic gamerule was moved to the correct gamerules folder.

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

**Changelog**
:cl:
- add: You can now roll Changeling or Heretic during an Enemy Communication instead of just Sleeper Agent.
- remove: The Survival gamemode has been removed. Survival's Death Party at MY PLACE!!!
- tweak: Nukies have a decreased chance to spawn with their base gamemode at 15% from 20%, and Changelings an increased amount, with changelings at 15% from 10%, TraitorLing at 8% from 5%, and NukeLing at 2% from 1%.
- tweak: Ghost role antags spawn at a halved chance, but mid-round antags at an increased chance. Generally, rounds shall be calmer later into the game, allowing longer rounds to be more common.
- tweak: Traitors now roll at the 30-60 second mark, like Changelings and Heretics.
- tweak: Revs need more players to start as a game, and have a higher player ratio per headrev at 20 from 15.
- tweak: Changeling Dual Antag gamemodes now actually spawn a decent amount of changelings. No longer do they always spawn 2 of them!

## Summary by CodeRabbit

- **New Features**
	- Introduced new game events: "GenomeAwakening" and "SuddenEnlightenment" for enhanced gameplay dynamics.
	- Added a new game preset "Trifecta" combining elements of existing modes.
	- Introduced the "Heretic" role with specific game rules and configurations.

- **Gameplay Adjustments**
	- Reduced occurrence rates of certain events to improve game balance.
	- Adjusted timing and player requirements for various game rules, allowing for quicker starts and more dynamic gameplay.

- **Bug Fixes**
	- Recalibrated antagonist probabilities for better balance in gameplay.

### CODE REVIEW

**Comment by cheki-ss14** [comment]
I'm in support of this. I think it could help reduce the amount of people I see cryoing before 10 minutes, and encourage people to play the whole round.

**Comment by TooSillyFennec** [comment]
Guh test fail

**Comment by Icepicked** [comment]
there goes my free ninja gamemode 😔 

Nice changes though.

**Comment by TooSillyFennec** [comment]
From the test it seems secret isn't picking a preset...

But it's excluding E V E R Y preset. I'm like 90% sure there's 0 reason for this. i'll test a couple of changes and if none including reverts work the check's just being dumb.

**Comment by whateverusername0** [comment]
i'm currently working on some sort of dynamic gamemode which will work this way: one major antag will be selected (nukies, revs, or a decent amount of solo antags), and 0-2 minor antags or gamerules coming with them depending on the amount of points gathered during the round which will also affect other gamerules spawning during the round.

so trifecta and other dual antag gamemodes will be cut off.

leaving midround lings and heretics is a godo, changing gamerule timing on traitors is a godo.

you should also change cling and heretic midround message to something else. there's plenty of voicelines and messages you can pick from (in 13), such as "N anomaly detected near the station. There is no additional data."; "Level 5 biological hazard detected aboard the station. All personnel must contain the outbreak." (which is currently used in zombies and will be used in blob when i get to it)

overall good PR

**Comment by TooSillyFennec** [comment]
> i'm currently working on some sort of dynamic gamemode which will work this way: one major antag will be selected (nukies, revs, or a decent amount of solo antags), and 0-2 minor antags or gamerules coming with them depending on the amount of points gathered during the round which will also affect other gamerules spawning during the round.
> 
> so trifecta and other dual antag gamemodes will be cut off.
> 
> leaving midround lings and heretics is a godo, changing gamerule timing on traitors is a godo.
> 
> you should also change cling and heretic midround message to something else. there's plenty of voicelines and messages you can pick from (in 13), such as "N anomaly detected near the station. There is no additional data."; "Level 5 biological hazard detected aboard the station. All personnel must contain the outbreak." (which is currently used in zombies and will be used in blob when i get to it)
> 
> overall good PR

The point of using Enemy Communication is to alert the crew there's a new antag but not what exact antag. if desired I'm able to change them still, I'd use anomaly for heretics and find a fitting one for lings.

Also i'm gonna remove trifecta to test if that makes the tests not be dumb anyways, so that makes me care a bit less that I'm nuking it. Also maybe add a couple of roundstart minor/solo antags when you do dynamic to the major antags to do the role of their dual antag variants by the way. Great to hear dynamic's actually a real week away.

**Comment by TooSillyFennec** [comment]
Test fail seems unrelated to my PR, how did adding trifecta kill secret as a gamemode? who knows :3

**Comment by whateverusername0** [comment]
> The point of using Enemy Communication is to alert the crew there's a new antag but not what exact antag.

also can you do it like in 13? when there's traitors regardless of if it's midround or roundstart the message will still play

**Comment by TooSillyFennec** [comment]
> > The point of using Enemy Communication is to alert the crew there's a new antag but not what exact antag.
> 
> also can you do it like in 13? when there's traitors regardless of if it's midround or roundstart the message will still play

pretty sure it's any antag that's not "external" actually. external = nukies/wizard and there's a chance for it to not happen even when there's internal antags, and a chance for it to happen with no internal antags. it's a dynamic thing pretty sure.

**Review by Piras314 — CHANGES_REQUESTED** [review]
I think survival is a fine gamemode to have on a low %, even if it's not necessarily the best. Also update the folder to _Goobstation, forgot about this for a bit.

**Comment by Piras314** [comment]
the conflicts are because those files were moved to Resources/Prototypes/_Goobstation/

**Comment by Piras314** [comment]
@TooSillyFennec

**Comment by TooSillyFennec** [comment]
Dynamic was a week away after all!!!! :3

**Pull request closed without merging**
