### PR TITLE
Make flaps un-unanchorable

### PR DESCRIPTION
**Pull request by Aidenkrz**
## Why / Balance
Make NT Airfryers :tm: a little harder to make
https://youtu.be/6_zkG4TBkAg

**Changelog**
:cl:
- tweak: You can no longer unanchor flaps.

### CODE REVIEW

**Comment by Plyushsune** [comment]
Screenshot_20241209_140924_Discord

**Comment by deltanedas** [comment]
nobody tell durk about holofans or just grilling them normally

**Comment by RatherUncreative** [comment]
The real buff is some tider can't annoy me by removing the plastic flap in front of cargo and walking away with it.

**Comment by JoeHammad1844** [comment]
Igondolad pr

**Comment by WhiteGorila** [comment]
this is wizden level mald pr, in fact re add the ability to make plastic flaps

**Comment by Piras314** [comment]
literally 1984 vro...

**Comment by Aidenkrz** [comment]
piras literally no one asked you

**Comment by Aidenkrz** [comment]
> nobody tell durk about holofans or just grilling them normally

the point is to make it harder to do it. not impossible. If I wanted to make it impossible id just make tranq only affect players and not mobs???

**Comment by JoeHammad1844** [comment]
another durk selfmerge classic

**Comment by Piras314** [comment]
this is straight up just stupid

**Pull request merged**
