### PR TITLE
Skubstub, Removal of "twosides", Removal of missing/duplicate attribution listings

### PR DESCRIPTION
**Pull request by Piras314**
## About the PR

added skubstub removed twosides and fixed some attributions

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- remove: Removed the lobby screen "twosides"
- add: Added a remix of Skubstep, Skubstub to lobby and jukebox

### CODE REVIEW

**Comment by Aidenkrz** [comment]
FAIL!

**Comment by Piras314** [comment]
wizden songs being removed would only reduce downloads of first time players and only by less than 30mb i think so yeah

**Comment by Aidenkrz** [comment]
The song does not have any metadata, meaning it won't be displayed correctly in the lobby screen.

**Comment by Piras314** [comment]
@Aidenkrz

**Pull request merged**
