### PR TITLE
Makes the Energy Shotgun self-recharge and increases its max battery capacity

### PR DESCRIPTION
**Pull request by Piras314**
## About the PR

increased the max + starting charge of the energy shotgun to 1050 from 800, what it was before https://github.com/space-wizards/space-station-14/pull/31235. also made it self-recharge at a rate of 20, and before https://github.com/space-wizards/space-station-14/pull/31235 it was 25.

## Requirements

- [X] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- tweak: The Energy Shotgun now self-recharges again.
- tweak: The Energy Shotgun's maximum battery capacity has been increased.

## Summary by CodeRabbit

- **New Features**
	- Increased the maximum and starting charge for battery guns, enhancing their capacity.
	- Introduced a new battery type, `BatterySelfRecharger`, which features automatic recharging capabilities, improving gameplay sustainability.

### CODE REVIEW

**Comment by BombasterDS** [comment]
Energy shotgun was overpowered weapon before. It don't need self-recharging, but increasing max battery capacity would be nice.

**Comment by JoeHammad1844** [comment]
so does it have more shots or does it overall recharge slower?

**Comment by Piras314** [comment]
It has the same number of shots as pre-nerf and slower recharge. The other nerfs included in that PR weren't reverted either.

**Review by whateverusername0 — APPROVED** [review]
approved

**Pull request merged**
