### PR TITLE
space wind fast

### PR DESCRIPTION
**Pull request by starch70**
funny

## About the PR
faster default cvars for space wind cause i was bored

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**
:cl: Yakub
- tweak: space wind default cvar is faster

i dont think this would actually do anything if merged

### CODE REVIEW

**Comment by JustSome1Nearby** [comment]
The YEET update...?

**Comment by Piras314** [comment]
:pig2::dash:

**Comment by Beridot** [comment]
god bless you

**Comment by Aidenkrz** [comment]
1st off, this is how you change CVars, second off, no.

**Pull request closed without merging**
