### PR TITLE
Shitmed

### PR DESCRIPTION
**Pull request by gluesniffler**
ＢＯＲＮ ＴＯ ＳＨＩＴＣＯＤＥ
MAINTS IS A FUCK 
鬼神 Robust Em All 1984
I am mcdonalds wifi coder
410,757,864,530 TEST FAILS
image

## About the PR
This PR ports https://github.com/Simple-Station/Einstein-Engines/pull/1159.

## Can I take this PR for my repo?
I genuinely don't give a shit what you do with this shitcode. Pearl clutching code is cringe, code stealing is based. If you'd like to have evidence of me not giving a shit, message me on discord @ .mocho.

All I ask is if you do, please forward complaints, bug reports and potentially bug fixes :trollface:

## Is this the same as Starlight's surgery from Lilten's video?

Nope! We've got partial woundmed as well, simplified surgeries, and a few other features... More stuff soon to come for Cybernetics and shitpost surgeries like removing cat ears/tail :trollface: 

## Why / Balance
What's a week? Anyway durk asked me to port it.

## Technical details
A lot of things will break, expect a lot of merge conflicts every time anything BodySystem is touched now.

## Media
[Surgery Demo](https://www.youtube.com/watch?v=UhxS5b3LC-A "Surgery Demo")

Design Document - Click on the pizza abomination to see it.
[image](https://hackmd.io/@gluesniffler/Sygge7BaC)
(It's somewhat outdated, the project seems to be growing in scope now that I'm getting help).

## Requirements
- [X] I have fucked myself with a rake 10 times over. I can sadly still see PJB.
- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.
- [X] I have sent Kira a shipment of deodorant so he can be more presentable to society.

## Shoutouts
- Shoutout to [Ataraxia/Backmen (RU)](https://discord.gg/ss-14-backmen-ru-1053200453829132298) for helping out with getting the code stable!
- Shoutout to [Arcadis Station](https://discord.gg/YT4GmAsXXt) for the bug reports!
- Shoutout to [Einstein Engines](https://discord.gg/zU6p9udMrx) for standing my incessant whining about code breaking.
- Shoutout to [Starlight's](https://discord.gg/wAyQKB78fH) Darkrell for all of the help with figuring out optimizations for surgery.
- Shoutout to [RMC](https://discord.gg/rouny) for the Surgery code!
- Shoutout to Jezithyr for... Keeping us waiting I guess?

**Changelog**
:cl: Mocho
- add: What's a week? Anyway surgery is here.

### CODE REVIEW

**Comment by deltanedas** [comment]
unannounced newmed test codebase :trollface:

**Comment by gluesniffler** [comment]
> unannounced newmed test codebase :trollface:

pro

**Comment by deltanedas** [comment]
rmc ui stolen, instamerge

**Comment by Aidenkrz** [comment]
Oh boy! I can't wait to merge upstream!

**Comment by JoeHammad1844** [comment]
Can you permakill lings with decapitation?

**Comment by gluesniffler** [comment]
> Can you permakill lings with decapitation?

None of this shitcode was made with goob antags in mind, so im gonna have to hit you with the https://tryitands.ee/

**Comment by deltanedas** [comment]
ling abilities will 100% need adapting for this like the limb regen ability
brains being vestigial can be done with slime already i think so copying should be easy

**Comment by JoeHammad1844** [comment]
you can take somebody's eyes out and they will still be able to see

**Comment by yglop** [comment]
Surgery is just a week away ancestors were saying. And here we are. He did it.
He did it (1)

**Pull request merged**
