### PR TITLE
Remove inappropriate names from skeletons and ninjas.

### PR DESCRIPTION
**Pull request by Verbalase**
## About the PR
Removed a Ninja name and title along with a Skeleton first name. (Boner, Throat, Deep.)

## Why / Balance
There's no way in hell you don't know where I'm going with this. "Boner" come on. I'm not staring at my monitor watching a Ninja named "Deep Throat" bro.

## Technical details
Removed "Boner" from the Skeleton first name file. I also remove the "Deep" name along with "Throat" from the Ninja Titles file.

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
None?

**Changelog**
Removed certain Skeleton and Ninja names.

:cl:
- removed: Inappropriate names.

### CODE REVIEW

**Comment by Piras314** [comment]
didnt do the cl right, but it probably doesnt need a cl

**Review by Piras314 — APPROVED** [review]

**Comment by Verbalase** [comment]
> didnt do the cl right, but it probably doesnt need a cl

Was editing it.

**Comment by Piras314** [comment]
but wait! there's more! you should be doing this changes on a fork, not on our main repo PLEASE.

**Comment by Piras314** [comment]
It's fine for this PR but in future...

**Comment by Verbalase** [comment]
> but wait! there's more! you should be doing this changes on a fork, not on our main repo PLEASE.

bro thinks im the all knower of git shit

**Comment by Verbalase** [comment]
if i did this wrong, someone will die

**Comment by PoTeletubby** [comment]
still wont stop me from calling every skeleton I see a boner

**Comment by CatMagic1** [comment]
Watergate bruh

**Pull request merged**
