### PR TITLE
"essential" flatpacks (for admeme obviously)

### PR DESCRIPTION
**Pull request by starch70**
## About the PR
adds HORRIBLE flatpacks
full list:
- supermatter flatpack (Supermatter)
- energy flatpack (TeslaEnergyBall)
- gravity flatpack (Singularity)
- normal immovable toilet flatpack (ImmovableRodSkibidi)
- normal toilet flatpack (MobSkibidiToilet)
- asteroid flatpack (AsteroidDebrisLarger)
- cancer flatpack (MobMouseCancer)

## Why / Balance
it came to me in a vision
theres no need for balance if i make it a admeme (excuse to not put it in any catalogs)

## Technical details
made a flatpack-sequel.yml file because the normal flatpack.yml wasn't cool enough for me

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**
🆑 
- add: Added asteroid flatpack, normal toilet flatpack, normal immovable toilet flatpack, gravity flatpack, energy flatpack, and supermatter flatpack, and cancer flatpack (all of them are exclusive to entity spawner)

## Summary by CodeRabbit

- **New Features**
	- Introduced several new flatpack entities, including:
		- **SupermatterFlatpack**: Advanced flatpacking technology.
		- **TeslaBallFlatpack**: Provides free energy.
		- **SingularityFlatpack**: Early gravity generator.
		- **ImmovableSkibidiFlatpack**: An immovable toilet option.
		- **SkibidiFlatpack**: Standard toilet flatpack.
		- **AsteroidFlatpack**: Represents asteroid debris.
		- **CancerMouseFlatpack**: A normal mouse flatpack.

### CODE REVIEW

**Review by Piras314 — CHANGES_REQUESTED** [review]
add the ADMEME suffix to them

**Comment by starch70** [comment]
how do i give them the suffix in entity spawner im at school rn but i'll edit it with my phone

**Comment by starch70** [comment]
the people wanted a SM flatpack and i will give it to them

**Comment by Aidenkrz** [comment]
Hard no, just bloat, admins can modify a flatpak by just editing the components of an existing one.

**Comment by JoeHammad1844** [comment]
F5 key

**Pull request closed without merging**
