### PR TITLE
fix : wake up bug

### PR DESCRIPTION
**Pull request by jorgun**
## About the PR

fixes the problem whit sleepers not getting the wakeup action.

## Technical details

this is a check somhow conected to changling and not adding duplicate actions.

## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl:
- fix: fixed actions somtimes not showing up.

## Summary by CodeRabbit

- **New Features**
	- Updated action handling to allow the addition of duplicate actions, paving the way for more complex game interactions in the future.

### CODE REVIEW

**Review by whateverusername0 — APPROVED** [review]
ok

**Comment by jorgun** [comment]
@whateverusername0 i need to know what this check is for? if you can remember.
i did a few tests an nothing broke. but i cant be sure

**Comment by whateverusername0** [comment]
for duplicate actions i think

**Comment by jorgun** [comment]
this altso restores flashlights to borgs

**Comment by Aidenkrz** [comment]
Isn't the sleep bug a wizden problem? I don't think it has anything to do with changeling

**Comment by jorgun** [comment]
it is us. i can wake up just fine on wizden build.

for some reason when you sleep and wake up you keep the action in the actioncomponent.
if i made it temporary(make it delete itself when done) i get a long errorlog
so evrytime to wake up you get another instance of this action.

the borg have 2 instances of flashligth. not sure why. migth be 1 server side and 1 client side, i dunno
but this here changeling duplicate action check triggers and prevents the borg from having flashlights.

**Comment by jorgun** [comment]
image
this is from wizdenbuild.
this whuddent be a problem if not for the check for duplicate actions. 
that being said, this is probably altso a bug.

**Comment by jorgun** [comment]
done a few more tests, i dont know why this check existed to begin whit.

**Pull request merged**
