### PR TITLE
Riot bullet shield resprite

### PR DESCRIPTION
**Pull request by JoeHammad1844**
## About the PR

The riot bullet shield sprite has been changed to look closer to the riot shield

## Media

image

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
:cl:JoeHammad
- tweak: Changed the riot bullet shield sprite to look less weird

### CODE REVIEW

**Comment by Aidenkrz** [comment]
Read your checks

**Comment by JoeHammad1844** [comment]
the fucking checks changed since last time

**Comment by JoeHammad1844** [comment]
my face when i completely forget

**Comment by JoeHammad1844** [comment]
that should fix it

**Review by Piras314 — APPROVED** [review]

**Comment by JoeHammad1844** [comment]
this seems to have been reverted at some point

**Comment by JoeHammad1844** [comment]
oh i got it, i didnt change where the shield reads it's sprite from, fak

**Pull request merged**
