### PR TITLE
change ling and heretic playtime reqs

### PR DESCRIPTION
**Pull request by lanse12**
## About the PR
changes ling playtime req from 5 hours sec to 10 hours overall
changes heretic playtime req from 5 hours sec and 5 hours med to 15 hours overall

## Why / Balance
heretic 15 hours since there's less handholding
ling 10 hours since it's braindead
playing sec doesn't mean shit as your average tider is more robust than a 500 hour hos main
you don't need med playtime for heretic at all

### CODE REVIEW

**Comment by BombasterDS** [comment]
For heretic you need to know how to remove organs without gibbing body. Also you need to know how to fight in this game.
For ling you need to know how to fight in game.

I think sec and med time justified.

**Comment by lanse12** [comment]
never have i ever extracted organs out of someone  as heretic using surgery

**Comment by Piras314** [comment]
Sec requirement = Combat requirement, 5h sec is very reasonable for these antagonists. Nukies have the same.

**Comment by lanse12** [comment]
nukeop has no sec requirement

**Comment by Piras314** [comment]
I forgot about that, I think this is ok then, though I feel heretic might want sec playtime still since it's SO combat heavy, like how nukie commander has 5h sec requirement.

**Comment by lanse12** [comment]
i feel like heretic needs more overall since it's way harder than the other antags and you need a good amount of game knowledge to actually succeed

**Comment by RatherUncreative** [comment]
I feel like the most important thing about having sec time is knowing your enemy. Knowing what security can and can't do, or under what circumstances they can and can't arm up for is very useful for a station antag.

Getting killed by a changeling while playing security is a great learning experience for what you can do to them when you roll changeling.

**Comment by JustSome1Nearby** [comment]
Guys, please stop raising Sec requirements, i have like 2k hours of Launcher "playtime" in steam, played sec a LOT and KNOW how to play them in this spess game, from other servers too... But DONT WANT TO play them just for playtime req on this specific server!!! I am sci main! Let me have fun!

**Comment by Aidenkrz** [comment]
> Guys, please stop raising Sec requirements, i have like 2k hours of Launcher "playtime" in steam, played sec a LOT and KNOW how to play them in this spess game, from other servers too... But DONT WANT TO play them just for playtime req on this specific server!!! I am sci main! Let me have fun!

this dude doesn't know how to do a time transfer

**Comment by JustSome1Nearby** [comment]
No, i just dont use discord, through wich time transfer is done usually

**Review by whateverusername0 — APPROVED** [review]

**Comment by Sarahon** [comment]
Honestly I'm not against people playing more sec to get into a lot of the combat roles. Or just overall gameplay. But everyone is new at least once to these roles.

**Pull request merged**
