### PR TITLE
Nerf skeletons

### PR DESCRIPTION
**Pull request by Aineias1**
## About the PR

Nerfed skeletons, bones shouldnt be stronger than lots of meat

OLD STATS 
immune to everything except physical and heat damage
type: damageModifierSet
id: Skeleton
coefficients:
  Blunt: 1.1
  Slash: 0.8
  Piercing: 0.6
  Cold: 0.0
  Poison: 0.0
  Radiation: 0.0
  Asphyxiation: 0.0
  Bloodloss: 0.0
  Cellular: 0.0
flatReductions:
  Blunt: 5
## Why / Balance

Skeleton nukies are too OP, + skeleton antags are OP
## Technical details

changed code in Resources/Prototypes/Damage/modifier_sets.yml
## Media

image

## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

Skeletons are Nerfed
**Changelog**

## Summary by CodeRabbit

- **New Features**
	- Introduced multiple new damage modifier sets, enhancing gameplay interactions with various materials.
- **Modifications**
	- Updated coefficients for the existing `Skeleton` damage modifier set, improving balance in damage types.
	- Specified flat reductions for several damage modifier sets, impacting damage mitigation strategies.

### CODE REVIEW

**Comment by a-person5660** [comment]
mald PR much?

**Comment by a-person5660** [comment]
fr tho, skeletons are fine as they are. i dont get why you want it changed, they are unrevivable too, a fair trade off for better stats

**Comment by Aineias1** [comment]
> fr tho, skeletons are fine as they are. i dont get why you want it changed, they are unrevivable too, a fair trade off for better stats

their ONLY downside were: 150 till gib, 10% more blunt damage. Thats it. They dont bleed, they dont breathe so if they get in crit they WONT die if someone wont finish them. Skeletons shouldnt be stronger than any other specie because they are just bunch of walking BONES, without muscles,flesh etc. They aren't strong. And i made it just because @Piras314  told me to

**Comment by a-person5660** [comment]
if skeletons being a round start race was permenant i would aggree, but its a halloween event so i think its fine to have it be a bit unbalanced, i doubt its causing any issues and if it is then it will be over in a week anyway.

**Review by Piras314 — CHANGES_REQUESTED** [review]
why is this changing sprites

**Comment by Aineias1** [comment]
> why is this changing sprites

what.

**Comment by Aineias1** [comment]
FUUUCK

**Comment by Aineias1** [comment]
@Piras314  Changed sprites back to normal and fixed checks
 (I STILL DONT KNOW HOW THEY GOT CHANGED, ONLY THING I HAVE COMMITED IS THE DAMAGE MODIFICATORS)

**Review by Piras314 — APPROVED** [review]

**Comment by a-person5660** [comment]
wait you made skeletons take ~10% extra damage, truly a bruh moment.

**Comment by Piras314** [comment]
they're literally immune to most types of damage and have easy-to-get omnizine (milk)

**Pull request merged**
