### PR TITLE
Nukie planet and shuttle edits

### PR DESCRIPTION
**Pull request by Piras314**
## About the PR

Added some red lights, a syndicate stamp, some paper, a syndicate fax machine, a defib cabinet, some roller skates, among pequenos (sus) and a singular regular laser rifle to the nukie map. Added a recharger, more donk pockets, a cool hat, a defib cabinet, a bunch of jetpacks and red lights to the shuttle.

## Why / Balance

Nukies having access to at least 1 laser eliminates a big headache. This is the same for defibs and jetpacks.

## Technical details

n/a

## Media

not like a big redesign or anything
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- tweak: Modified nukie planet and shuttle

### CODE REVIEW

**Comment by Piras314** [comment]
These changes can be reverted at any time if there are merge conflicts, there's no need to maintain this if I don't do it.

**Comment by Aidenkrz** [comment]
Make the maps separate from their vanilla upstream counterparts so i dont have to deal with merge conflicts :)

**Comment by Piras314** [comment]
i guess so yeah

**Comment by Piras314** [comment]
@Aidenkrz done

**Comment by Aidenkrz** [comment]
Thanks :')

**Pull request merged**
