### PR TITLE
wet floor sign allows suit storage

### PR DESCRIPTION
**Pull request by JoeHammad1844**
## About the PR

if you wear a wet floor sign you can now put things on your suit storage slot
## Why / Balance

without this the only way non sec can have access to suit storage is if they break into a sec outpost and hack the secdrobe, if there even is one, to take a regular armor vest, or take a hardsuit. this gives crew and antagonists a low risk way of obtaining suit storage without having much armor while remaining mobile

and it has armor values, so it should be considered armor in this way

weapons like rifles and spears have slings on their sprite when you wear it on suit storage, but suddenly doesn't work when you don't have an armor vest on. (perhaps this can be solved by adding a sling item and craftable makeshift sling that allows you to wear guns and spears on the suit storage slot regardless of outerclothing?

## Media
image
image

## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

**Changelog**
:cl: JoeHammad
- tweak: wet floor signs, when worn, now allows suit storage

## Summary by CodeRabbit

- **New Features**
	- Introduced the `advanced mop` with enhanced functionalities for water reagent management.
	- Added a `golden plunger` with illumination effects.
	- Defined a new `Wet Floor Sign Mine Explosive` with explosive properties.
	- Expanded the definitions of janitorial items, including `damp rag` and `wet floor sign` with updated functionalities.
  
These updates enhance gameplay by adding new items and improving existing ones.

### CODE REVIEW

**Comment by JoeHammad1844** [comment]
funny fulldiff

**Comment by Aidenkrz** [comment]
webedit moment

**Comment by JoeHammad1844** [comment]
yeah, trying to fix that

**Comment by Aidenkrz** [comment]
reopen when you've fixed this

**Pull request closed without merging**
