### PR TITLE
Goofy Ah Felinid

### PR DESCRIPTION
**Pull request by Aidenkrz**
## Why / Balance
im just a silly little guy

## Media
https://github.com/user-attachments/assets/d007d635-8d4b-4b6b-b465-fa0a3a5716f2

**Changelog**
:cl:
- remove: Removed Felinids from command.
- tweak: Felinids resprited to look more realistic.
- tweak: Felinids renamed to their true name, Gremlins.

### CODE REVIEW

**Comment by Aineias1** [comment]
another selfmerge

**Review by whateverusername0 — CHANGES_REQUESTED** [review]
where's the command removal

**Comment by Elijahrane** [comment]
Finally felinids have reached their true potential

**Comment by Dead-Flag-Blues** [comment]
reporting this to PJB for racism

**Comment by whateverusername0** [comment]
> reporting this to PJB for racism

lol

**Pull request merged**
