### PR TITLE
remove KesslerSyndrome

### PR DESCRIPTION
**Pull request by yglop**
## About the PR
Remove KesslerSyndrome gamemode from secret_weights.

## Why / Balance
John told me to do so.

## Summary by CodeRabbit

- **New Features**
	- Adjusted role probabilities to enhance gameplay dynamics, increasing the likelihood of encountering the "Changeling" role.
	- Removed the "KesslerSyndrome" role from active gameplay, streamlining role options.

### CODE REVIEW

**Review by whateverusername0 — APPROVED** [review]

**Comment by whateverusername0** [comment]
based, merge now

**Comment by Piras314** [comment]
why

**Comment by whateverusername0** [comment]
because meteors suck

**Comment by vanilia123** [comment]
Meteors do suck. On Goob we dont have enough "smart" engineers to even power up station, so how do you expect them to keep up with fixing spacings. Keesler Syndrome always looks the same, arrivals spaced, distro fucked, people slowly dying till evac. Not that fun.

**Pull request merged**
